// ---- FIGHTERS roster row ----
 { name: "Jorge Rivera", division: "MW", rank: "NR", record: "20-9-0", initials: "JR", country: "" },

// ---- FIGHTER_STATS ----
  "Jorge Rivera": { ht:"6'1\"", dob:"1972-02-28", reach:'73"', stance:"Orthodox", slpm:3.27, strAcc:"50%", sapm:2.42, strDef:"57%", kd:1.04, tdLanded:0.91, tdAcc:"50%", tdDef:"64%", subAvg:0.13, finRate:"80%", streak:1, gym:"" },

// ---- FIGHT_HISTORY ----
  "Jorge Rivera": [
    { date: "Jan 20, 2012", opponent: "Eric Schafer", result: "W", method: "KO/TKO", round: 2, time: "1:31", event: "UFC on FX: Guillard vs. Miller", org: "UFC" },
    { date: "Aug 6, 2011", opponent: "Constantinos Philippou", result: "L", method: "Decision (Split)", round: 3, time: "5:00", event: "UFC 133: Evans vs. Ortiz 2", org: "UFC" },
    { date: "Feb 26, 2011", opponent: "Michael Bisping", result: "L", method: "KO/TKO", round: 2, time: "1:54", event: "UFC 127: Penn vs. Fitch", org: "UFC" },
    { date: "Mar 31, 2010", opponent: "Nate Quarry", result: "W", method: "KO/TKO", round: 2, time: "0:29", event: "UFC Fight Night: Florian vs. Gomi", org: "UFC" },
    { date: "Oct 24, 2009", opponent: "Rob Kimmons", result: "W", method: "KO/TKO", round: 3, time: "1:53", event: "UFC 104: Machida vs. Shogun", org: "UFC" },
    { date: "Apr 1, 2009", opponent: "Nissen Osterneck", result: "W", method: "Decision (Split)", round: 3, time: "5:00", event: "UFC Fight Night: Condit vs. Kampmann", org: "UFC" },
    { date: "Jun 7, 2008", opponent: "Martin Kampmann", result: "L", method: "Submission", round: 1, time: "2:44", event: "UFC 85: Bedlam", org: "UFC" },
    { date: "Jan 19, 2008", opponent: "Kendall Grove", result: "W", method: "KO/TKO", round: 1, time: "1:20", event: "UFC 80: Rapid Fire", org: "UFC" },
    { date: "Feb 3, 2007", opponent: "Terry Martin", result: "L", method: "KO/TKO", round: 1, time: "0:14", event: "UFC 67: All or Nothing", org: "UFC" },
    { date: "Nov 11, 2006", opponent: "Edwin Dewees", result: "W", method: "KO/TKO", round: 1, time: "2:37", event: "The Ultimate Fighter 4 Finale" },
    { date: "Apr 1, 2006", opponent: "Timothy Williams", result: "W", method: "TKO", round: 1, time: "3:50", event: "WFL 6 Real: No Fooling Around" },
    { date: "Jan 16, 2006", opponent: "Chris Leben", result: "L", method: "KO/TKO", round: 1, time: "1:44", event: "UFC Fight Night 3", org: "UFC" },
    { date: "Oct 7, 2005", opponent: "Dennis Hallman", result: "W", method: "Decision (Unanimous)", round: 3, time: "5:00", event: "UFC 55: Fury", org: "UFC" },
    { date: "Sep 10, 2005", opponent: "Marcelo Azevedo", result: "W", method: "Decision (Unanimous)", round: 3, time: "5:00", event: "Cage Rage 13: No Fear" },
    { date: "Aug 6, 2005", opponent: "Danny Vega", result: "W", method: "Submission (Triangle Choke with Armbar)", round: 1, time: "0:47", event: "WFL 3: Unleashed" },
    { date: "Apr 30, 2005", opponent: "Anderson Silva", result: "L", method: "KO/TKO", round: 2, time: "3:53", event: "Cage Rage 11: Face Off" },
    { date: "Feb 26, 2005", opponent: "Alex Reid", result: "W", method: "KO/TKO", round: 1, time: "0:41", event: "Cage Rage 10: Deliverance" },
    { date: "Oct 22, 2004", opponent: "Rich Franklin", result: "L", method: "Submission", round: 3, time: "4:28", event: "UFC 50: The War of '04", org: "UFC" },
    { date: "Jul 10, 2004", opponent: "Mark Weir", result: "W", method: "TKO", round: 1, time: "-", event: "Cage Rage 7: Battle of Britain" },
    { date: "Apr 30, 2004", opponent: "James Gabert", result: "W", method: "TKO", round: 3, time: "4:10", event: "MMA: Eruption" },
    { date: "Jan 31, 2004", opponent: "Lee Murray", result: "L", method: "Submission", round: 1, time: "1:45", event: "UFC 46: Supernatural", org: "UFC" },
    { date: "Sep 26, 2003", opponent: "David Loiseau", result: "W", method: "Decision (Unanimous)", round: 3, time: "5:00", event: "UFC 44: Undisputed", org: "UFC" },
    { date: "May 3, 2003", opponent: "Solomon Hutcherson", result: "W", method: "KO/TKO", round: 1, time: "3:01", event: "USMMA 3: Ring of Fury" },
    { date: "Nov 30, 2002", opponent: "Andy Lagden", result: "W", method: "Submission (Rear Naked Choke)", round: 1, time: "-", event: "CWFC 2: Fists of Fury" },
    { date: "Sep 21, 2002", opponent: "Travis Lutter", result: "W", method: "TKO", round: 3, time: "3:46", event: "USMMA 2: Ring of Fury" },
    { date: "May 18, 2002", opponent: "Joe Nye", result: "W", method: "TKO", round: 1, time: "0:52", event: "USMMA 1: Ring of Fury" },
    { date: "Mar 22, 2002", opponent: "Brian Hawkins", result: "W", method: "KO/TKO", round: 1, time: "-", event: "TFC FightZone: Back in the Zone" },
    { date: "Aug 4, 2001", opponent: "Elias Rivera", result: "W", method: "TKO", round: 1, time: "6:50", event: "MD 3: Mass Destruction 3" },
    { date: "Jun 23, 2001", opponent: "Branden Lee Hinkle", result: "L", method: "TKO", round: 2, time: "1:54", event: "RSF 2: Attack at the Track" },
  ],
