#!/usr/bin/env node
/* Extract the live simulator scoring code + inline data from index.html into a
 * standalone Node module (_scorer.js) and a data dump (_sim-data.json), so the
 * EXACT production formula can be run offline for backtesting.
 *
 * Two honesty rewrites are baked into the generated scorer:
 *   1. Date.now()  ->  __now()   — a controllable clock, so "recency", age, and
 *      layoff are measured relative to the fight date being graded, not today.
 *   2. fighterDivisionRankBadge -> a controllable stub (defaults to null), so the
 *      backtest can disable CURRENT rankings (which would leak the future) and
 *      fall back to simEstimateHistoricalTier, which is point-in-time by design.
 * FIGHTER_STATS / FIGHT_HISTORY are captured in mutable closure bindings that the
 * harness swaps per-fight to the as-of-date reconstruction.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = __dirname;
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// Balanced-bracket slice starting at the opening { or [ at openIdx, string-aware.
function sliceBalanced(src, openIdx) {
  const open = src[openIdx];
  const close = open === '{' ? '}' : ']';
  let depth = 0, inStr = null, esc = false;
  for (let i = openIdx; i < src.length; i++) {
    const c = src[i];
    if (inStr) {
      if (esc) { esc = false; continue; }
      if (c === '\\') { esc = true; continue; }
      if (c === inStr) inStr = null;
      continue;
    }
    if (c === '"' || c === "'" || c === '`') { inStr = c; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) return src.slice(openIdx, i + 1); }
  }
  throw new Error('unbalanced from ' + openIdx);
}

// Grab `const NAME = <literal>;` and eval the literal value. Line-based: these
// are top-level consts whose closing }; / ]; sits alone at the start of a line
// (interior entries always end with },/],), so we scan for that terminator —
// far more robust than bracket-counting across a 60k-line data literal.
function extractLiteral(name) {
  const lines = html.split('\n');
  const re = new RegExp('(?:const|let|var)\\s+' + name + '\\s*=\\s*([\\[{])');
  let start = -1, isArr = false;
  for (let i = 0; i < lines.length; i++) {
    const m = re.exec(lines[i]);
    if (m) { start = i; isArr = m[1] === '['; break; }
  }
  if (start < 0) throw new Error('literal not found: ' + name);
  const closeRe = isArr ? /^\s*\];\s*$/ : /^\s*\};\s*$/;
  let end = -1;
  for (let i = start + 1; i < lines.length; i++) {
    if (closeRe.test(lines[i])) { end = i; break; }
  }
  if (end < 0) throw new Error('literal close not found: ' + name);
  const openCol = lines[start].search(/[\[{]/);
  const text = lines[start].slice(openCol) + '\n'
    + lines.slice(start + 1, end).join('\n') + '\n'
    + lines[end].replace(/;\s*$/, '');
  // eslint-disable-next-line no-eval
  return eval('(' + text + ')');
}

// Grab a full `function NAME(...) { ... }` body as source text.
function extractFunction(name) {
  const m = new RegExp('function\\s+' + name + '\\s*\\([^)]*\\)\\s*').exec(html);
  if (!m) throw new Error('function not found: ' + name);
  let i = m.index;
  while (html[i] !== '{') i++;
  const body = sliceBalanced(html, i);
  return html.slice(m.index, i) + body;
}

// Contiguous block of scoring functions: from the FIGHT SIMULATOR banner up to
// (but not including) the method-distribution / DOM-render code.
function extractSimBlock() {
  const start = html.indexOf('// ── FIGHT SIMULATOR');
  const end = html.indexOf('const SIM_UFC_WIN_WEIGHT');
  if (start < 0 || end < 0) throw new Error('sim block markers not found');
  return html.slice(start, end);
}

console.log('Extracting data literals...');
const FIGHTERS = extractLiteral('FIGHTERS');
const FIGHTER_STATS = extractLiteral('FIGHTER_STATS');
const FIGHT_HISTORY = extractLiteral('FIGHT_HISTORY');
console.log('  FIGHTERS:', FIGHTERS.length,
            '| FIGHTER_STATS:', Object.keys(FIGHTER_STATS).length,
            '| FIGHT_HISTORY:', Object.keys(FIGHT_HISTORY).length);

fs.writeFileSync(path.join(OUT, '_sim-data.json'),
  JSON.stringify({ FIGHTERS, FIGHTER_STATS, FIGHT_HISTORY }));

console.log('Extracting scoring source...');
let simBlock = extractSimBlock();
let calcAge = extractFunction('calcAge');

// Honesty rewrite #1: controllable clock. calcAge uses a no-arg `new Date()`
// (today) rather than Date.now(), so rewire that too — otherwise age is measured
// as-of today, not as-of the fight being graded (a point-in-time leak in the age
// term).
simBlock = simBlock.replace(/Date\.now\(\)/g, '__now()');
calcAge = calcAge.replace(/new Date\(\)/g, 'new Date(__now())');
calcAge = calcAge.replace(/Date\.now\(\)/g, '__now()');

const scorer = `/* AUTO-GENERATED by extract-sim.js — do not edit by hand. */
'use strict';
module.exports = function createScorer(initStats, initHistory, initFighters) {
  let FIGHTER_STATS = initStats;
  let FIGHT_HISTORY = initHistory;
  let FIGHTERS = initFighters;
  let __NOW = Date.now();
  let __rankBadge = function(){ return null; };
  let window = { FIGHT_STATS: null };   // stub for simControlNet (reads window.FIGHT_STATS)
  function __now(){ return __NOW; }
  function fighterDivisionRankBadge(name){ return __rankBadge(name); }
  function searchNorm(s){ return String(s==null?'':s).toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(); }
  function aliasCanonicalMatches(){ return []; }
  ${calcAge}

  ${simBlock}

  return {
    simWinProbability: simWinProbability,
    simPowerScore: simPowerScore,
    simPowerScoreBreakdown: simPowerScoreBreakdown,
    getSimProfile: getSimProfile,
    simVolatility: simVolatility,
    simRateCredibility: simRateCredibility,
    simStyleMatchupDelta: simStyleMatchupDelta,
    simRankClosenessFactor: simRankClosenessFactor,
    simHeadToHeadBoost: simHeadToHeadBoost,
    simUnprovenPenalty: simUnprovenPenalty,
    simControlNet: simControlNet,
    simControlTimeBoost: simControlTimeBoost,
    simSoftCap: simSoftCap,
    simLossFinishProfile: simLossFinishProfile,
    simFinishVulnerability: simFinishVulnerability,
    simDurabilityBoost: simDurabilityBoost,
    setStats: function(s){ FIGHTER_STATS = s; },
    setHistory: function(h){ FIGHT_HISTORY = h; },
    setFighters: function(f){ FIGHTERS = f; },
    setNow: function(ts){ __NOW = ts; },
    setBox: function(b){ window.FIGHT_STATS = b; },
    setRankBadge: function(fn){ __rankBadge = fn || function(){ return null; }; }
  };
};
`;
fs.writeFileSync(path.join(OUT, '_scorer.cjs'), scorer);
console.log('Wrote _scorer.cjs (', scorer.length, 'bytes ) and _sim-data.json');
