/* AUTO-GENERATED by gen-climb-data.cjs — the REAL sim scorer, browser-wrapped.
   Do not edit. Regenerate instead, so the game can never drift from the model. */
(function(){
  var module = { exports: null };
/* AUTO-GENERATED by extract-sim.js — do not edit by hand. */
'use strict';
module.exports = function createScorer(initStats, initHistory, initFighters) {
  let FIGHTER_STATS = initStats;
  let FIGHT_HISTORY = initHistory;
  let FIGHTERS = initFighters;
  let __NOW = Date.now();
  let __rankBadge = function(){ return null; };
  let window = { FIGHT_STATS: null };   // stub for simControlNet (reads window.FIGHT_STATS)
  function __now(){ return __NOW; }
  function fighterDivisionRankBadge(name){ return __rankBadge(name); }
  function searchNorm(s){ return String(s==null?'':s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(); }
  function aliasCanonicalMatches(){ return []; }
  function calcAge(dob) {
 const b = new Date(dob), n = new Date(__now());
 let age = n.getFullYear() - b.getFullYear();
 if (n < new Date(n.getFullYear(), b.getMonth(), b.getDate())) age--;
 return age;
 }

  // ── FIGHT SIMULATOR ──────────────────────────────────────────────────────
  function simFindFighter(query) {
    if (!query) return null;
    const q = searchNorm(query.trim());
    if (!q) return null;
    const roster = FIGHTERS.filter(f => f && f.name);
    const exact = roster.find(f => searchNorm(f.name) === q);
    if (exact) return exact.name;
    const partial = roster.find(f => searchNorm(f.name).includes(q));
    return partial ? partial.name : null;
  }

  function simGetFighterRoster(name) {
    return FIGHTERS.find(f => f && f.name === name) || null;
  }

  // Ordered ladders (lightest → heaviest) used to measure how many weight
  // classes apart two fighters are. Men's and women's divisions are kept
  // separate — there's no cross-gender matchup in MMA, so that's always
  // treated as an impossible simulation.
  const SIM_DIVISION_LADDERS = {
    men: ['FLW', 'BW', 'FW', 'LW', 'WW', 'MW', 'LHW', 'HW'],
    women: ['WSW', 'WFLW', 'WBW', 'WFW']
  };
  // "WFLY" is a pre-existing alternate code for Women's Flyweight used on a
  // handful of older roster entries — treat it the same as "WFLW".
  const SIM_DIVISION_ALIASES = { WFLY: 'WFLW' };
  const SIM_DIVISION_LABELS = {
    FLW: 'Flyweight', BW: 'Bantamweight', FW: 'Featherweight', LW: 'Lightweight',
    WW: 'Welterweight', MW: 'Middleweight', LHW: 'Light Heavyweight', HW: 'Heavyweight',
    WSW: "Women's Strawweight", WFLW: "Women's Flyweight", WFLY: "Women's Flyweight",
    WBW: "Women's Bantamweight", WFW: "Women's Featherweight"
  };

  function simDivisionLabel(div) {
    return SIM_DIVISION_LABELS[div] || div || 'Unknown';
  }

  function simDivisionInfo(div) {
    const d = SIM_DIVISION_ALIASES[div] || div;
    let idx = SIM_DIVISION_LADDERS.men.indexOf(d);
    if (idx !== -1) return { gender: 'men', index: idx };
    idx = SIM_DIVISION_LADDERS.women.indexOf(d);
    if (idx !== -1) return { gender: 'women', index: idx };
    return null;
  }

  // Returns the number of weight classes apart two divisions are, or
  // Infinity if they can't be compared (unknown division, or one men's
  // and one women's).
  function simDivisionDistance(divA, divB) {
    const a = simDivisionInfo(divA);
    const b = simDivisionInfo(divB);
    if (!a || !b || a.gender !== b.gender) return Infinity;
    return Math.abs(a.index - b.index);
  }

  // Custom autocomplete dropdown for the fighter-picker inputs. A plain
  // <input list="..."> datalist was tried first, but it's unreliable here:
  // Safari ignores the `list` attribute outright, and Chrome/Edge won't
  // reopen the suggestion popup on a second click into an already-focused,
  // already-filled input — both made it feel like fighters couldn't be
  // changed without a page refresh. This component is fully scripted so
  // selecting a new fighter always works, on any browser, any number of times.
  function simBuildAutocomplete(inputId, listId) {
    const input = document.getElementById(inputId);
    const list = document.getElementById(listId);
    if (!input || !list) return;

    let activeIndex = -1;

    function getRoster() {
      return FIGHTERS.filter(f => f && f.name).map(f => f.name);
    }

    function hideList() {
      list.style.display = 'none';
      list.innerHTML = '';
      activeIndex = -1;
    }

    // The dropdown uses position:fixed and is repositioned against the input's
    // live bounding rect (rather than relying on normal document flow). This
    // matters most on mobile: when the on-screen keyboard opens it eats the
    // bottom portion of the screen, so a dropdown anchored below the input via
    // simple absolute/top:100% positioning can end up rendered underneath the
    // keyboard (still "in the document" but not visible). Recomputing against
    // the visualViewport lets us flip the list above the input when there
    // isn't enough room below.
    function positionList() {
      const rect = input.getBoundingClientRect();
      const vv = window.visualViewport;
      const viewportHeight = vv ? vv.height : window.innerHeight;
      const margin = 6;
      const spaceBelow = viewportHeight - rect.bottom - margin;
      const spaceAbove = rect.top - margin;
      const showBelow = spaceBelow >= 120 || spaceBelow >= spaceAbove;

      list.style.left = rect.left + 'px';
      list.style.width = rect.width + 'px';
      list.style.margin = '0';

      if (showBelow) {
        list.style.top = (rect.bottom + margin) + 'px';
        list.style.bottom = 'auto';
        list.style.maxHeight = Math.max(80, Math.min(220, spaceBelow)) + 'px';
      } else {
        list.style.top = 'auto';
        list.style.bottom = (viewportHeight - rect.top + margin) + 'px';
        list.style.maxHeight = Math.max(80, Math.min(220, spaceAbove)) + 'px';
      }
    }

    function reposition() {
      if (list.style.display === 'block') positionList();
    }
    window.addEventListener('resize', reposition);
    window.addEventListener('scroll', reposition, true);
    if (window.visualViewport) {
      window.visualViewport.addEventListener('resize', reposition);
      window.visualViewport.addEventListener('scroll', reposition);
    }

    function renderMatches() {
      const q = searchNorm(input.value.trim());
      if (!q) { hideList(); return; }
      const roster = getRoster();
      const starts = [];
      const contains = [];
      for (const name of roster) {
        const ln = searchNorm(name);
        if (ln.startsWith(q)) starts.push(name);
        else if (ln.includes(q)) contains.push(name);
      }
      // Include fighters matched only by an alias (e.g. "King Green" -> Bobby Green).
      const _rosterSet = new Set(roster);
      const _already = new Set(starts.concat(contains));
      aliasCanonicalMatches(q, 'includes').forEach(nm => {
        if (_rosterSet.has(nm) && !_already.has(nm)) { contains.push(nm); _already.add(nm); }
      });
      const matches = starts.concat(contains).slice(0, 8);
      if (matches.length === 0) { hideList(); return; }
      // Only recompute the fixed position when the list is transitioning from
      // hidden to visible (i.e. once per "open" session), not on every single
      // keystroke. On real mobile keyboards the on-screen keyboard can still be
      // animating in/out for a couple hundred ms after focus, which spans
      // several rapid keystrokes if the user types quickly; recalculating
      // top/bottom/maxHeight against the viewport on every keystroke while
      // that animation is mid-flight can read a transient/stale viewport size
      // and park the list off-screen or with a collapsed height, making it
      // look like the list "disappeared" even though matches still exist.
      const wasHidden = list.style.display !== 'block';
      activeIndex = -1;
      list.innerHTML = matches
        .map(n => `<div class="sim-autocomplete-item" data-name="${n.replace(/"/g, '&quot;')}">${n}</div>`)
        .join('');
      list.style.display = 'block';
      if (wasHidden) positionList();
    }

    function selectName(name) {
      input.value = name;
      input.dataset.selected = name;
      hideList();
    }

    input.addEventListener('input', () => {
      input.dataset.selected = '';
      renderMatches();
    });
    input.addEventListener('focus', renderMatches);
    input.addEventListener('blur', () => {
      // slight delay so a click on a dropdown item registers before it's hidden
      setTimeout(hideList, 150);
    });
    input.addEventListener('keydown', (e) => {
      const items = list.querySelectorAll('.sim-autocomplete-item');
      if (!items.length) return;
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        activeIndex = Math.min(activeIndex + 1, items.length - 1);
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        activeIndex = Math.max(activeIndex - 1, 0);
      } else if (e.key === 'Enter') {
        if (activeIndex >= 0) {
          e.preventDefault();
          selectName(items[activeIndex].dataset.name);
        }
        return;
      } else if (e.key === 'Escape') {
        hideList();
        return;
      } else {
        return;
      }
      items.forEach((it, i) => it.classList.toggle('active', i === activeIndex));
    });
    list.addEventListener('mousedown', (e) => {
      const item = e.target.closest('.sim-autocomplete-item');
      if (!item) return;
      e.preventDefault();
      selectName(item.dataset.name);
    });
  }

  function initSimFighterPickers() {
    simBuildAutocomplete('simFighterA', 'simFighterAList');
    simBuildAutocomplete('simFighterB', 'simFighterBList');
  }

  function simPct(v, def) {
    if (v === undefined || v === null) return def;
    if (typeof v === 'string') {
      const n = parseFloat(v.replace('%', ''));
      return isNaN(n) ? def : n / 100;
    }
    return typeof v === 'number' ? v : def;
  }

  function simNum(v, def) {
    return typeof v === 'number' && !isNaN(v) ? v : def;
  }

  // The hand-maintained finRate stat is a career-wide total, which has the
  // same front-loading problem as the boosts above: a fighter's lifetime
  // finish rate can be propped up by regional finishes from years before
  // they reached UFC-level competition, AND by finishes from a decade ago
  // that say little about how they finish fights now. Prefers a finish rate
  // computed from UFC-only wins, weighting each one by recency (a finish in
  // the last year or two counts close to double a finish from 6+ years
  // back) rather than averaging the whole UFC tenure flat. Falls back to
  // the static career-wide figure when the UFC sample is too thin (<4 wins)
  // to trust.
  function simRelevantFinRate(name, staticFinRate) {
    const ufc = simFinishStats(name, true);
    if (ufc.wins < 4) return staticFinRate;
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    const now = __now();
    let weightedFinishes = 0, totalWeight = 0;
    hist.forEach(f => {
      if (f.result !== 'W' || f.org !== 'UFC' || !f.date) return;
      const d = new Date(f.date);
      const yearsAgo = isNaN(d) ? 3 : Math.max(0, (now - d.getTime()) / (1000 * 60 * 60 * 24 * 365.25));
      const weight = 0.5 + 0.5 * Math.max(0, 1 - Math.min(yearsAgo, 6) / 6);
      const isFinish = /^(?:KO|TKO|Submission|Technical Submission)\b/i.test(String(f.method || '').trim());
      totalWeight += weight;
      if (isFinish) {
        // A finish counts as less evidence of finishing power when the
        // opponent was already an established finish-vulnerable target --
        // simFinishVulnerability returns a negative number scaled by how
        // often/badly that opponent gets stopped, so this discounts (never
        // zeroes out, floored at 0.4x) the credit toward THIS fighter's
        // finish rate while the win still counts fully toward the sample
        // size (totalWeight) either way.
        const oppDiscount = Math.max(0.4, 1 + simFinishVulnerability(f.opponent));
        weightedFinishes += weight * oppDiscount;
      }
    });
    return totalWeight > 0 ? weightedFinishes / totalWeight : staticFinRate;
  }

  // Every per-fight box-score rate stat (striking output/accuracy,
  // knockdowns, takedown volume/accuracy/defense, finish rate, ...) is only
  // as trustworthy as the competition it was earned against. A handful of
  // lopsided performances against opposition that's never proven good
  // enough to rank can swing any of these to extreme, unrepeated levels —
  // it's a true reflection of those specific fights, just not yet a
  // reliable read on the fighter in general. simRateCredibility gives a 0-1
  // trust score per fighter, built from both UFC sample size and the
  // quality of any ranked opponents actually faced (see simRateCredibility
  // for the current formula — a single low-quality ranked win no longer
  // grants instant full trust on its own). This pulls each raw stat back
  // toward its roster-typical baseline by the shortfall — full credibility
  // leaves a stat untouched, low credibility pulls it most of the way to
  // baseline, rather than feeding an unproven outlier value through at full
  // strength.
  // Floored at 0.5 rather than running all the way to 0: low credibility
  // used to be able to replace a stat almost entirely with a generic
  // roster-average baseline, which silently treats "small/unproven sample"
  // as "assume this fighter is mediocre" — that's not the same claim. A
  // fighter who's actually dominant just hasn't had the chance to prove it
  // against ranked competition yet; their real numbers should still count
  // for something. The uncertainty in a thin sample is handled separately,
  // by widening the win-probability curve in simWinProbability (see
  // credibility's use there) rather than by crushing the point estimate
  // itself toward average.
  function simCredibilityDampen(value, baseline, credibility) {
    const effectiveCredibility = 0.5 + 0.5 * credibility;
    return baseline + (value - baseline) * effectiveCredibility;
  }

  // kd, tdLanded, and subAvg are the only three rate stats with no natural
  // ceiling: strAcc/strDef/tdAcc/tdDef/finRate are percentages (bounded
  // 0-100% by construction), but these three are raw event counts divided
  // by total fight time. That division is fine across a normal-length
  // sample, but when a fighter's total logged UFC cage time is tiny — a
  // couple of fights that both ended in the first minute — one real
  // takedown or knockdown extrapolates into an absurd "per 15 min" rate
  // (e.g. a single takedown landed inside a 30-second fight reads as ~18
  // takedowns/15min). That's an artifact of the denominator, not a real
  // pattern, and it was blowing up simPowerScore for fighters like
  // Abdulrakhman Yakhyaev (9-0, two UFC fights, both sub-minute finishes)
  // to the point of out-scoring a reigning champion.
  // Ceilings set well above any real UFC fighter's genuine sustained rate,
  // so this only ever clips an obvious small-sample artifact.
  const SIM_RATE_CEILING = { kd: 3.0, tdLanded: 6.0, subAvg: 3.0 };

  // Full trust (1) once a fighter has ~30 minutes of total logged UFC cage
  // time — roughly two full fights worth — since by then a high rate
  // reflects a real repeated pattern rather than one or two events landing
  // in an unusually short denominator.
  const SIM_RATE_RELIABILITY_FULL_SECONDS = 30 * 60;

  function simParseFightSeconds(timeStr) {
    if (!timeStr) return null;
    const m = String(timeStr).match(/^(\d+):(\d{2})$/);
    if (!m) return null;
    return parseInt(m[1], 10) * 60 + parseInt(m[2], 10);
  }

  // Total seconds of UFC cage time actually logged for a fighter — the real
  // denominator behind kd/tdLanded/subAvg. A finish's total time is
  // (round-1)*5min plus the clock shown at the stoppage; a decision goes
  // the full scheduled distance. Non-UFC fights aren't counted since these
  // rate stats are UFC-only (the ufc.com box-score convention they're
  // pulled from).
  function simUfcCageSeconds(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    const ROUND_LEN = 5 * 60;
    let total = 0;
    hist.forEach(f => {
      if (f.org !== 'UFC' || !f.result || f.result === '–' || f.method === 'Upcoming') return;
      const isDecision = String(f.method || '').toUpperCase().includes('DECISION');
      if (isDecision) {
        total += simNum(f.round, 3) * ROUND_LEN;
      } else {
        const completedRounds = Math.max(0, simNum(f.round, 1) - 1);
        const clock = simParseFightSeconds(f.time);
        total += completedRounds * ROUND_LEN + (clock != null ? clock : ROUND_LEN);
      }
    });
    return total;
  }

  function simRateTimeReliability(name) {
    return Math.min(1, simUfcCageSeconds(name) / SIM_RATE_RELIABILITY_FULL_SECONDS);
  }

  // Clamps a small-sample-inflated rate to a realistic ceiling, then lets
  // that clamp relax back out as a fighter accumulates real cage time: at
  // 0 reliability the value is fully clamped to the ceiling; at full
  // reliability the raw value passes through untouched — a fighter who has
  // genuinely proven a high rate over enough real fight time keeps it,
  // however high it is.
  function simCapSmallSampleRate(rawValue, ceiling, reliability) {
    const capped = Math.min(rawValue, ceiling);
    return capped + (rawValue - capped) * reliability;
  }

  function getSimProfile(name, rounds) {
    const s = (typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[name]) || {};
    const credibility = simRateCredibility(name);
    const timeReliability = simRateTimeReliability(name);
    const kdSane = simCapSmallSampleRate(simNum(s.kd, 0.3), SIM_RATE_CEILING.kd, timeReliability);
    const tdLandedSane = simCapSmallSampleRate(simNum(s.tdLanded, 1.0), SIM_RATE_CEILING.tdLanded, timeReliability);
    const subAvgSane = simCapSmallSampleRate(simNum(s.subAvg, 0.3), SIM_RATE_CEILING.subAvg, timeReliability);
    const slpm = simCredibilityDampen(simNum(s.slpm, 3.5), 3.5, credibility);
    const sapm = simCredibilityDampen(simNum(s.sapm, 3.5), 3.5, credibility);
    const tdLanded = simCredibilityDampen(tdLandedSane, 1.0, credibility);
    const tdAcc = simCredibilityDampen(simPct(s.tdAcc, 0.4), 0.4, credibility);
    // A win streak built mostly pre-UFC, against obscure regional
    // competition, isn't the same signal as a real UFC streak — same
    // root issue as the rate stats above, so it gets the same dampening
    // treatment, toward a neutral baseline of 0 rather than a per-stat
    // average (a streak of 0 is a normal, common starting point).
    const streak = simCredibilityDampen(simNum(s.streak, 0), 0, credibility);
    const kd = simCredibilityDampen(kdSane, 0.3, credibility);
    const finRate = simCredibilityDampen(simRelevantFinRate(name, simPct(s.finRate, 0.45)), 0.45, credibility);
    return {
      slpm,
      strAcc: simCredibilityDampen(simPct(s.strAcc, 0.45), 0.45, credibility),
      sapm,
      strDef: simCredibilityDampen(simPct(s.strDef, 0.55), 0.55, credibility),
      kd,
      tdLanded,
      tdAcc,
      tdDef: simCredibilityDampen(simPct(s.tdDef, 0.65), 0.65, credibility),
      subAvg: simCredibilityDampen(subAvgSane, 0.3, credibility),
      finRate,
      streak,
      scheduleMultiplier: simScheduleMultiplier(name),
      activityCredit: simActivityCredit(name),
      trajectory: simTrajectory(name),
      age: simAgeFactor(s.dob),
      layoff: simLayoffFactor(name),
      bigFight: simBigFightExperience(name),
      controlBoost: simControlTimeBoost(name, credibility),
      // Schedule-dampened: an unbeaten record is only as meaningful as the
      // competition it was built against. Unlike the rate stats, this bonus was
      // applied at full strength regardless of opposition, so a prospect padding
      // a perfect record on the regional scene (e.g. Michael Morales) earned the
      // same undefeated premium as one who ran the gauntlet of ranked contenders
      // (Topuria, Rakhmonov). Multiplying by credibility ties it to schedule
      // quality — an elite undefeated fighter (credibility ≈ 1) keeps essentially
      // the full bonus, a thin/regional record sheds most of it — and also curbs
      // its overlap with the win-streak/form term, which already rewards the same
      // unbeaten run and is itself credibility-dampened.
      undefeatedBoost: simUndefeatedBoost(name) * credibility,
      durabilityBoost: simDurabilityBoost(name),
      finishVulnerability: simFinishVulnerability(name),
      fiveRoundFactor: rounds === 5 ? simFiveRoundFactor(name) : 0
    };
  }

  // How tested a fighter's resume actually is, split by result. Each
  // completed fight against a CURRENTLY ranked opponent is weighted by how
  // highly they're ranked (a near-title-shot opponent counts for close to 3x
  // a fighter clinging to #15) and by recency (a test from the last year or
  // two counts close to double one from 6+ years back, though a deep
  // historical resume still keeps a floor of value rather than decaying to
  // zero). Wins and losses against that ranked competition are tallied
  // separately rather than lumped together — beating ranked opponents and
  // losing to them are not the same signal, and treating them as
  // interchangeable was hiding which of the two actually happened. Uses each
  // opponent's CURRENT roster rank as a proxy for "were they real
  // competition" — we don't have point-in-time historical rankings.
  //
  // Losses to ranked opponents are credited by HOW they happened rather than
  // flatly subtracted: a competitive decision loss to elite competition
  // means a fighter was genuinely tested and held up reasonably well — real,
  // positive signal, just less than a win would be — while a finish loss is
  // closer to "no information either way" (simFinishVulnerability already
  // separately penalizes a pattern of getting finished, so this doesn't need
  // to double-penalize that here). Critically, a loss credited this way can
  // never drag a fighter's schedule quality BELOW what a fighter who has
  // never faced anyone ranked at all gets — going the distance with the
  // champ twice should never score worse than having an entirely empty
  // resume.
  //
  // That empty-resume case is handled explicitly: previously, zero ranked
  // opponents and an evenly-split ranked record both produced the same
  // neutral net of 0, which let a long UFC tenure built entirely against
  // unranked competition pass through with no schedule discount at all. Once
  // a fighter has had a real opportunity to be tested (6+ UFC fights) and it
  // still never happened, that's treated as a real negative rather than
  // neutral. Gated on fight count so it doesn't punish fast-rising prospects
  // who simply haven't been matched up yet.
  function simScheduleQuality(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let winsWeighted = 0, testedLossCredit = 0, ufc = 0, ufcWins = 0, ufcLossWeighted = 0, rankedFaced = 0, rankedQuality = 0;
    const now = __now();
    hist.forEach(f => {
      if (!f.opponent || !f.result || f.method === 'Upcoming' || f.result === '–') return;
      if (f.org === 'UFC') {
        ufc++;
        // Tracked separately from the plain `ufc` count below for
        // simRateCredibility (see there for why): a long career padded
        // mostly with losses shouldn't buy the same "trust this fighter's
        // raw stats" credit as the same length career built on wins. Losses
        // still count for SOMETHING — going the distance still means real,
        // representative stats were generated that fight — just discounted,
        // and discounted harder for a quick finish loss (short fight,
        // thinner data, often a fighter being run over) than a competitive
        // decision loss.
        if (f.result === 'W') {
          ufcWins++;
        } else if (f.result === 'L') {
          const method = String(f.method || '').toUpperCase();
          const isFinish = method.includes('KO') || method.includes('TKO') || method.includes('SUB');
          const isCloseDecision = method.includes('SPLIT') || method.includes('MAJORITY');
          ufcLossWeighted += isFinish ? 0.25 : (isCloseDecision ? 0.85 : 0.6);
        }
      }
      if (f.result !== 'W' && f.result !== 'L') return;
      const tier = simRankTier(f.opponent);
      if (tier == null) return;
      rankedFaced++;
      const quality = Math.max(0.3, 1 - tier / 15);
      rankedQuality += quality;
      const d = new Date(f.date);
      const yearsAgo = isNaN(d) ? 5 : Math.max(0, (now - d.getTime()) / (1000 * 60 * 60 * 24 * 365.25));
      const recency = 0.4 + 0.6 * Math.max(0, 1 - Math.min(yearsAgo, 6) / 6);
      const contrib = quality * recency;
      if (f.result === 'W') {
        winsWeighted += contrib;
      } else {
        const method = String(f.method || '').toUpperCase();
        const isFinish = method.includes('KO') || method.includes('TKO') || method.includes('SUB');
        const isCloseDecision = method.includes('SPLIT') || method.includes('MAJORITY');
        testedLossCredit += contrib * (isFinish ? 0.1 : (isCloseDecision ? 0.7 : 0.5));
      }
    });
    let net = winsWeighted + testedLossCredit;
    const untested = ufc >= 6 && rankedFaced === 0;
    if (untested) net -= 1.5;
    const effectiveUfc = ufcWins + ufcLossWeighted;
    return { net, ufc, effectiveUfc, untested, rankedFaced, rankedQuality };
  }

  // How much to trust a fighter's raw per-fight rate stats at face value,
  // distinct from the win/loss-based schedule quality above. Facing a
  // ranked opponent is a costly, meaningful signal — at that point the
  // stats have been earned partly against real competition — but not
  // every ranked opponent is the same kind of evidence, and a single
  // fight shouldn't instantly launder an entire raw-stat profile when
  // the UFC sample backing it is still tiny (e.g. 2 total UFC fights,
  // one a decision win over a fighter just barely inside the rankings
  // [#14 of 15], with the rest of the career's gaudy numbers —
  // knockdowns, finish rate — built against obscure regional
  // competition). So the credibility boost is weighted by how good the
  // ranked opponent(s) actually were (the same tier-based quality used
  // for schedule quality above), not just a flat per-fight count — a
  // win over a top contender buys a lot more trust than a win over a
  // fighter who barely cracked the rankings. A fighter with a real UFC
  // tenure (many fights) or multiple quality ranked wins still reaches
  // full trust quickly; it's only the extreme small-sample, low-quality
  // case that now stays partially dampened. 14 "fight-equivalents" is
  // treated as enough of a sample for full trust.
  function simRateCredibility(name) {
    // Uses effectiveUfc (win-weighted UFC fight count, see simScheduleQuality)
    // rather than the raw fight count: a career padded mostly with losses
    // shouldn't earn the same "trust these raw stats" credit as the same
    // length career built on wins. A losing fighter can still rack up UFC
    // tenure indefinitely without ever proving their per-fight rate stats
    // are representative of real success.
    const { effectiveUfc, rankedQuality } = simScheduleQuality(name);
    return Math.min(1, (effectiveUfc + rankedQuality * 5) / 14);
  }

  // Schedule quality used to be tacked onto the power score as a flat side
  // bonus at the end, which meant a gaudy striking/grappling/finishing
  // profile built mostly against soft, unranked competition scored exactly
  // as trustworthy as the same numbers earned against a murderers' row —
  // the bonus just stacked on top rather than actually questioning the
  // stats themselves. This instead returns a multiplier applied directly to
  // the production-stat terms in simPowerScore (striking, grappling,
  // finishing): a thin/soft schedule discounts those numbers, a real
  // murderers'-row resume inflates them, since the per-fight box-score data
  // here has no per-opponent breakdown to recompute the underlying stats
  // from directly. tanh keeps the swing bounded to roughly +/-15% either
  // way for ordinary cases, so schedule quality stays a real but secondary
  // adjustment rather than overriding what a fighter's stats actually say.
  //
  // The "untested" case — 6+ UFC fights, literally zero of them against a
  // ranked opponent — gets a wider +/-35% swing instead. A gaudy
  // striking/finishing profile built entirely against opposition that's
  // never been good enough to rank is exactly the scenario where the
  // underlying rate stats themselves are least trustworthy (small, one-
  // sided samples inflate per-fight rates like knockdowns/finish rate in a
  // way a deep, mixed-quality career doesn't), so it warrants more than the
  // ordinary secondary nudge.
  function simScheduleMultiplier(name) {
    const { net, untested } = simScheduleQuality(name);
    const cap = untested ? 0.35 : 0.15;
    return 1 + cap * Math.tanh(net / 2.5);
  }

  // Separate, smaller credit for sheer UFC-level fight count/experience —
  // distinct from schedule QUALITY above, capped so a 50-fight veteran's
  // volume alone doesn't swamp everything else.
  function simActivityCredit(name) {
    const { ufc } = simScheduleQuality(name);
    return Math.min(ufc, 20) * 0.04;
  }

  // Recent-fight trajectory, distinct from the plain win-streak counter
  // below: a streak resets to 0 on ANY non-win, with no way to tell "lost a
  // tight decision" from "just got starched in the first round" apart, and
  // gives no extra credit for what a current streak was actually built on.
  // Looks at the last FIVE completed fights (widened from 2 — a 2-fight
  // window could miss a real pattern sitting just one fight further back,
  // e.g. Krylov bouncing back with one win over an unranked opponent right
  // after getting knocked out twice in a row by Reyes and Guskov; with only
  // the last 2 fights visible, that second KO loss falls outside the window
  // entirely and the pattern disappears). Weights decay fast (most recent
  // fight still dominates) but a real short-to-medium-term trend across the
  // last year or two now actually shows up. Layers a bonus for a recent win
  // (bigger if it was a finish, bigger still if the opponent is currently
  // ranked) or a penalty for a recent loss (notably bigger if it was by
  // finish — a fresh brutal stoppage loss is a real, distinct red flag a
  // reset-to-zero streak can't capture). On top of that, 2+ finish losses
  // within this 5-fight window get an extra penalty beyond what each one
  // already contributes individually — that's a categorically different,
  // more current signal (a real decline, a chin or gas tank going) than the
  // same two finish losses spread thinly across a long career.
  function simTrajectory(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    const completed = f => f.result && f.result !== '–' && f.method !== 'Upcoming' && f.date;
    // "Recent form" should mean recent UFC-level form. Without this,
    // a fighter a couple fights into their UFC run has most or all of this
    // 5-fight window filled with regional bouts against weaker competition
    // — the same front-loading problem already corrected for finish rate
    // and finish vulnerability elsewhere, just left unaddressed here. Falls
    // back to full history only when there are literally zero UFC fights
    // to draw from (a fighter making their UFC debut still needs SOME
    // recent-form signal rather than none at all).
    const ufcHist = hist.filter(f => completed(f) && f.org === 'UFC');
    const pool = ufcHist.length > 0 ? ufcHist : hist.filter(completed);
    const recent = pool.slice(0, 5);
    const weights = [1.0, 0.5, 0.3, 0.18, 0.1];
    let score = 0, recentFinishLosses = 0;
    recent.forEach((f, i) => {
      const weight = weights[i] != null ? weights[i] : 0.1;
      const method = String(f.method || '').toUpperCase();
      const isFinish = method.includes('KO') || method.includes('TKO') || method.includes('SUB');
      const tier = simRankTier(f.opponent);
      // Same tier-based quality scale used for schedule quality and
      // credibility — a win over a fighter just barely inside the rankings
      // shouldn't get the same flat bonus as a win over a top contender.
      const oppQuality = tier != null ? Math.max(0.3, 1 - tier / 15) : 0;
      if (f.result === 'W') {
        let v = 0.25;
        if (isFinish) v += 0.2;
        if (tier != null) v += 0.25 * oppQuality;
        score += v * weight;
      } else if (f.result === 'L') {
        // Scale loss penalty by opponent caliber — losing to the champ
        // barely moves trajectory; losing to an unranked fighter is the
        // full hit. oppQuality already computed above (0 for unranked,
        // 1.0 for champ). disgrace floor of 0.15 so even an elite-level
        // loss leaves a small mark (you still got beaten). Finish penalty
        // scales the same way — getting finished by Pereira is a very
        // different signal than getting starched by a nobody.
        const disgrace = tier != null ? Math.max(0.15, 1 - oppQuality) : 1.0;
        let v = -0.25 * disgrace;
        if (isFinish) { v -= 0.35 * disgrace; recentFinishLosses++; }
        score += v * weight;
      }
    });
    if (recentFinishLosses >= 2) score -= 0.3 * (recentFinishLosses - 1);
    // The disgrace floor (0.15) already softens individual elite losses —
    // losing to the champ barely dents your score by design. But when the
    // LAST two fights are both losses, the floor effect compounds: a fighter
    // who lost to #1 and #2 back-to-back emerges with near-zero or even
    // positive trajectory despite being on a skid. Two consecutive losses
    // are a real form signal regardless of opponent quality, so add a flat
    // penalty here that the per-fight disgrace math can't absorb away.
    const lastTwoLosses = pool.slice(0, 2).filter(f => f.result === 'L').length;
    if (lastTwoLosses >= 2) score -= 0.3;
    return simSoftCap(score, 1.5);
  }

  // Past 36, fighters reliably start losing a step physically — but the
  // dropoff is small right at 36 and compounds gradually rather than as a
  // cliff, so the per-year penalty itself grows a little each year rather
  // than staying flat. Nothing happens at all at 36 or younger.
  function simAgeFactor(dob) {
    if (!dob) return 0;
    const age = calcAge(dob);
    // Onset lowered 36 → 32, curve steepened (×1.5) and cap raised 1.5 → 2.0.
    // The point-in-time backtest (scripts/sim-backtest/) found the age penalty was
    // by far the most under-tuned term: starting it in the early 30s rather than at
    // 36, and letting it bite harder, was the single biggest out-of-sample gain of
    // the whole tuning effort (test log loss 0.6631 → 0.6554, accuracy 60.9 → 62.2%).
    // Both the training and held-out sets minimized around an onset of 30-32, which
    // matches sports science (athletic peak ~27-30, measurable decline from the early
    // 30s) — the old age-36 threshold was crediting fading veterans with prime ability
    // their results no longer supported. "Moderate" curve: prime late-20s untouched,
    // ~0.8 pts off by 35, approaching the 2.0 cap in the 40s.
    if (age <= 32) return 0;
    const yearsPast = age - 32;
    const raw = ((yearsPast * 0.12) + (yearsPast * yearsPast * 0.02)) * 1.5;
    return -simSoftCap(raw, 2.0);
  }

  // Most recent completed fight date (skips scheduled/upcoming bookings),
  // used for the ring-rust factor below.
  function simLastFightDate(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let latest = null;
    hist.forEach(f => {
      if (!f.date || !f.result || f.result === '–' || f.method === 'Upcoming') return;
      const d = new Date(f.date);
      if (!isNaN(d) && (!latest || d > latest)) latest = d;
    });
    return latest;
  }

  // Long layoffs (injury, inactivity, contract limbo) are a real and
  // well-known predictor of underperformance — rust, lost timing, missed
  // training camps. No bonus for fighting often (avoids rewarding sheer
  // activity), just a small, growing penalty once a layoff passes ~14 months.
  function simLayoffFactor(name) {
    const last = simLastFightDate(name);
    if (!last) return 0;
    const months = (__now() - last.getTime()) / (1000 * 60 * 60 * 24 * 30.4);
    if (!(months > 14)) return 0;
    const raw = (months - 14) * 0.05;
    return -simSoftCap(raw, 1.2);
  }

  // Credit for having actually been in deep, high-pressure fights (full
  // five-round wars — title fights and ranked main events both land here).
  // That's a different, more specific signal than general strength of
  // schedule: it's about composure and cardio when a fight goes long, not
  // just who the opponent was.
  function simBigFightExperience(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let count = 0;
    hist.forEach(f => {
      if (!f.result || f.result === '–' || f.method === 'Upcoming') return;
      // Restricted to UFC bouts — a 5-round fight in a regional promotion
      // (rare, but it happens) isn't the same big-stage/championship-rounds
      // experience this signal is meant to capture.
      if (f.org !== 'UFC') return;
      if (f.round === 5) count++;
    });
    return Math.min(1, count * 0.18);
  }

  // Small top-up specifically for a zero in the loss column, distinct from
  // the win-streak ("form") term above — a fighter with one early-career
  // loss who's won their last 12 already gets full streak credit there,
  // but "has never lost, period" is its own signal worth a little extra.
  // Below ~9 wins the bonus stays modest (could still just mean "hasn't
  // faced real competition yet"); past 9 wins a clean record starts
  // looking like a real accomplishment, so it grows a bit faster from
  // there. Both legs are soft-capped so a 20-0 prospect doesn't run away
  // with it.
  function simUndefeatedBoost(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let wins = 0, losses = 0;
    hist.forEach(f => {
      if (!f.result || f.result === '–' || f.method === 'Upcoming') return;
      if (f.result === 'W') wins++;
      else if (f.result === 'L') losses++;
    });
    if (losses > 0 || wins === 0) return 0;
    const belowNine = simSoftCap(Math.min(wins, 9), 9) * 0.06;
    const pastNine = simSoftCap(Math.max(0, wins - 9), 8) * 0.14;
    return belowNine + pastNine;
  }

  // Shared tally for the finish-rate factors below: how many wins were
  // finishes (KO/TKO/Submission, as opposed to decision) and, among losses,
  // how many were finishes vs. decisions. `ufcOnly` restricts the pass to
  // UFC-organization fights only — see simFinishStatsRelevant below for why.
  function simFinishStats(name, ufcOnly) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let wins = 0, winFinishes = 0, losses = 0, lossFinishes = 0, lossDecisions = 0;
    hist.forEach(f => {
      if (!f.result || f.result === '–' || f.method === 'Upcoming') return;
      if (ufcOnly && f.org !== 'UFC') return;
      const method = String(f.method || '').trim();
      // "Technical Submission (...)" doesn't start with "Submission" so the
      // old pattern missed it entirely — not a finish, not a decision,
      // silently excluded from both buckets. 149+ fights across the roster
      // use this exact method string (a ref-stoppage submission, distinct
      // from "Technical Decision," which IS a decision and was already
      // matched fine by the isDecision check below).
      const isFinish = /^(?:KO|TKO|Submission|Technical Submission)\b/i.test(method);
      const isDecision = /Decision/i.test(method);
      if (f.result === 'W') {
        wins++;
        if (isFinish) winFinishes++;
      } else if (f.result === 'L') {
        losses++;
        if (isFinish) lossFinishes++;
        else if (isDecision) lossDecisions++;
      }
    });
    return { wins, winFinishes, losses, lossFinishes, lossDecisions };
  }

  // Many fighters' early careers were built on regional shows against
  // significantly weaker competition than the UFC roster — a prospect who
  // finished everyone in a regional promotion, then settled into a more
  // competitive decision-heavy run once they reached the UFC, shouldn't get
  // full credit for those front-loaded regional finishes when measuring
  // CURRENT finishing/durability threat. Prefers a UFC-only tally when
  // there's enough of a UFC sample to trust (4+ wins or 3+ losses, matching
  // the minimums the boosts below already require), falling back to the
  // full career history otherwise so a fighter with only a couple of UFC
  // fights isn't left with no signal at all.
  function simFinishStatsRelevant(name) {
    const ufc = simFinishStats(name, true);
    if (ufc.wins >= 4 || ufc.losses >= 3) return ufc;
    return simFinishStats(name, false);
  }

  // Recency-weighted loss tally, mirroring how simRelevantFinRate already
  // weights the WIN side — a finish loss from the last year or two counts
  // close to double one from 6+ years back (floored, not decayed to zero),
  // rather than a flat career-long average. Without this, two finish losses
  // from early in a decade-long career read identically to two finish
  // losses suffered in the last 14 months, which is backwards for
  // forecasting CURRENT fragility (e.g. Krylov was finished twice — by
  // Dominick Reyes and Bogdan Guskov — within roughly 14 months of each
  // other, both well inside this window). Uses the same UFC-only-vs-full-
  // career sample decision as simFinishStatsRelevant, so the recency-
  // weighted rate and the raw counts used for sample-size gating always
  // come from the same pool of fights.
  function simLossFinishProfile(name) {
    const ufc = simFinishStats(name, true);
    const useUfcOnly = ufc.wins >= 4 || ufc.losses >= 3;
    const raw = useUfcOnly ? ufc : simFinishStats(name, false);
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    const now = __now();
    let totalWeight = 0, finishWeight = 0, decisionWeight = 0;
    hist.forEach(f => {
      if (f.result !== 'L' || f.method === 'Upcoming' || !f.date) return;
      if (useUfcOnly && f.org !== 'UFC') return;
      const d = new Date(f.date);
      const yearsAgo = isNaN(d) ? 3 : Math.max(0, (now - d.getTime()) / (1000 * 60 * 60 * 24 * 365.25));
      const weight = 0.5 + 0.5 * Math.max(0, 1 - Math.min(yearsAgo, 6) / 6);
      const method = String(f.method || '').trim();
      const isFinish = /^(?:KO|TKO|Submission|Technical Submission)\b/i.test(method);
      const isDecision = /Decision/i.test(method);
      totalWeight += weight;
      if (isFinish) finishWeight += weight;
      else if (isDecision) decisionWeight += weight;
    });
    return {
      losses: raw.losses,
      lossFinishes: raw.lossFinishes,
      weightedLossFinishRate: totalWeight > 0 ? finishWeight / totalWeight : 0,
      weightedLossDecisionRate: totalWeight > 0 ? decisionWeight / totalWeight : 0,
      weightedFinishLossCount: finishWeight
    };
  }

  // "Granite chin" signal: among a fighter's losses, what share went the
  // distance rather than ending early. A fighter who's lost fights but has
  // rarely or never been finished is notoriously durable — a real, distinct
  // trait from raw strDef/output numbers. Requires at least 3 losses so one
  // decision loss doesn't read as an iron chin. Rate is recency-weighted
  // (see simLossFinishProfile) so a durable stretch right now counts more
  // than one from years ago.
  function simDurabilityBoost(name) {
    const stats = simLossFinishProfile(name);
    if (stats.losses < 3) return 0;
    const pct = stats.weightedLossDecisionRate;
    if (pct <= 0.75) return 0;
    return simSoftCap((pct - 0.75) * 4, 1) * 0.4;
  }

  // Inverse signal: a fighter who's finished often when they lose (chin or
  // gas-tank questions either way) takes a real hit. Used to be pure rate
  // (finishes / losses past a 75% threshold), which had a real blind spot:
  // a fighter stopped in all 3 of a thin 3-loss sample scored as MORE
  // vulnerable than one stopped 9 times in 11 losses (100% vs ~82%), even
  // though 9 finish losses is a far more substantial, proven pattern than
  // 3. Driven purely by the recency-weighted COUNT of finish losses (see
  // simLossFinishProfile — 3-4 is a modest flag, 6+ a real pattern, 9+
  // serious, soft-capped so it doesn't grow unbounded past that, and a
  // finish loss from years ago counts for less than a fresh one). Same
  // 3-loss minimum sample as the durability bonus above. No rate floor —
  // 3+ finish losses is a real pattern worth flagging on its own, even for
  // a long-career fighter where it's a small share of a much larger total
  // loss count; diluting it by share would let volume quietly launder away
  // a proven finish-loss pattern.
  //
  // Returns a PERCENTAGE (negative fraction), not a flat point value — see
  // where this is consumed in simPowerScore. A flat point subtraction reads
  // as negligible against a "glass cannon" fighter whose heavy-output
  // stats have built a big score (Krylov: -0.6 against a 7.4 total was
  // background noise), while crushing a fighter who had little score to
  // begin with (Derrick Lewis: the old flat penalty alone was 46% of his
  // entire score). Scaling by a percentage of the fighter's own subtotal
  // fixes both ends at once: a fighter whose exciting offense built a big
  // score actually loses a real chunk of it for also having a proven
  // finish-loss pattern, while a fighter with little score isn't driven
  // disproportionately negative by the same flat number.
  function simFinishVulnerability(name) {
    const stats = simLossFinishProfile(name);
    if (stats.losses < 3 || stats.lossFinishes < 3) return 0;
    return -simSoftCap(Math.max(0, stats.weightedFinishLossCount - 2) * 0.07, 0.30);
  }

  // 5-round-specific modifier — only added when the simulator is run in
  // 5-round mode (see runFightSimulator / simSetRounds). Deliberately kept
  // small and separate from the always-on power-score terms above rather
  // than folded into them, so picking "3 Rounds" still scores fights
  // exactly as it always has.
  //
  // Three pieces:
  //   1. Deep-rounds experience. FIGHT_HISTORY only records the round a
  //      fight actually ended in, not how many rounds it was SCHEDULED
  //      for — but round 4 or 5 can only happen in a fight that was
  //      scheduled for 5, so it doubles as a reliable proxy without
  //      needing a separate field. A win out there earns more credit than
  //      a loss, but a loss still counts for a little — surviving into
  //      deep water at all is real evidence a fighter doesn't fall apart
  //      once a fight runs long, separate from whether they won it.
  //   2. Durability bonus. Reuses the existing "granite chin" signal
  //      (simDurabilityBoost) at a fraction of its normal weight — that
  //      signal already lives in the base score year-round, this just
  //      adds a little extra credit specifically for the 25-minute case.
  //   3. Finishability penalty. A raw count of finish losses (3+) is a
  //      real cardio/durability red flag once a fight can go the full
  //      distance — scales gently with how many, soft-capped so a long,
  //      finish-heavy career doesn't swing this wildly.
  // Recency weight for a single dated fight, mirroring simLossFinishProfile's
  // decay exactly (floor of 0.5 at 6+ years, never zero — a 5-round fight
  // from 8 years ago is weaker evidence of CURRENT cardio/conditioning than
  // one from last year, but it's not nothing; a fighter doesn't un-learn how
  // to swim 25 minutes). Unknown/unparseable dates get a neutral 0.75
  // (between the 0.5 floor and the 1.0 ceiling) rather than full or zero
  // weight, so a handful of missing dates can't quietly dominate or vanish.
  function simRecencyWeight(dateStr) {
    const d = new Date(dateStr);
    if (isNaN(d)) return 0.75;
    const yearsAgo = Math.max(0, (__now() - d.getTime()) / (1000 * 60 * 60 * 24 * 365.25));
    return 0.5 + 0.5 * Math.max(0, 1 - Math.min(yearsAgo, 6) / 6);
  }

  function simFiveRoundFactor(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let deepRounds = 0;
    hist.forEach(f => {
      if (!f.result || f.method === 'Upcoming' || !f.round || f.round < 4) return;
      const w = simRecencyWeight(f.date);
      if (f.result === 'W') deepRounds += 0.18 * w;
      else if (f.result === 'L') deepRounds += 0.06 * w;
    });
    const experienceFactor = simSoftCap(deepRounds, 0.6);
    const durabilityFactor = simDurabilityBoost(name) * 0.35;
    // Finishability penalty reuses simLossFinishProfile's already
    // recency-weighted finish-loss count instead of a flat tally, so a
    // finish loss from years ago counts for less than a fresh one — same
    // floor-of-0.5, 6-year decay used everywhere else in this file. Sample
    // gate (3+ losses, 3+ of them finishes) matches simFinishVulnerability
    // above, so the two penalties never disagree about whether a fighter
    // has a real enough sample to judge. Scaled up (roughly 2x base/slope/
    // cap) relative to the always-on version above — cardio and durability
    // questions get sharper, not lighter, once a fight can run the full 25
    // minutes, and this stacks with the always-on penalty (which already
    // applies in every fight, 3 or 5 round) rather than replacing it, so a
    // genuinely finish-prone fighter takes a real double hit in 5-round
    // mode specifically.
    const lossProfile = simLossFinishProfile(name);
    let finishPenalty = 0;
    if (lossProfile.losses >= 3 && lossProfile.lossFinishes >= 3) {
      const wCount = lossProfile.weightedFinishLossCount;
      finishPenalty = -simSoftCap(0.12 + (wCount - 3) * 0.06, 0.5);
    }
    const decisionFactor = simDecisionGrinderBoost(name);
    // 2x multiplier applied after the soft caps above (not folded into
    // their inputs), so it scales the whole signal's range uniformly
    // rather than changing the shape of the diminishing-returns curve.
    return (experienceFactor + durabilityFactor + finishPenalty + decisionFactor) * 2;
  }

  // Standalone "grinder" signal, separate from deep-rounds experience above.
  // That term only fires once a fighter has actually BEEN in round 4/5 — it
  // says nothing about a fighter stepping into their first 5-round fight who
  // has nonetheless built a career on out-pacing people over a full fight and
  // winning the decision. Two conditions, both required:
  //   1. Decisions have to make up a real share of their career (35%+ of all
  //      decided fights, with a minimum raw sample) — one decision win in an
  //      otherwise finish-heavy career isn't a "grinder," it's a data point.
  //   2. They have to be clearly WINNING those decisions (65%+ of their
  //      decisions, recency-weighted), not just going the distance. A
  //      fighter who's 5-5 by decision has shown they can hang 15-25 minutes,
  //      but that's not an edge — it's a coin flip, exactly the case the user
  //      flagged as not a real signal.
  // Even past that bar, a meaningful raw count of decision LOSSES still drags
  // the bonus down (lossDrag below) — a fighter who barely cleared 65% on a
  // thin sample shouldn't score the same as one who's dominantly won
  // decisions with few losses to show otherwise.
  //
  // Scoped to fights at round <= 3 only (i.e. excludes any fight we know for
  // certain was scheduled for 5 — round 4/5 can only happen in a 5-round
  // fight, same proxy used by the experience term above). Two reasons to cut
  // it off there rather than scanning the whole career:
  //   1. Once a fighter is fighting 5-round fights regularly, it's almost
  //      always against tougher, more championship-caliber competition. A
  //      decision LOSS at that level isn't evidence they've lost their
  //      grinding edge — it's just a harder fight — so it shouldn't be able
  //      to drag this term down at all.
  //   2. Round 4/5 decision WINS are already credited by the experience
  //      factor above; counting them here too would double-pay the same
  //      evidence. The edge a fighter built up grinding out 3-round
  //      decisions should carry forward into their 5-round profile on its
  //      own terms, independent of how their actual 5-round fights go.
  function simDecisionGrinderBoost(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let winsRaw = 0, lossesRaw = 0, decWinsRaw = 0, decLossesRaw = 0;
    let decWinsW = 0, decLossesW = 0;
    hist.forEach(f => {
      if (!f.result || f.result === '–' || f.method === 'Upcoming') return;
      if (f.round && f.round >= 4) return;
      const w = simRecencyWeight(f.date);
      const isDecision = /Decision/i.test(String(f.method || '').trim());
      if (f.result === 'W') {
        winsRaw++;
        if (isDecision) { decWinsRaw++; decWinsW += w; }
      } else if (f.result === 'L') {
        lossesRaw++;
        if (isDecision) { decLossesRaw++; decLossesW += w; }
      }
    });
    const totalRaw = winsRaw + lossesRaw;
    const decTotalRaw = decWinsRaw + decLossesRaw;
    const decTotalW = decWinsW + decLossesW;
    if (totalRaw < 5 || decTotalRaw < 3 || decTotalW <= 0) return 0;
    if (decTotalRaw / totalRaw < 0.35) return 0;
    const winRate = decWinsW / decTotalW;
    if (winRate < 0.65) return 0;
    const rateBonus = (winRate - 0.65) * 0.6;
    const volumeBonus = simSoftCap(decWinsW, 6) * 0.02;
    const lossDrag = simSoftCap(decLossesRaw, 5) * 0.05;
    return simSoftCap(Math.max(0, rateBonus + volumeBonus - lossDrag), 0.3);
  }

  // "Boom or bust" signal: a fighter who finishes opponents often AND gets
  // finished often themselves is inherently less predictable than their raw
  // power-score gap suggests — a violent-but-fragile finisher can blow out
  // a methodical, low-variance opponent just as easily as get blown out by
  // them, in a way a stats-only model isn't well-equipped to call. Uses the
  // LOWER of the two rates (offense, defense) deliberately: both have to be
  // genuinely elevated for "boom or bust" to apply, since a fighter who's
  // only dangerous in one direction isn't actually unpredictable, just good
  // or bad. Same 4-win/3-loss sample minimum used elsewhere for finish-rate
  // signals, so a thin sample doesn't get flagged as volatile on noise.
  function simVolatility(name) {
    const { wins, winFinishes, losses, lossFinishes } = simFinishStatsRelevant(name);
    if (wins < 4 || losses < 3) return 0;
    const finishOffense = winFinishes / wins;
    const finishDefense = lossFinishes / losses;
    return Math.min(finishOffense, finishDefense);
  }

  // UFC's official takedown stats (tdLanded/tdAcc) only count takedown
  // attempts that land — they say nothing about how long a fighter then
  // controls top position, passes guard, or grinds out a round once the
  // takedown is in. A fighter who scores one takedown and rides out four
  // minutes of a five-minute round looks identical in the raw stat to one
  // who got up immediately. That's a real blind spot for control-heavy
  // grapplers, who can look unremarkable on paper while being functionally
  // dominant. There's no actual control-time stat in this dataset to pull
  // from, so this is a proxy: a fighter who clearly operates as a
  // high-volume, high-accuracy takedown threat (3+ landed/15min at 40%+
  // accuracy) while their own striking numbers are quiet (under 3.5
  // landed/absorbed per minute — i.e. fights aren't being won in exchanges)
  // is very likely winning rounds through control time the raw stats don't
  // show. That inference is only trusted when there's outside confirmation
  // it's working for them — a current ranking or a 3+ win streak — so it
  // doesn't reward a grappler who's merely active but actually losing.
  // Real net control time — the fighter's control seconds minus their opponents',
  // per 15 min of fight time — computed from the per-fight box scores already
  // loaded for the box-score modal (window.FIGHT_STATS). Box scores don't carry a
  // duration, so each bout's length comes from FIGHT_HISTORY (round + time),
  // matched by date+opponent, exactly like simUfcCageSeconds. UFC bouts only.
  // Returns null when there's no usable box-scored bout (so the caller falls back
  // to no control adjustment). This replaces an earlier ESTIMATE that merely
  // inferred control from "low striking + high takedown volume"; we now have the
  // actual numbers.
  function simControlNet(name) {
    const box = (typeof window !== 'undefined' && window.FIGHT_STATS && window.FIGHT_STATS[name]) || null;
    if (!box || !box.length) return null;
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    const ROUND_LEN = 5 * 60;
    const durByKey = {};
    hist.forEach(f => {
      if (String(f.org || '').toUpperCase() !== 'UFC' || !f.result || f.result === '–' || f.method === 'Upcoming') return;
      const isDecision = String(f.method || '').toUpperCase().includes('DECISION');
      let sec;
      if (isDecision) sec = simNum(f.round, 3) * ROUND_LEN;
      else { const clk = simParseFightSeconds(f.time); sec = Math.max(0, simNum(f.round, 1) - 1) * ROUND_LEN + (clk != null ? clk : ROUND_LEN); }
      durByKey[f.date + '||' + f.opponent] = sec;
    });
    let self = 0, opp = 0, total = 0, n = 0;
    box.forEach(bt => {
      const dur = durByKey[bt.date + '||' + bt.opponent];
      if (dur == null) return;
      self += simParseFightSeconds((bt.f || {}).ctrl) || 0;
      opp += simParseFightSeconds((bt.o || {}).ctrl) || 0;
      total += dur; n++;
    });
    if (!n || !total) return null;
    return ((self - opp) / 60) / (total / 60) * 15;   // net control MINUTES per 15 min
  }

  // Control-time bonus, driven by the real net-control number above. UFC judging
  // rewards top control heavily, and a fighter who controls far more than they're
  // controlled is winning rounds in a way the raw takedown counts don't fully
  // capture. Credibility-dampened (a thin or soft-schedule sample is pulled toward
  // neutral, same treatment as the other rate stats) and soft-capped so a single
  // long-control fight can't dominate. Weight 0.4 / cap 3.5 were fit empirically
  // against a point-in-time backtest of 4,518 fights (scripts/sim-backtest/):
  // swapping the old inert proxy for this improved out-of-sample log loss
  // 0.6664 → 0.6625 and Brier 0.2370 → 0.2351, with k held at 5.4.
  function simControlTimeBoost(name, credibility) {
    const net = simControlNet(name);
    if (net == null) return 0;
    const dampened = net * (0.5 + 0.5 * credibility);
    return 0.4 * simSoftCap(dampened, 3.5);
  }

  // Reach and stance are tracked per fighter but previously never touched
  // the score. A real reach edge is a modest but genuine advantage at
  // range; orthodox fighters see far fewer southpaw/switch opponents than
  // vice versa, giving the less common stance a small unfamiliarity edge.
  // Both are capped small — neither should outweigh the underlying stats.
  function simReachInches(name) {
    const s = (typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[name]) || {};
    if (!s.reach) return null;
    const n = parseFloat(String(s.reach).replace('"', ''));
    return isNaN(n) ? null : n;
  }

  function simStance(name) {
    const s = (typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[name]) || {};
    return s.stance ? String(s.stance).trim() : null;
  }

  function simStyleMatchupDelta(nameA, nameB, profileA, profileB) {
    let delta = 0;
    const ra = simReachInches(nameA), rb = simReachInches(nameB);
    if (ra != null && rb != null) {
      delta += simSoftCap((ra - rb) * 0.04, 0.3);
    }
    const isSouthpawish = s => s === 'Southpaw' || s === 'Switch';
    const sta = simStance(nameA), stb = simStance(nameB);
    if (sta && stb) {
      if (isSouthpawish(sta) && !isSouthpawish(stb)) delta += 0.15;
      else if (isSouthpawish(stb) && !isSouthpawish(sta)) delta -= 0.15;
    }
    // Grappling matchup: use credibility-dampened stats from profile when
    // available (profileA/B passed from simWinProbability, which already
    // computed them via getSimProfile — same dampening that applies to the
    // power score). Falls back to raw FIGHTER_STATS for any direct call that
    // doesn't supply profiles. This fixes the previous inconsistency where
    // a prospect's padded regional grappling stats could earn a big style-
    // matchup edge here that didn't match the discounting already applied to
    // their power score terms.
    const rawA = (typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[nameA]) || {};
    const rawB = (typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[nameB]) || {};
    const tdLandedA = profileA ? profileA.tdLanded : simNum(rawA.tdLanded, 1.0);
    const tdAccA    = profileA ? profileA.tdAcc    : simPct(rawA.tdAcc, 0.4);
    const subAvgA   = profileA ? profileA.subAvg   : simNum(rawA.subAvg, 0.3);
    const tdDefA    = profileA ? profileA.tdDef    : simPct(rawA.tdDef, 0.65);
    const tdLandedB = profileB ? profileB.tdLanded : simNum(rawB.tdLanded, 1.0);
    const tdAccB    = profileB ? profileB.tdAcc    : simPct(rawB.tdAcc, 0.4);
    const subAvgB   = profileB ? profileB.subAvg   : simNum(rawB.subAvg, 0.3);
    const tdDefB    = profileB ? profileB.tdDef    : simPct(rawB.tdDef, 0.65);
    const threatA = tdLandedA * tdAccA + subAvgA * 0.5;
    const threatB = tdLandedB * tdAccB + subAvgB * 0.5;
    const grappleEdge = (threatA * (0.65 - tdDefB)) - (threatB * (0.65 - tdDefA));
    // This is the matchup-aware grappling term: each fighter's takedown/sub threat
    // is scaled by (0.65 − OPPONENT takedown defense), so a grappler is rewarded
    // against a leaky-TDD opponent and penalised against an elite-TDD one. Weight
    // raised 1.6 → 2.5: the point-in-time backtest (scripts/sim-backtest/) showed
    // this term was slightly under-weighted — both train and out-of-sample log loss
    // improved and then plateaued as it rose toward ~2.5-3.0. The ±1.2 soft cap
    // bounds it regardless of weight, so a wide TDD gap can't run away. (A separate,
    // control-time-specific matchup adjustment was also tested here and REJECTED —
    // it gave no out-of-sample benefit, being redundant with this term.)
    delta += simSoftCap(grappleEdge * 2.5, 1.2);
    return delta;
  }

  // Composite "power score": striking output net of damage absorbed,
  // grappling/finishing threat, and a small recent-form (streak) bonus.
  // Knockdown rate (kd) has no natural ceiling like the other per-fight
  // stats, so a fighter with a handful of violent finishes (small UFC
  // sample, e.g. 3+ kd/15min) can post a wildly outsized value relative to
  // the rest of the roster. Soft-cap it (tanh) so it keeps rewarding real
  // power while no longer letting one outlier stat single-handedly swing
  // the whole score — values well under the cap (the vast majority of
  // fighters) are barely touched.
  function simSoftCap(x, cap) {
    return cap * Math.tanh(x / cap);
  }

  function simPowerScore(p) {
    // Striking output and damage absorbed are each soft-capped (diminishing
    // returns on raw volume) rather than entering linearly. The old linear form
    // over-weighted sheer volume: calibrating against the stored closing lines,
    // low-volume fighters — technical strikers like Edwards, high craft but
    // modest output — came out systematically underrated (~4 pts), while
    // high-volume fighters were slightly over-rated. Capping both sides at ~2.2
    // closes most of that gap and improves overall market agreement, without
    // flattening real striking edges: the marginal value of the 7th significant
    // strike per minute over the 6th is simply less than the 2nd over the 1st.
    const strikingNet = simSoftCap(p.slpm * p.strAcc, 2.2) - simSoftCap(p.sapm * (1 - p.strDef), 2.2);
    // Takedown defense was tracked per fighter but never actually touched
    // the score — strikingNet above already nets a fighter's own defense
    // against damage absorbed, but grappling below was pure offense with no
    // defensive counterpart at all. Center on 0.65, the same default used
    // elsewhere when tdDef is missing, so an elite defender (90-100%) earns
    // a real bonus and a poor one (30-40%) takes a real hit.
    const tdDefBonus = (p.tdDef - 0.65) * 1.5;
    // Grappling/finishing weights dialed back from 1.2/2.2/4/2.5: these
    // terms, stacked together, were repeatedly driving lopsided model
    // outputs (89-93% favorites) in fights the actual betting market saw as
    // much closer or even favoring the other fighter (Whittaker/Krylov,
    // Royval/Kavanagh, Saint Denis/Pimblett, Krylov/Ankalaev) — a heavy
    // grappler/finisher's subAvg, takedown volume, and finish rate were
    // compounding across multiple terms (grappling, finishing, and
    // formerly finisherBoost) for what's ultimately one underlying trait.
    // finisherBoost has been removed outright as redundant with finRate.
    const grappling = (p.tdLanded * p.tdAcc * 1.0) + (p.subAvg * 1.6);
    const finishing = (p.finRate * 3) + (simSoftCap(p.kd, 2.2) * 2.0);
    // Recent-form bonus. Used to hard-cap at +/-3 fights, so a 3-fight streak
    // and a 16-fight streak (Makhachev) scored identically — no credit at
    // all for sustained dominance past that point. Soft-capped instead so a
    // long streak keeps earning more, just with diminishing returns.
    // Scalar reduced 0.3 → 0.2: a 10-fight streak was adding ~2.3 pts on its
    // own — more than half the typical power-score gap in a close elite
    // matchup — causing the model to over-weight recent momentum relative to
    // the underlying production stats (striking, finishing, grappling) that
    // should be doing most of the work. 0.2 still meaningfully rewards
    // sustained dominance (max ≈ 1.5 pts) without letting streak alone flip a
    // competitive fight into a near-certain outcome.
    const form = simSoftCap(p.streak, 10) * 0.2;
    // Schedule quality is folded in here as a multiplier on the three
    // production-stat terms (striking, grappling, finishing) rather than
    // added on afterward as a flat bonus — see simScheduleMultiplier. Pure
    // fight-count experience (activityCredit) and the other situational
    // factors stay additive, since those aren't claims about whether the
    // underlying numbers are trustworthy.
    const production = (strikingNet + grappling + finishing) * p.scheduleMultiplier;
    // Subtotal before the finish-vulnerability penalty, which now applies
    // as a PERCENTAGE of this subtotal (see simFinishVulnerability) rather
    // than a flat point subtraction summed in alongside everything else.
    // Math.abs() on the subtotal so the penalty always reduces the score,
    // even for a fighter whose subtotal is already negative — multiplying
    // a negative subtotal by a negative fraction would otherwise flip the
    // sign and accidentally reward them for being finish-prone.
    const subtotal = production + tdDefBonus + form + p.activityCredit + p.trajectory + p.age + p.layoff + p.bigFight + p.controlBoost + p.undefeatedBoost + p.durabilityBoost;
    const afterFinishPenalty = subtotal + Math.abs(subtotal) * p.finishVulnerability;
    return afterFinishPenalty + (p.fiveRoundFactor || 0);
  }

  // Numeric rank tier from the roster's static rank field: champ/interim
  // champ are the top tier, "#N" parses to N, and "NR"/unknown returns
  // null (no signal either way — never treated as "worse"). The roster data
  // stores champ/interim-champ as either "C"/"IC" or "#C"/"#IC" depending on
  // division — only matching the bare form meant a fighter's best possible
  // win (over an actual champion recorded as "#C") was silently scoring as
  // "no rank signal at all," the same as an opponent with no rank whatsoever.
  function simRankTier(name) {
    // Read from the loaded rankings JSON (RANKINGS_LOOKUP) so the simulator
    // stays in sync whenever rankings.json is updated, rather than relying on
    // the stale rank field embedded in each FIGHTERS roster entry.
    const badge = fighterDivisionRankBadge(name);
    if (!badge) return null;
    const r = badge.replace(/^#/, '').toUpperCase();
    if (r === 'C' || r === 'CHAMPION') return 0;
    if (r === 'IC') return 0.5;
    const m = r.match(/^(\d+)$/);
    return m ? parseInt(m[1], 10) : null;
  }

  // When the division's own rankings already say two fighters are close
  // peers (adjacent or near-adjacent spots), that's a quality-of-competition
  // signal raw per-fight counting stats don't capture — so it pulls a
  // stat-driven score gap back toward even. Falls off fast: only fighters
  // within ~4 ranking spots are affected, and pairs with no usable rank on
  // either side (unranked, unsynced) are left completely alone.
  // Divisor widened 2 → 4: the old formula treated champ vs #1 contender
  // (gap=1) as barely near-peers (20% compression) and gave zero compression
  // to any pairing 2+ ranks apart. That's too narrow — a #1 contender has
  // clearly earned their spot and shouldn't have a large stat gap amplified
  // at full strength just because they're one rung below the title. 4 gives
  // ~45% compression at gap=1 (champ/#1), ~20% at gap=2 (#1/#3), tapering
  // cleanly to zero by gap=4+. Fighters far down the rankings are still
  // treated entirely on raw stats with no compression.
  function simRankClosenessFactor(nameA, nameB) {
    const ra = simRankTier(nameA), rb = simRankTier(nameB);
    if (ra == null || rb == null) return 0;
    const gap = Math.abs(ra - rb);
    const closeness = Math.max(0, 1 - gap / 4);
    return closeness * closeness; // 1 at gap 0, 0.56 at gap 1, 0.25 at gap 2, 0 by gap 4+
  }

  // For opponents no longer in current rankings (retired, faded, etc.),
  // estimate the approximate tier they held at the time of a fight based on
  // their own UFC record up to that date. This gives appropriate credit for
  // wins over former champions/contenders that the current roster no longer
  // reflects. UFC win count plus whether any of those wins came over then-
  // ranked fighters (proxy for actual contender status, since per-fight
  // historical rankings aren't stored). Returns null if no estimate is
  // possible (opponent unknown or had no UFC wins before the fight).
  function simEstimateHistoricalTier(oppName, beforeDate) {
    const oppHist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[oppName]) || [];
    if (!oppHist.length) return null;
    const cutoff = beforeDate ? new Date(beforeDate).getTime() : __now();
    let ufcWins = 0, hadRankedWin = false;
    oppHist.forEach(f => {
      if (!f.date || f.result !== 'W') return;
      if (String(f.org || '').toUpperCase() !== 'UFC') return;
      const d = new Date(f.date).getTime();
      if (isNaN(d) || d >= cutoff) return;
      ufcWins++;
      if (simRankTier(f.opponent) !== null) hadRankedWin = true;
    });
    if (ufcWins >= 5 && hadRankedWin) return 7;  // established contender
    if (ufcWins >= 5)                 return 10; // solid mid-ranker
    if (ufcWins >= 3)                 return 12; // borderline ranked
    if (ufcWins >= 1)                 return 14; // barely ranked
    return null;
  }

  // Quality score [0, 1] for the best ranked win in a fighter's history.
  // 0 = no wins over any currently-ranked or estimably-ranked opponent;
  // 1.0 = has beaten the champion. Linear: #15 ≈ 0.1, #10 ≈ 0.33,
  // #5 ≈ 0.67, #1 ≈ 0.93. Floor of 0.1 so even a win at the very back
  // of the rankings registers as a small amount of proof — it's still a
  // ranked opponent. For opponents who are now unranked, falls back to
  // simEstimateHistoricalTier to reconstruct their approximate tier at
  // fight time rather than silently giving zero credit.
  function simBestWinQuality(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    let best = 0;
    hist.forEach(f => {
      if (f.result !== 'W') return;
      let tier = simRankTier(f.opponent);
      if (tier == null) tier = simEstimateHistoricalTier(f.opponent, f.date);
      if (tier == null) return;
      const q = Math.max(0.1, 1 - tier / 15);
      if (q > best) best = q;
    });
    return best;
  }

  // simRateCredibility/simScheduleMultiplier discount a thin or padded
  // resume's raw STATS, and simRankClosenessFactor softens a stat gap when
  // both fighters are already close peers — but none of them stop a gaudy
  // counting-stat profile built entirely against unranked opposition from
  // outright favoring its owner over a CURRENTLY elite opponent the moment
  // the gap is wide instead of close (e.g. an undefeated 9-0 prospect who
  // has never faced anyone ranked projecting as a 90% favorite over a
  // reigning champion). That's not "uncertain", it's a real gap in
  // demonstrated level the stats alone can't speak to.
  //
  // This applies an asymmetric penalty that scales by the quality of the
  // fighter's best ranked win (simBestWinQuality). Zero ranked wins = full
  // penalty. Beating the back of the rankings (#15, quality ≈ 0.1) barely
  // dents it — you've shown up once, but at the lowest tier. Beating a top-5
  // contender zeroes it out almost entirely. Beating the champion eliminates
  // it. Scales by how elite the CURRENT opponent is (eliteness) — stepping up
  // to fight the back of the rankings for the first time earns only a small
  // raw penalty, stepping up to fight the champion earns close to the full
  // hit. Two unranked fighters are unaffected either way (oppTier null).
  //
  // Squared decay (1 - bestWinQ)² instead of linear: the original linear
  // formula left 40% of the max penalty (≈2.35 pts) on a fighter who had
  // beaten a #6 — treating "beat a ranked opponent once" as still 40% unproven.
  // That's too aggressive; one quality win against ranked competition is strong
  // evidence, and the residual uncertainty should collapse non-linearly. With
  // the squared form: bestWinQ=0 still gets full penalty, but bestWinQ=0.6
  // (beat #6) drops to 16% → ≈0.94 pts, and bestWinQ=0.93 (beat #1) is
  // essentially 0. A fighter in the "grey area" — partially proven — now
  // receives a proportionally smaller penalty rather than nearly half the max.
  // A fighter's recent UFC bouts (wins/losses only), most recent first.
  function simRecentUfc(name, n) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    return hist
      .filter(f => f.date && (f.result === 'W' || f.result === 'L') && String(f.org || '').toUpperCase() === 'UFC')
      .sort((a, b) => new Date(b.date) - new Date(a.date))
      .slice(0, n || 5);
  }

  // Count of a fighter's UFC bouts (wins + losses) on record.
  function simUfcFightCount(name) {
    const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
    return hist.filter(f => f.date && (f.result === 'W' || f.result === 'L') && String(f.org || '').toUpperCase() === 'UFC').length;
  }

  function simFighterAge(name) {
    const dob = ((typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[name]) || {}).dob;
    if (!dob) return null;
    const t = new Date(dob).getTime();
    if (isNaN(t)) return null;
    return (__now() - t) / (1000 * 60 * 60 * 24 * 365.25);
  }

  // How much of a CURRENT threat a proven-but-unranked veteran still is, [0,1].
  // Scales the unranked-opponent unproven penalty (below) so a prospect gets
  // the full "you haven't been tested at this level" treatment against a still-
  // credible vet — inconsistent but beating ranked names and not old (Kevin
  // Holland, 33, recent wins over the likes of Luque/Nelson → ~0.9) — while a
  // genuinely declining vet on a bad run (old, lost most of their last five —
  // late-career Niko Price → ~0.2) does NOT inflate the prospect's number. This
  // is the failsafe: beating a washed vet shouldn't read as proof, so the
  // penalty for facing one shrinks toward zero. Built from recent UFC form, the
  // quality of the best recent win, and age.
  function simVetThreat(name) {
    const recent = simRecentUfc(name, 5);
    if (!recent.length) return 0.6; // no UFC sample — neutral-ish, neither proven nor washed
    const winRate = recent.filter(f => f.result === 'W').length / recent.length;
    let skid = 0;
    for (const f of recent) { if (f.result === 'L') skid++; else break; }
    let recentWinQ = 0;
    recent.forEach(f => {
      if (f.result !== 'W') return;
      let t = simRankTier(f.opponent);
      if (t == null) t = simEstimateHistoricalTier(f.opponent, f.date);
      if (t != null) recentWinQ = Math.max(recentWinQ, Math.max(0.1, 1 - t / 15));
    });
    const age = simFighterAge(name);
    let ageFactor = 1;
    if (age != null && age > 36) ageFactor = Math.max(0.5, 1 - (age - 36) * 0.08);
    const base = 0.4 + 0.5 * winRate - 0.13 * Math.min(skid, 3) + 0.35 * recentWinQ;
    return Math.max(0, Math.min(1, base)) * ageFactor;
  }

  // Discount applied when crediting a fighter's win over a now-unranked former
  // contender, based on how declined that opponent already was ON THE DATE of
  // the fight. Symmetric counterpart to simVetThreat (which protects against
  // facing a washed vet): beating a former contender in their prime is a real
  // proof-of-level win and counts in full (1.0), but beating one who was
  // already OLD and on a LOSING SKID at the time — e.g. a 41-year-old Masvidal
  // mid-slide, or a 38-year-old Jeremy Stephens on a five-fight skid — proves
  // much less, so the credit is scaled down. Deliberately narrow: only triggers
  // when BOTH conditions hold (age > 35 AND a 2+ fight UFC losing streak as of
  // that date), so a healthy or still-winning contender is never discounted at
  // any age, and prime-era wins keep full value.
  function simBeatenVetDiscount(oppName, date) {
    const cutoff = date ? new Date(date).getTime() : __now();
    let ageAt = null;
    const dob = ((typeof FIGHTER_STATS !== 'undefined' && FIGHTER_STATS[oppName]) || {}).dob;
    if (dob) { const t = new Date(dob).getTime(); if (!isNaN(t)) ageAt = (cutoff - t) / (1000 * 60 * 60 * 24 * 365.25); }
    const priorUfc = ((typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[oppName]) || [])
      .filter(f => f.date && (f.result === 'W' || f.result === 'L') && String(f.org || '').toUpperCase() === 'UFC')
      .filter(f => { const d = new Date(f.date).getTime(); return !isNaN(d) && d < cutoff; })
      .sort((a, b) => new Date(b.date) - new Date(a.date));
    let skid = 0;
    for (const f of priorUfc) { if (f.result === 'L') skid++; else break; }
    if (ageAt == null || ageAt <= 35 || skid < 2) return 1;
    return Math.max(0.2, 1 - 0.18 * Math.min(skid, 4) - 0.06 * (ageAt - 35));
  }

  // How "proven" a fighter is for the unranked-opponent branch of the unproven
  // penalty, [0,1] — whichever of two independent bars is higher:
  //   1) Resume: quality of the best genuine contender they've beaten. A
  //      currently-ranked win counts in full; a win over an opponent who was
  //      themselves a real contender (estimated tier ≤ 7, i.e. they'd beaten a
  //      ranked fighter of their own) counts — but is scaled by how declined
  //      that opponent already was at fight time (simBeatenVetDiscount), so
  //      beating a faded ex-contender on a losing skid earns little; a win over
  //      a never-ranked journeyman barely registers (0.05). Deliberately
  //      STRICTER than simBestWinQuality so a prospect padding a record against
  //      gatekeepers (e.g. a faded Niko Price) reads as essentially unproven.
  //   2) Tenure: simply having had a long UFC career. An established fighter
  //      (~18+ UFC bouts) is fully proven regardless of (1) — the resume
  //      estimator only sees CURRENT rankings, so it routinely misses that a
  //      long-since-faded opponent was elite at the time and would otherwise
  //      mislabel vets like Masvidal as "unproven." A prospect with a handful
  //      of UFC bouts earns ~no tenure credit, so the resume term governs them.
  function simProvenLevel(name) {
    const wins = ((typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || []).filter(f => f.result === 'W');
    let resume = 0;
    wins.forEach(f => {
      const live = simRankTier(f.opponent);
      if (live != null) { resume = Math.max(resume, Math.max(0.1, 1 - live / 15)); return; }
      const est = simEstimateHistoricalTier(f.opponent, f.date);
      if (est == null) return;
      const q = est <= 7
        ? Math.max(0.1, 1 - est / 15) * simBeatenVetDiscount(f.opponent, f.date)
        : 0.05;
      resume = Math.max(resume, q);
    });
    const tenure = Math.max(0, Math.min(1, (simUfcFightCount(name) - 4) / 14));
    return Math.max(resume, tenure);
  }

  function simUnprovenPenalty(name, oppName) {
    const oppTier = simRankTier(oppName);
    if (oppTier != null) {
      // Opponent is currently ranked. Scale 8.0 / cap 7.0: a truly unproven
      // fighter vs the champion faces a ~5.7-pt penalty, a meaningful underdog
      // regardless of how inflated their counting stats look on a soft
      // schedule. Uses simProvenLevel (same tenure-gated measure as the
      // unranked branch below) rather than simBestWinQuality so a long-tenured
      // fighter — a former champion like Edwards whose best wins are now lower-
      // ranked — is never mislabeled "unproven" against a higher-ranked
      // opponent; only a genuinely thin résumé (a true prospect) is penalized.
      const eliteness = Math.max(0, 1 - oppTier / 15);
      const rawPenalty = simSoftCap(eliteness * 8.0, 7.0);
      const unprovenFraction = Math.max(0, 1 - simProvenLevel(name));
      return rawPenalty * (unprovenFraction * unprovenFraction);
    }
    // Opponent is currently UNRANKED — but not necessarily an unknown. A faded
    // ex-contender or an inconsistent-but-proven vet (lots of UFC wins, some
    // over ranked names, e.g. Kevin Holland) is still a real demonstrated level
    // a padded-stat prospect has never been tested against. Keying the penalty
    // purely on the live top-15 silently skipped that whole class, letting an
    // undefeated regional prospect project as an 85%+ favorite over a tough
    // vet. So fall back to the opponent's estimated historical tier, but scale
    // the whole thing two ways the ranked branch doesn't need:
    //   • simVetThreat(opponent) — a genuinely declining vet is a weaker test,
    //     so the penalty (and thus the prospect's discount) shrinks. Failsafe.
    //   • simProvenLevel(name) instead of simBestWinQuality — stricter about
    //     what counts as a proven win, but tenure-gated so an established
    //     fighter facing an unranked opponent is never mislabeled "unproven."
    // Opponents with no UFC wins to estimate from → no penalty, so two genuine
    // unknowns are left alone.
    const est = simEstimateHistoricalTier(oppName, null);
    if (est == null) return 0;
    const eliteness = Math.max(0, 1 - est / 15);
    const rawPenalty = simSoftCap(eliteness * 8.0, 7.0);
    const unprovenFraction = Math.max(0, 1 - simProvenLevel(name));
    return rawPenalty * (unprovenFraction * unprovenFraction) * simVetThreat(oppName);
  }

  // If these two have actually fought before, that's real fight-specific
  // information — stylistic answers, game-planning, who-figured-out-who —
  // that raw aggregate stats can't see. Trusted within an 8-year window,
  // tapering gradually to zero rather than hard-cutting at a fixed age (a
  // meeting at 5 years and 4 months is still meaningful — it shouldn't read
  // as zero just because an earlier, tighter cutoff happened to fall a few
  // months short of it; e.g. Ankalaev's decision win over Krylov, Feb 2021,
  // was being discarded entirely by an old 5-year cliff despite still being
  // clearly relevant). Weighted by how the fight ended (a finish says a lot
  // more than a split decision) and how recent it was (a fresh result is
  // more predictive than one nearing the end of the window). Checks both
  // fighters' histories since a meeting should be recorded on at least one
  // side.
  function simHeadToHeadBoost(nameA, nameB) {
    const findMeeting = (name, opp) => {
      const hist = (typeof FIGHT_HISTORY !== 'undefined' && FIGHT_HISTORY[name]) || [];
      return hist.find(f => f.opponent === opp && f.result && f.result !== '–' && f.method !== 'Upcoming' && f.date);
    };
    const fromA = findMeeting(nameA, nameB);
    const fromB = !fromA ? findMeeting(nameB, nameA) : null;
    const meeting = fromA || fromB;
    if (!meeting) return 0;
    const aWon = fromA ? meeting.result === 'W' : meeting.result === 'L';
    const d = new Date(meeting.date);
    if (isNaN(d)) return 0;
    const yearsAgo = (__now() - d.getTime()) / (1000 * 60 * 60 * 24 * 365.25);
    const DECAY_YEARS = 8;
    if (yearsAgo > DECAY_YEARS || yearsAgo < 0) return 0;
    const recency = 1 - (yearsAgo / DECAY_YEARS); // 1.0 right after the fight, tapering to 0 at the window edge
    const method = String(meeting.method || '').toUpperCase();
    const isFinish = method.includes('KO') || method.includes('TKO') || method.includes('SUB');
    const magnitude = (isFinish ? 1.2 : 0.7) * recency;
    return aWon ? magnitude : -magnitude;
  }

  function simWinProbability(nameA, nameB, rounds) {
    const profA = getSimProfile(nameA, rounds);
    const profB = getSimProfile(nameB, rounds);
    const sa = simPowerScore(profA);
    const sb = simPowerScore(profB);
    // Logistic curve on the power-score differential — gives clear separation
    // for lopsided matchups while keeping closely-matched fights near 50/50.
    // The stat/style differential is softened when the rankings say these two
    // are near-peers (see simRankClosenessFactor). Head-to-head history is
    // added afterward, unsoftened — a real prior result between these two
    // specific fighters isn't a stat artifact the closeness factor should be
    // discounting, it's ground truth, and rematches are often exactly the
    // close-peer pairings that factor would otherwise dampen.
    // Widened from 2.3 → 3.2 → 5.4. The tighter curves turned moderate raw score
    // gaps (5-8 points, mostly from stacked grappling/finishing terms) into
    // overconfident probabilities the betting market never priced anywhere close
    // to. 5.4 was fit empirically: a point-in-time backtest of this exact formula
    // over 4,518 decided UFC bouts (each fighter reconstructed from only their
    // prior box scores, current rankings disabled to avoid leakage — see
    // scripts/sim-backtest/) showed the model was systematically overconfident —
    // its 70-80% picks won ~65%, its 20-30% picks won ~35%. Raising k to 5.4
    // flattens the curve to fix that: it improved out-of-sample log loss and
    // Brier score while leaving accuracy (60.9%) and every pick order unchanged.
    // Big favorites now read ~64-67% instead of ~72-76%; coin-flips barely move.
    // Widened further when either fighter is a "boom or bust" type (see
    // simVolatility) — a high-variance fighter's predicted edge shouldn't be
    // trusted at the same confidence as a low-variance one, since their
    // actual outcomes swing harder than a stats-only gap implies. Only the
    // more volatile of the two fighters matters here: either side being
    // unpredictable is enough to soften the whole matchup's confidence.
    //
    // Also widened when either fighter's rate stats are low-credibility
    // (thin UFC sample, no proven ranked competition — see
    // simRateCredibility). That used to be handled entirely by crushing the
    // low-credibility fighter's own stat inputs toward a generic baseline in
    // simCredibilityDampen, which had the side effect of treating "small,
    // unproven sample" as "assume mediocre" — a fighter actually running
    // through opponents got their real production discounted away just for
    // not yet having the UFC tenure to "prove" it. Now that dampening is
    // softer (floored at 50% pull, not 100%), and the rest of the
    // uncertainty instead widens this curve: a thin-sample fighter's
    // apparent edge (or deficit) is treated as less certain, pulling the
    // probability back toward 50/50, rather than silently overwritten with
    // an average-fighter's numbers before the curve even sees it.
    const volatility = Math.max(simVolatility(nameA), simVolatility(nameB));
    const lowCredibility = Math.max(1 - simRateCredibility(nameA), 1 - simRateCredibility(nameB));
    const uncertainty = Math.max(volatility, lowCredibility * 0.7);
    const k = 5.4 * (1 + 0.5 * uncertainty);
    const statDiff = ((sa - sb) + simStyleMatchupDelta(nameA, nameB, profA, profB)) * (1 - 0.8 * simRankClosenessFactor(nameA, nameB));
    // Unproven-against-the-level penalty (see simUnprovenPenalty) — applied
    // unsoftened, same as head-to-head, since a real demonstrated-level gap
    // isn't a stat artifact rankClosenessFactor should be discounting (and
    // it never fires for a close-rank pairing anyway, where both sides have
    // typically cleared this bar already).
    const diff = statDiff + simHeadToHeadBoost(nameA, nameB)
      - simUnprovenPenalty(nameA, nameB) + simUnprovenPenalty(nameB, nameA);
    const raw = 1 / (1 + Math.exp(-diff / k));
    return Math.min(0.96, Math.max(0.04, raw)); // no fight is a guaranteed lock
  }

  // Builds a weighted sample pool of {method, round} drawn from a fighter's
  // own historical fights, so method/round outcomes reflect how THEY actually
  // win. Draws from the FULL win history (every org), not just UFC wins --
  // UFC-only sampling produced artificial 100% splits for fighters with only
  // one or two UFC wins on record (e.g. a single UFC win by TKO meant every
  // simulated win came back "KO/TKO"). UFC wins are still weighted more
  // heavily than regional/other-org wins since they're the most
  // representative data point, but they no longer wipe out the rest of the
  // career sample. Decision LOSSES are also folded in (lightly, uncredited
  // toward a win) because going the distance -- win or lose -- is itself a
  // signal that a fighter's fights tend to land there.
  

  return {
    simWinProbability: simWinProbability,
    simPowerScore: simPowerScore,
    getSimProfile: getSimProfile,
    simVolatility: simVolatility,
    simRateCredibility: simRateCredibility,
    simStyleMatchupDelta: simStyleMatchupDelta,
    simRankClosenessFactor: simRankClosenessFactor,
    simHeadToHeadBoost: simHeadToHeadBoost,
    simUnprovenPenalty: simUnprovenPenalty,
    simControlNet: simControlNet,
    simControlTimeBoost: simControlTimeBoost,
    simSoftCap: simSoftCap,
    setStats: function(s){ FIGHTER_STATS = s; },
    setHistory: function(h){ FIGHT_HISTORY = h; },
    setFighters: function(f){ FIGHTERS = f; },
    setNow: function(ts){ __NOW = ts; },
    setBox: function(b){ window.FIGHT_STATS = b; },
    setRankBadge: function(fn){ __rankBadge = fn || function(){ return null; }; }
  };
};

  window.createScorer = module.exports;
})();
