// AUTO-GENERATED by scripts/gen-app-fighter-extras.cjs — do not edit by hand.
// Per-fighter Career Accolades, Tape Study, Fight History (with embedded
// box scores + a regional-promotion-strength tier per row), Odds History,
// News and Record Breakdown for the app's premium fighter profile (see
// worker/index.js's /api/app/fighter-extras). Keyed by the same slug space
// as data/fighter-lite.json's bySlug. Regenerate rather than patch: see the
// script header.

// DATA MOVED OUT (Sep 2026 cold-start latency fix -- see git log): this used
// to be a 19MB `export default {...}` object literal baked directly into the
// bundle, which meant V8 had to parse and compile it on every cold Worker
// isolate start -- for EVERY request, because wrangler.toml's
// run_worker_first=true means this module gets pulled in regardless of
// route. The data itself now lives in data/fighter-extras-full.json, built
// and deployed normally (it is NOT excluded from build-site.sh -- it stays
// protected the same way every other /data/*.json the Worker serves via
// env.ASSETS already is: worker/index.js's final routing fallthrough
// requires a subscribed session for any path that isn't explicitly public;
// this internal env.ASSETS.fetch() call bypasses that gate entirely, same as
// loadResults/loadClosingOdds/etc already do). Fetched once per isolate and
// cached in memory. Callers must now `await getFighterExtras(env)` instead
// of importing a ready-made object.
let _cache = null;
let _loading = null;
async function getFighterExtras(env) {
  if (_cache) return _cache;
  if (_loading) return _loading;
  _loading = (async () => {
    const res = await env.ASSETS.fetch(new Request("https://internal.gillylab/data/fighter-extras-full.json"));
    if (!res.ok) throw new Error("fighter-extras-full.json missing from the deployed build (status " + res.status + ") -- did build-site.sh run after this data was regenerated?");
    _cache = await res.json();
    return _cache;
  })();
  try { return await _loading; } finally { _loading = null; }
}
export { getFighterExtras };
