// AUTO-GENERATED by scripts/gen-app-fighter-extras.cjs — do not edit by hand.
// Per-fighter Career Accolades, Tape Study, Fight History (with embedded
// box scores + a regional-promotion-strength tier per row), Odds History,
// News and Record Breakdown for the app's premium fighter profile (see
// worker/index.js's /api/app/fighter-extras). Keyed by the same slug space
// as data/fighter-lite.json's bySlug. Regenerate rather than patch: see the
// script header.

// DATA MOVED OUT: this used to be a 19MB `export default {...}` object
// literal baked directly into the bundle, which meant V8 had to parse and
// compile it on every cold Worker isolate start -- for EVERY request,
// because wrangler.toml's run_worker_first=true means this module gets
// pulled in regardless of route. The data itself now lives in
// data/fighter-extras-full.json (excluded by name in build-site.sh, same
// treatment as data/fight-grid-all.json -- see CLAUDE.md #1/#3), fetched
// once per isolate via env.ASSETS and cached in memory. Callers must now
// `await getFighterExtras(env)` instead of importing a ready-made object.
let _cache = null;
let _loading = null;
async function getFighterExtras(env) {
  if (_cache) return _cache;
  if (_loading) return _loading;
  _loading = (async () => {
    const res = await env.ASSETS.fetch(new Request("https://internal.gillylab/data/fighter-extras-full.json"));
    if (!res.ok) throw new Error("fighter-extras-full.json missing from the deployed build (status " + res.status + ") -- did build-site.sh run after this data was regenerated?");
    _cache = await res.json();
    return _cache;
  })();
  try { return await _loading; } finally { _loading = null; }
}
export { getFighterExtras };
