// AUTO-GENERATED by scripts/gen-landing-data.cjs — do not edit by hand.
export default {
  "generatedAt": "2026-07-16T13:30:14.677Z",
  "rankings": {
    "division": "Bantamweight",
    "rows": [
      {
        "n": "C",
        "name": "Petr Yan",
        "record": "20-5-0",
        "champ": true,
        "slug": "petr-yan",
        "initials": "PY"
      },
      {
        "n": "1",
        "name": "Merab Dvalishvili",
        "record": "21-5-0",
        "champ": false,
        "slug": "merab-dvalishvili",
        "initials": "MD"
      },
      {
        "n": "2",
        "name": "Sean O'Malley",
        "record": "19-3-0",
        "champ": false,
        "slug": "sean-omalley",
        "initials": "SO"
      },
      {
        "n": "3",
        "name": "Umar Nurmagomedov",
        "record": "20-1-0",
        "champ": false,
        "slug": "umar-nurmagomedov",
        "initials": "UN"
      },
      {
        "n": "4",
        "name": "Cory Sandhagen",
        "record": "18-6-0",
        "champ": false,
        "slug": "cory-sandhagen",
        "initials": "CS"
      },
      {
        "n": "5",
        "name": "Song Yadong",
        "record": "23-9-1",
        "champ": false,
        "slug": "song-yadong",
        "initials": "SY"
      }
    ]
  },
  "roster": {
    "week": "July 8 – July 14, 2026",
    "added": [
      "Abubakar Vagaev"
    ],
    "addedTotal": 5,
    "removed": [],
    "removedTotal": 0,
    "names": [
      "Aaron Pico",
      "Abdul Hussein",
      "Abdul Rakhman Yakhyaev",
      "Abdul-Kareem Al-Selwady",
      "Abubakar Vagaev",
      "Abus Magomedov",
      "Adrian Yanez",
      "Aiemann Zahabi",
      "Ailin Perez",
      "Alatengheili",
      "Alberto Montes",
      "Alden Coria"
    ],
    "total": 644
  },
  "featured": {
    "name": "Islam Makhachev",
    "slug": "islam-makhachev",
    "division": "Welterweight",
    "record": "28-1-0",
    "initials": "IM",
    "bio": [
      [
        "Age",
        34
      ],
      [
        "Height",
        "5'10\""
      ],
      [
        "Reach",
        "70\""
      ],
      [
        "Stance",
        "Southpaw"
      ],
      [
        "Gym",
        "AKA/Eagles"
      ]
    ],
    "groups": [
      {
        "t": "Striking",
        "rows": [
          {
            "label": "Sig. strikes landed / min",
            "val": "2.45",
            "cls": "bad",
            "w": 27.9,
            "tickX": 47.8,
            "bar": true
          },
          {
            "label": "Striking accuracy",
            "val": "58%",
            "cls": "good",
            "w": 93.5,
            "tickX": 79.8,
            "bar": true
          },
          {
            "label": "Sig. strikes absorbed / min",
            "val": "1.45",
            "cls": "good",
            "w": 13.5,
            "tickX": 32.6,
            "bar": true
          },
          {
            "label": "Striking defense",
            "val": "62%",
            "cls": "good",
            "w": 93.9,
            "tickX": 81.8,
            "bar": true
          },
          {
            "label": "Knockdowns / 15 min",
            "val": "0.3",
            "cls": "bad",
            "w": 6,
            "tickX": 11.7,
            "bar": true
          }
        ]
      },
      {
        "t": "Grappling",
        "rows": [
          {
            "label": "Takedowns / 15 min",
            "val": "3.1",
            "cls": "good",
            "w": 39.8,
            "tickX": 18.3,
            "bar": true
          },
          {
            "label": "Takedown accuracy",
            "val": "56%",
            "cls": "good",
            "w": 88.9,
            "tickX": 63.5,
            "bar": true
          },
          {
            "label": "Takedown defense",
            "val": "91%",
            "cls": "good",
            "w": 91,
            "tickX": 68,
            "bar": true
          },
          {
            "label": "Submissions / 15 min",
            "val": "0.98",
            "cls": "good",
            "w": 59.8,
            "tickX": 37.8,
            "bar": true
          }
        ]
      },
      {
        "t": "Miscellaneous",
        "rows": [
          {
            "label": "Finish rate",
            "val": "64%",
            "cls": "bad",
            "w": 64,
            "tickX": 74,
            "bar": true
          },
          {
            "label": "Win streak",
            "val": "16",
            "cls": "",
            "w": 0,
            "tickX": null,
            "bar": false
          }
        ]
      }
    ],
    "hasBars": true
  },
  "oddsHistory": {
    "name": "Max Holloway",
    "slug": "max-holloway",
    "initials": "MH",
    "rows": [
      {
        "opponent": "Conor McGregor",
        "odds": -324
      },
      {
        "opponent": "Charles Oliveira",
        "odds": -208
      },
      {
        "opponent": "Dustin Poirier",
        "odds": -116
      },
      {
        "opponent": "Ilia Topuria",
        "odds": 228
      },
      {
        "opponent": "Justin Gaethje",
        "odds": 143
      },
      {
        "opponent": "Jung Chan-sung",
        "odds": -750
      },
      {
        "opponent": "Arnold Allen",
        "odds": -170
      }
    ]
  },
  "matchup": {
    "event": "UFC Fight Night",
    "startsAt": "2026-07-19T00:00:00.000Z",
    "weightClass": "Middleweight",
    "titleBout": false,
    "rounds": 5,
    "a": {
      "name": "Dricus Du Plessis",
      "slug": "dricus-du-plessis",
      "initials": "DP",
      "record": "23-3-0",
      "rank": "#2",
      "lean": 44,
      "slpm": 5.18,
      "sapm": 4.33
    },
    "b": {
      "name": "Kamaru Usman",
      "slug": "kamaru-usman",
      "initials": "KU",
      "record": "21-4-0",
      "rank": "#9",
      "lean": 42,
      "slpm": 4.16,
      "sapm": 2.67
    },
    "odds": {
      "a": "-249",
      "b": "+201",
      "books": 7,
      "favA": true,
      "favB": false
    }
  },
  "parlay": {
    "event": "UFC Fight Night",
    "kind": "moneyline",
    "book": "Consensus · 7 books",
    "legs": [
      {
        "pick": "Dricus Du Plessis",
        "slug": "dricus-du-plessis",
        "opponent": "Kamaru Usman",
        "label": "to win",
        "odds": "-249"
      },
      {
        "pick": "Christian Leroy Duncan",
        "slug": "christian-leroy-duncan",
        "opponent": "Jared Cannonier",
        "label": "to win",
        "odds": "-368"
      },
      {
        "pick": "Chase Hooper",
        "slug": "chase-hooper",
        "opponent": "Mitch Ramirez",
        "label": "to win",
        "odds": "-356"
      }
    ],
    "combined": "+128",
    "stake": 100,
    "payout": 228
  },
  "styleDemo": {
    "a": {
      "name": "Dricus Du Plessis",
      "slug": "dricus-du-plessis",
      "initials": "DP",
      "record": "23-3-0",
      "rank": "#2",
      "lean": 44,
      "pace": 10.6,
      "path": "Comfortable everywhere — his edge is the bigger finishing threat; drag Usman into his stronger area."
    },
    "b": {
      "name": "Kamaru Usman",
      "slug": "kamaru-usman",
      "initials": "KU",
      "record": "21-4-0",
      "rank": "#9",
      "lean": 42,
      "pace": 8,
      "path": "Comfortable everywhere — best route is the takedown (Plessis defends only 35%)."
    }
  },
  "counts": {
    "fighters": 3101,
    "bouts": 29247,
    "historyRows": 58493,
    "videos": 1668,
    "photos": 2327
  },
  "photos": [
    "islam-makhachev",
    "max-holloway",
    "dricus-du-plessis",
    "kamaru-usman",
    "christian-leroy-duncan",
    "chase-hooper",
    "petr-yan",
    "merab-dvalishvili",
    "sean-omalley",
    "umar-nurmagomedov",
    "cory-sandhagen",
    "song-yadong"
  ],
  "card": {
    "event": "UFC Fight Night",
    "slug": "ufc-fight-night-july-18-2026",
    "date": "2026-07-19",
    "prelimsAt": "2026-07-18T21:00:00.000Z",
    "location": "Paycom Center, Oklahoma City, OK",
    "city": "Oklahoma City",
    "fights": [
      {
        "f1": "Dricus Du Plessis",
        "f2": "Kamaru Usman",
        "s1": "dricus-du-plessis",
        "s2": "kamaru-usman",
        "rec1": "23-3-0",
        "rec2": "21-4-0",
        "rank1": "#2",
        "rank2": "#9",
        "weight": "Middleweight",
        "rounds": 5,
        "o1": "-249",
        "o2": "+201",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 1",
        "main": true,
        "tape": {
          "a": {
            "ht": "6'0\"",
            "reach": "76\"",
            "age": 32,
            "stance": "Orthodox",
            "gym": "Team CIT MMA",
            "layoff": {
              "txt": "11 mo",
              "mo": 11,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Khamzat Chimaev",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Sean Strickland",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Israel Adesanya",
                "method": "Submission (Face crank)",
                "round": "4",
                "time": "3:38"
              },
              {
                "r": "W",
                "opp": "Sean Strickland",
                "method": "Decision (Split)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Robert Whittaker",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "2:23"
              }
            ]
          },
          "b": {
            "ht": "6'0\"",
            "reach": "76\"",
            "age": 39,
            "stance": "Switch",
            "gym": "Kill Cliff FC",
            "layoff": {
              "txt": "1y 1m",
              "mo": 13,
              "long": true
            },
            "l5": [
              {
                "r": "W",
                "opp": "Joaquin Buckley",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Khamzat Chimaev",
                "method": "Decision (Majority)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Leon Edwards",
                "method": "Decision (Majority)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Leon Edwards",
                "method": "KO (Head kick)",
                "round": "5",
                "time": "4:04"
              },
              {
                "r": "W",
                "opp": "Colby Covington",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Jared Cannonier",
        "f2": "Christian Leroy Duncan",
        "s1": "jared-cannonier",
        "s2": "christian-leroy-duncan",
        "rec1": "18-9-0",
        "rec2": "14-2-0",
        "rank1": "#11",
        "rank2": "#13",
        "weight": "Middleweight",
        "rounds": 3,
        "o1": "+287",
        "o2": "-368",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 2",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'11\"",
            "reach": "77.5\"",
            "age": 42,
            "stance": "Orthodox",
            "gym": "MMA Lab (2017–present)",
            "layoff": {
              "txt": "11 mo",
              "mo": 11,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Michael Page",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Gregory Rodrigues",
                "method": "TKO (Punches)",
                "round": "4",
                "time": "0:21"
              },
              {
                "r": "L",
                "opp": "Caio Borralho",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Nassourdine Imavov",
                "method": "TKO (Punches)",
                "round": "4",
                "time": "1:34"
              },
              {
                "r": "W",
                "opp": "Marvin Vettori",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "6'2\"",
            "reach": "79\"",
            "age": 30,
            "stance": "Switch",
            "gym": "Range Martial Arts Academy",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Roman Dolidze",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Marco Tulio",
                "method": "KO (Spinning backfist and punches)",
                "round": "2",
                "time": "3:28"
              },
              {
                "r": "W",
                "opp": "Eryk Anders",
                "method": "KO (Spinning back elbow and punches)",
                "round": "1",
                "time": "3:53"
              },
              {
                "r": "W",
                "opp": "Andrey Pulyaev",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Gregory Rodrigues",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Chase Hooper",
        "f2": "Mitch Ramirez",
        "s1": "chase-hooper",
        "s2": "mitch-ramirez",
        "rec1": "16-5-1",
        "rec2": "8-3-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Lightweight",
        "rounds": 3,
        "o1": "-356",
        "o2": "+277",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 3",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'1\"",
            "reach": "75.5\"",
            "age": 26,
            "stance": "Southpaw",
            "gym": "Combat Sport & Fitness",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Lance Gibson Jr.",
                "method": "TKO (Knees)",
                "round": "1",
                "time": "2:56"
              },
              {
                "r": "L",
                "opp": "Alexander Hernandez",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "4:58"
              },
              {
                "r": "W",
                "opp": "Jim Miller",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Clay Guida",
                "method": "Submission (Armbar)",
                "round": "1",
                "time": "3:41"
              },
              {
                "r": "W",
                "opp": "Viacheslav Borshchev",
                "method": "Submission (Brabo choke)",
                "round": "2",
                "time": "3:00"
              }
            ]
          },
          "b": {
            "ht": "5'11\"",
            "reach": "71\"",
            "age": 33,
            "stance": "Orthodox",
            "gym": "Syndicate MMA",
            "layoff": {
              "txt": "1y 0m",
              "mo": 12,
              "long": true
            },
            "l5": [
              {
                "r": "L",
                "opp": "Mike Davis",
                "method": "TKO (Flying knee and punches)",
                "round": "2",
                "time": "4:08"
              },
              {
                "r": "L",
                "opp": "Thiago Moises",
                "method": "TKO (Leg kicks)",
                "round": "3",
                "time": "0:15"
              },
              {
                "r": "W",
                "opp": "Aireon Tavarres",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "2:19"
              },
              {
                "r": "L",
                "opp": "Carlos Prates",
                "method": "TKO (Punch)",
                "round": "2",
                "time": "1:14"
              },
              {
                "r": "W",
                "opp": "Jeremie Holloway",
                "method": "TKO (Leg kick)",
                "round": "2",
                "time": "0:59"
              }
            ]
          }
        }
      },
      {
        "f1": "Tabatha Ricci",
        "f2": "Fatima Kline",
        "s1": "tabatha-ricci",
        "s2": "fatima-kline",
        "rec1": "12-4-0",
        "rec2": "9-1-0",
        "rank1": "#8",
        "rank2": "#11",
        "weight": "Women's Strawweight",
        "rounds": 3,
        "o1": "+358",
        "o2": "-486",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 4",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'1\"",
            "reach": "61\"",
            "age": 31,
            "stance": "Orthodox",
            "gym": "Paragon BJJ / Black House MMA",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Virna Jandiroba",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Amanda Ribas",
                "method": "TKO (Elbow and punches)",
                "round": "2",
                "time": "2:59"
              },
              {
                "r": "L",
                "opp": "Yan Xiaonan",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Angela Hill",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Tecia Pennington",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'6\"",
            "reach": "67\"",
            "age": 26,
            "stance": "Orthodox",
            "gym": "MK Muay Thai",
            "layoff": {
              "txt": "8 mo",
              "mo": 8,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Angela Hill",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Melissa Martinez",
                "method": "TKO (Head kick and punches)",
                "round": "3",
                "time": "2:36"
              },
              {
                "r": "W",
                "opp": "Victoria Dudakova",
                "method": "TKO (Elbows)",
                "round": "2",
                "time": "4:27"
              },
              {
                "r": "L",
                "opp": "Jasmine Jasudavicius",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Andressa Romero",
                "method": "Decision (Unanimous)",
                "round": "4",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Tommy McMillen",
        "f2": "Alberto Montes",
        "s1": "tommy-mcmillen",
        "s2": "alberto-montes",
        "rec1": "10-0-0",
        "rec2": "12-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Featherweight",
        "rounds": 3,
        "o1": "-148",
        "o2": "+123",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 5",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'0\"",
            "reach": "74\"",
            "age": 28,
            "stance": "Orthodox",
            "gym": "Red Hawk Academy",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Manolo Zecchini",
                "method": "TKO (Knee)",
                "round": "1",
                "time": "3:57"
              },
              {
                "r": "W",
                "opp": "David Mgoyan",
                "method": "Decision (Majority)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Dumar Roa",
                "method": "Submission (Rear-naked choke)",
                "round": "1",
                "time": "1:58"
              },
              {
                "r": "W",
                "opp": "Genier Penagos",
                "method": "Submission (Guillotine)",
                "round": "1",
                "time": "1:10"
              },
              {
                "r": "W",
                "opp": "Josh Wright",
                "method": "Submission (Guillotine)",
                "round": "1",
                "time": "2:13"
              }
            ]
          },
          "b": {
            "ht": "5'7\"",
            "reach": "69\"",
            "age": 32,
            "stance": "Orthodox",
            "gym": "The Goat Shed",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Ricky Turcios",
                "method": "Submission (Anaconda choke)",
                "round": "2",
                "time": "0:40"
              },
              {
                "r": "W",
                "opp": "Carlos Calderon",
                "method": "Submission (Anaconda choke)",
                "round": "2",
                "time": "2:38"
              },
              {
                "r": "W",
                "opp": "Kevin Garcia",
                "method": "Submission (D'Arce choke)",
                "round": "2",
                "time": "0:52"
              },
              {
                "r": "W",
                "opp": "Adam Ortiz",
                "method": "Submission (D'Arce choke)",
                "round": "1",
                "time": "2:09"
              },
              {
                "r": "L",
                "opp": "Ira Lukowsky",
                "method": "KO/TKO",
                "round": "2",
                "time": "0:17"
              }
            ]
          }
        }
      },
      {
        "f1": "Austin Bashi",
        "f2": "Jose Miguel Delgado",
        "s1": "austin-bashi",
        "s2": "jose-miguel-delgado",
        "rec1": "14-1-0",
        "rec2": "",
        "rank1": "NR",
        "rank2": "",
        "weight": "Featherweight",
        "rounds": 3,
        "o1": "-103",
        "o2": "-119",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 1",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'6\"",
            "reach": "70\"",
            "age": 24,
            "stance": "Orthodox",
            "gym": "Warrior Way Martial Arts",
            "layoff": {
              "txt": "11 mo",
              "mo": 11,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "John Yannis",
                "method": "Submission (Rear-naked choke)",
                "round": "1",
                "time": "3:39"
              },
              {
                "r": "L",
                "opp": "Christian Rodriguez",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Dorian Ramos",
                "method": "Submission (Rear-naked choke)",
                "round": "2",
                "time": "3:15"
              },
              {
                "r": "W",
                "opp": "Zac Riley",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "3:48"
              },
              {
                "r": "W",
                "opp": "Askar Askar",
                "method": "Submission (Rear-naked choke)",
                "round": "2",
                "time": "1:48"
              }
            ]
          },
          "b": {
            "ht": "5'11\"",
            "reach": "73\"",
            "age": 28,
            "stance": "Switch",
            "gym": "The MMA Lab",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Andre Fili",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Nathaniel Wood",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Hyder Amil",
                "method": "KO (Knee and elbows)",
                "round": "1",
                "time": "0:26"
              },
              {
                "r": "W",
                "opp": "Connor Matthews",
                "method": "KO (Punches)",
                "round": "1",
                "time": "2:58"
              },
              {
                "r": "W",
                "opp": "Ernie Juarez",
                "method": "KO (Knee and punches)",
                "round": "2",
                "time": "1:25"
              }
            ]
          }
        }
      },
      {
        "f1": "Jean-Paul Lebosnoyani",
        "f2": "Seokhyeon Ko",
        "s1": "jean-paul-lebosnoyani",
        "s2": "seokhyeon-ko",
        "rec1": "10-2-0",
        "rec2": "13-2-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Welterweight",
        "rounds": 3,
        "o1": "+172",
        "o2": "-208",
        "books": 5,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 2",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'11\"",
            "reach": "72\"",
            "age": 27,
            "stance": "Switch",
            "gym": "UFC Performance Institute",
            "layoff": {
              "txt": "5 mo",
              "mo": 5,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Phil Rowe",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Jack Congdon",
                "method": "KO (Head Kick and Punch)",
                "round": "1",
                "time": "1:08"
              },
              {
                "r": "W",
                "opp": "Kegan Gennrich",
                "method": "Submission (Triangle Choke)",
                "round": "1",
                "time": "4:00"
              },
              {
                "r": "W",
                "opp": "Victor Kuiks",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Adam Wamsley",
                "method": "KO (Punches)",
                "round": "1",
                "time": "3:46"
              }
            ]
          },
          "b": {
            "ht": "5'10\"",
            "reach": "71\"",
            "age": 32,
            "stance": "Southpaw",
            "gym": "HAVAS Seoul",
            "layoff": {
              "txt": "8 mo",
              "mo": 8,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Phil Rowe",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Oban Elliott",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Igor Cavalcanti",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Alwin Kincai",
                "method": "TKO",
                "round": "1",
                "time": "0:58"
              },
              {
                "r": "W",
                "opp": "Ryuta Sakurai",
                "method": "TKO",
                "round": "2",
                "time": "0:56"
              }
            ]
          }
        }
      },
      {
        "f1": "Levi Rodrigues Jr.",
        "f2": "Felipe Franco",
        "s1": "levi-rodrigues",
        "s2": "felipe-franco",
        "rec1": "5-0-0",
        "rec2": "10-2-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Light Heavyweight",
        "rounds": 3,
        "o1": null,
        "o2": null,
        "books": 0,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 3",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'0\"",
            "reach": "76.5\"",
            "age": 29,
            "stance": "Orthodox",
            "gym": "Rasteira Fight Team",
            "layoff": {
              "txt": "9 mo",
              "mo": 9,
              "long": false
            },
            "l5": [
              {
                "r": "NC",
                "opp": "Freddy Vidal",
                "method": "No Contest (Overturned)",
                "round": "1",
                "time": "3:20"
              },
              {
                "r": "W",
                "opp": "Alan Ribeiro",
                "method": "KO (Punches)",
                "round": "1",
                "time": "2:47"
              },
              {
                "r": "W",
                "opp": "Jhonny Pereira",
                "method": "TKO (Shoulder injury)",
                "round": "3",
                "time": "0:21"
              },
              {
                "r": "W",
                "opp": "Jose Carlos Lima",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "1:28"
              },
              {
                "r": "W",
                "opp": "Leonardo Genuino",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "2:32"
              }
            ]
          },
          "b": {
            "ht": "6'1\"",
            "reach": "76\"",
            "age": 25,
            "stance": "Orthodox",
            "gym": "Galpao da Luta",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Mario Pinto",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Douglas Felipe Santos",
                "method": "Submission (Rear-naked choke)",
                "round": "1",
                "time": "4:05"
              },
              {
                "r": "W",
                "opp": "Kleberson Tavares",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "0:32"
              },
              {
                "r": "L",
                "opp": "Freddy Vidal",
                "method": "Submission (Rear-naked choke)",
                "round": "3",
                "time": "4:48"
              },
              {
                "r": "W",
                "opp": "Murilo dos Santos Ferreira",
                "method": "Submission (Arm-triangle choke)",
                "round": "1",
                "time": "1:10"
              }
            ]
          }
        }
      },
      {
        "f1": "Alden Coria",
        "f2": "Stewart Nicoll",
        "s1": "alden-coria",
        "s2": "stewart-nicoll",
        "rec1": "12-3-0",
        "rec2": "8-3-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Flyweight",
        "rounds": 3,
        "o1": "-1095",
        "o2": "+688",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 4",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'8\"",
            "reach": "67\"",
            "age": 28,
            "stance": "Orthodox",
            "gym": "4oz Fight Club, Aztlan Boxing",
            "layoff": {
              "txt": "5 mo",
              "mo": 5,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Luis Gurule",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Alessandro Costa",
                "method": "TKO (Punches)",
                "round": "3",
                "time": "0:47"
              },
              {
                "r": "W",
                "opp": "German Orpineda Ponce",
                "method": "TKO (Elbows)",
                "round": "2",
                "time": "3:21"
              },
              {
                "r": "NC",
                "opp": "Paris Moran",
                "method": "No Contest (Overturned)",
                "round": "1",
                "time": "3:12"
              },
              {
                "r": "W",
                "opp": "Chris Ocon",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "2:22"
              }
            ]
          },
          "b": {
            "ht": "5'5\"",
            "reach": "65.5\"",
            "age": 31,
            "stance": "Orthodox",
            "gym": "Team Compton Training Centre",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Alessandro Costa",
                "method": "TKO (Punch to the body)",
                "round": "2",
                "time": "4:56"
              },
              {
                "r": "L",
                "opp": "Lucas Rocha",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Jesus Aguilar",
                "method": "Technical Submission (Guillotine choke)",
                "round": "1",
                "time": "2:39"
              },
              {
                "r": "W",
                "opp": "Issei Kitano",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "4:45"
              },
              {
                "r": "W",
                "opp": "Dansheel Moodley",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "4:24"
              }
            ]
          }
        }
      },
      {
        "f1": "RJ Harris",
        "f2": "Alvin Hines",
        "s1": "rj-harris",
        "s2": "alvin-hines",
        "rec1": "5-0-0",
        "rec2": "7-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Heavyweight",
        "rounds": 3,
        "o1": "+117",
        "o2": "-142",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 5",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'6\"",
            "reach": "80\"",
            "age": 27,
            "stance": "",
            "gym": "",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Phillip Latu",
                "method": "Submission (Standing Guillotine Choke)",
                "round": "2",
                "time": "4:01"
              },
              {
                "r": "W",
                "opp": "Alex Marro",
                "method": "KO (Left Hook)",
                "round": "1",
                "time": "2:17"
              },
              {
                "r": "W",
                "opp": "Austin Green",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Charlie Cleveland",
                "method": "Submission (Americana)",
                "round": "2",
                "time": "3:07"
              },
              {
                "r": "W",
                "opp": "Quentin Campbell",
                "method": "Submission (Forearm Choke)",
                "round": "1",
                "time": "3:24"
              }
            ]
          },
          "b": {
            "ht": "6'2\"",
            "reach": "74\"",
            "age": 34,
            "stance": "Orthodox",
            "gym": "La Bodega Fight Team",
            "layoff": {
              "txt": "1y 1m",
              "mo": 13,
              "long": true
            },
            "l5": [
              {
                "r": "L",
                "opp": "Jhonata Diniz",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Billy Ray Valdez",
                "method": "KO (Head kick)",
                "round": "3",
                "time": "2:09"
              },
              {
                "r": "W",
                "opp": "J.R. Hicks",
                "method": "Submission (Arm-triangle choke)",
                "round": "1",
                "time": "1:40"
              },
              {
                "r": "W",
                "opp": "Mark Currier",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "1:48"
              },
              {
                "r": "W",
                "opp": "Taylor Escamilla",
                "method": "TKO (Elbows)",
                "round": "2",
                "time": "2:40"
              }
            ]
          }
        }
      },
      {
        "f1": "Anna Melisano",
        "f2": "Dione Barbosa",
        "s1": "",
        "s2": "dione-barbosa",
        "rec1": "6-1-0",
        "rec2": "9-4-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Women's Flyweight",
        "rounds": 3,
        "o1": "+445",
        "o2": "-627",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 6",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'6\"",
            "reach": "70\"",
            "age": 29,
            "stance": "",
            "gym": "SBG Alabama / Spartan Fitness MMA",
            "layoff": {
              "txt": "7 mo",
              "mo": 7,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Andrea Amaro",
                "method": "TKO (Doctor Stoppage)",
                "round": "3",
                "time": "2:56"
              },
              {
                "r": "W",
                "opp": "Lydia Warren",
                "method": "Submission (Rear-Naked Choke)",
                "round": "1",
                "time": "4:17"
              },
              {
                "r": "W",
                "opp": "Blanca Medina",
                "method": "KO (Punch)",
                "round": "1",
                "time": "3:28"
              },
              {
                "r": "W",
                "opp": "Ana Martinez",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Kendal Holowell",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'6\"",
            "reach": "65.5\"",
            "age": 34,
            "stance": "Orthodox",
            "gym": "Kings MMA",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Melissa Gatto",
                "method": "Decision (Majority)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Karine Silva",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Diana Belbita",
                "method": "Submission (Arm-triangle choke)",
                "round": "1",
                "time": "4:13"
              },
              {
                "r": "L",
                "opp": "Miranda Maverick",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Ernesta Kareckaite",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Ezra Elliott",
        "f2": "Damien Anderson",
        "s1": "",
        "s2": "damien-anderson",
        "rec1": "",
        "rec2": "",
        "rank1": "",
        "rank2": "",
        "weight": "Featherweight",
        "rounds": 3,
        "o1": "+131",
        "o2": "-158",
        "books": 3,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 7",
        "main": false,
        "tape": {
          "a": {
            "ht": "",
            "reach": "",
            "age": null,
            "stance": "",
            "gym": "",
            "layoff": null,
            "l5": []
          },
          "b": {
            "ht": "",
            "reach": "",
            "age": null,
            "stance": "",
            "gym": "",
            "layoff": null,
            "l5": []
          }
        }
      }
    ],
    "main": {
      "a": {
        "ht": "6'0\"",
        "reach": "76\"",
        "age": 32,
        "stance": "Orthodox",
        "gym": "Team CIT MMA",
        "layoff": {
          "txt": "11 mo",
          "mo": 11,
          "long": false
        },
        "l5": [
          {
            "r": "L",
            "opp": "Khamzat Chimaev",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Sean Strickland",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Israel Adesanya",
            "method": "Submission (Face crank)",
            "round": "4",
            "time": "3:38"
          },
          {
            "r": "W",
            "opp": "Sean Strickland",
            "method": "Decision (Split)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Robert Whittaker",
            "method": "TKO (Punches)",
            "round": "2",
            "time": "2:23"
          }
        ]
      },
      "b": {
        "ht": "6'0\"",
        "reach": "76\"",
        "age": 39,
        "stance": "Switch",
        "gym": "Kill Cliff FC",
        "layoff": {
          "txt": "1y 1m",
          "mo": 13,
          "long": true
        },
        "l5": [
          {
            "r": "W",
            "opp": "Joaquin Buckley",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "L",
            "opp": "Khamzat Chimaev",
            "method": "Decision (Majority)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "L",
            "opp": "Leon Edwards",
            "method": "Decision (Majority)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "L",
            "opp": "Leon Edwards",
            "method": "KO (Head kick)",
            "round": "5",
            "time": "4:04"
          },
          {
            "r": "W",
            "opp": "Colby Covington",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          }
        ]
      },
      "stats": {
        "a": {
          "ht": "6'0\"",
          "dob": "1994-01-14",
          "reach": "76\"",
          "stance": "Orthodox",
          "slpm": 5.18,
          "strAcc": "49%",
          "sapm": 4.33,
          "strDef": "53%",
          "kd": 0.4,
          "tdLanded": 2.22,
          "tdAcc": "51%",
          "tdDef": "35%",
          "subAvg": 0.71,
          "finRate": "87%",
          "streak": 0,
          "gym": "Team CIT MMA"
        },
        "b": {
          "ht": "6'0\"",
          "dob": "1987-05-11",
          "reach": "76\"",
          "stance": "Switch",
          "slpm": 4.16,
          "strAcc": "52%",
          "sapm": 2.67,
          "strDef": "55%",
          "kd": 0.44,
          "tdLanded": 2.79,
          "tdAcc": "44%",
          "tdDef": "90%",
          "subAvg": 0.09,
          "finRate": "48%",
          "streak": 1,
          "gym": "Kill Cliff FC"
        },
        "sig": {
          "kd": false,
          "strAcc": false,
          "strDef": false,
          "sapm": true,
          "output": false,
          "tdDef": true,
          "tdLanded": false,
          "subAvg": true,
          "finRate": true,
          "slpm": true,
          "tdAcc": false
        }
      },
      "lean": {
        "a": 44,
        "b": 42
      },
      "pace": {
        "a": 10.6,
        "b": 8
      },
      "path": {
        "a": "Comfortable everywhere — his edge is the bigger finishing threat; drag Usman into his stronger area.",
        "b": "Comfortable everywhere — best route is the takedown (Plessis defends only 35%)."
      },
      "story": {
        "a": [
          "Hasn't been finished in his last 12 fights."
        ],
        "b": []
      },
      "finishDur": {
        "finRate": {
          "a": "87% (20/23)",
          "b": "48% (10/21)"
        },
        "methods": {
          "a": "9 KO · 11 SUB · 3 DEC",
          "b": "9 KO · 1 SUB · 11 DEC"
        },
        "timesFinished": {
          "a": "2× (1 KO/TKO, 1 SUB)",
          "b": "2× (1 KO/TKO, 1 SUB)",
          "aCls": "w",
          "bCls": "l"
        }
      },
      "common": [
        {
          "opp": "Khamzat Chimaev",
          "a": "L (DEC R5)",
          "b": "L (DEC R3)",
          "aCls": "l",
          "bCls": "l"
        },
        {
          "opp": "Sean Strickland",
          "a": "2-0 (2 fights)",
          "b": "W (DEC R3)",
          "aCls": "w",
          "bCls": "w"
        }
      ],
      "pA": {
        "name": "Dricus Du Plessis",
        "slug": "dricus-du-plessis",
        "record": "23-3-0",
        "rank": "#2",
        "groups": [
          {
            "t": "Striking",
            "rows": [
              {
                "label": "Sig. strikes landed / min",
                "val": "5.18",
                "cls": "good",
                "w": 84.9,
                "tickX": 65.9,
                "bar": true
              },
              {
                "label": "Striking accuracy",
                "val": "49%",
                "cls": "bad",
                "w": 73.1,
                "tickX": 76.9,
                "bar": true
              },
              {
                "label": "Sig. strikes absorbed / min",
                "val": "4.33",
                "cls": "bad",
                "w": 68.2,
                "tickX": 52.6,
                "bar": true
              },
              {
                "label": "Striking defense",
                "val": "53%",
                "cls": "good",
                "w": 85.5,
                "tickX": 83.9,
                "bar": true
              },
              {
                "label": "Knockdowns / 15 min",
                "val": "0.4",
                "cls": "bad",
                "w": 13.9,
                "tickX": 15.9,
                "bar": true
              }
            ]
          },
          {
            "t": "Grappling",
            "rows": [
              {
                "label": "Takedowns / 15 min",
                "val": "2.22",
                "cls": "good",
                "w": 38.3,
                "tickX": 25.6,
                "bar": true
              },
              {
                "label": "Takedown accuracy",
                "val": "51%",
                "cls": "good",
                "w": 51,
                "tickX": 42,
                "bar": true
              },
              {
                "label": "Takedown defense",
                "val": "35%",
                "cls": "bad",
                "w": 35,
                "tickX": 69,
                "bar": true
              },
              {
                "label": "Submissions / 15 min",
                "val": "0.71",
                "cls": "bad",
                "w": 31.3,
                "tickX": 32.6,
                "bar": true
              }
            ]
          },
          {
            "t": "Miscellaneous",
            "rows": [
              {
                "label": "Finish rate",
                "val": "87%",
                "cls": "good",
                "w": 87,
                "tickX": 79,
                "bar": true
              },
              {
                "label": "Win streak",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          }
        ],
        "bars": true
      },
      "pB": {
        "name": "Kamaru Usman",
        "slug": "kamaru-usman",
        "record": "21-4-0",
        "rank": "#9",
        "groups": [
          {
            "t": "Striking",
            "rows": [
              {
                "label": "Sig. strikes landed / min",
                "val": "4.16",
                "cls": "bad",
                "w": 47.4,
                "tickX": 47.8,
                "bar": true
              },
              {
                "label": "Striking accuracy",
                "val": "52%",
                "cls": "good",
                "w": 83.9,
                "tickX": 79.8,
                "bar": true
              },
              {
                "label": "Sig. strikes absorbed / min",
                "val": "2.67",
                "cls": "good",
                "w": 24.8,
                "tickX": 32.6,
                "bar": true
              },
              {
                "label": "Striking defense",
                "val": "55%",
                "cls": "good",
                "w": 83.3,
                "tickX": 81.8,
                "bar": true
              },
              {
                "label": "Knockdowns / 15 min",
                "val": "0.44",
                "cls": "bad",
                "w": 8.7,
                "tickX": 11.7,
                "bar": true
              }
            ]
          },
          {
            "t": "Grappling",
            "rows": [
              {
                "label": "Takedowns / 15 min",
                "val": "2.79",
                "cls": "good",
                "w": 35.9,
                "tickX": 18.3,
                "bar": true
              },
              {
                "label": "Takedown accuracy",
                "val": "44%",
                "cls": "good",
                "w": 69.8,
                "tickX": 63.5,
                "bar": true
              },
              {
                "label": "Takedown defense",
                "val": "90%",
                "cls": "good",
                "w": 90,
                "tickX": 68,
                "bar": true
              },
              {
                "label": "Submissions / 15 min",
                "val": "0.09",
                "cls": "bad",
                "w": 5.5,
                "tickX": 37.8,
                "bar": true
              }
            ]
          },
          {
            "t": "Miscellaneous",
            "rows": [
              {
                "label": "Finish rate",
                "val": "48%",
                "cls": "bad",
                "w": 48,
                "tickX": 74,
                "bar": true
              },
              {
                "label": "Win streak",
                "val": "1",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          }
        ],
        "bars": true
      }
    }
  }
};
