// AUTO-GENERATED by scripts/gen-landing-data.cjs — do not edit by hand.
export default {
  "generatedAt": "2026-08-10T12:56:30.798Z",
  "rankings": {
    "division": "Bantamweight",
    "rows": [
      {
        "n": "C",
        "name": "Petr Yan",
        "record": "20-5-0",
        "champ": true,
        "slug": "petr-yan",
        "initials": "PY"
      },
      {
        "n": "1",
        "name": "Merab Dvalishvili",
        "record": "21-5-0",
        "champ": false,
        "slug": "merab-dvalishvili",
        "initials": "MD"
      },
      {
        "n": "2",
        "name": "Sean O'Malley",
        "record": "20-3-0",
        "champ": false,
        "slug": "sean-omalley",
        "initials": "SO"
      },
      {
        "n": "3",
        "name": "Umar Nurmagomedov",
        "record": "20-1-0",
        "champ": false,
        "slug": "umar-nurmagomedov",
        "initials": "UN"
      },
      {
        "n": "4",
        "name": "Mario Bautista",
        "record": "18-3-0",
        "champ": false,
        "slug": "mario-bautista",
        "initials": "MB"
      },
      {
        "n": "5",
        "name": "Cory Sandhagen",
        "record": "18-7-0",
        "champ": false,
        "slug": "cory-sandhagen",
        "initials": "CS"
      }
    ]
  },
  "roster": {
    "week": "July 14 – July 31, 2026",
    "added": [
      "Abubakar Vagaev"
    ],
    "addedTotal": 9,
    "removed": [
      "Michel Pereira"
    ],
    "removedTotal": 4,
    "names": [
      "Aaron Pico",
      "Abdul Hussein",
      "Abdul Rakhman Yakhyaev",
      "Abdul-Kareem Al-Selwady",
      "Abe Alsaghir",
      "Abubakar Vagaev",
      "Abus Magomedov",
      "Adrian Yanez",
      "Aiemann Zahabi",
      "Ailin Perez",
      "Alatengheili",
      "Alberto Montes"
    ],
    "total": 663
  },
  "featured": {
    "name": "Islam Makhachev",
    "slug": "islam-makhachev",
    "division": "Welterweight",
    "record": "28-1-0",
    "initials": "IM",
    "bio": [
      [
        "Age",
        34
      ],
      [
        "Height",
        "5'10\""
      ],
      [
        "Reach",
        "70\""
      ],
      [
        "Stance",
        "Southpaw"
      ],
      [
        "Gym",
        "AKA/Eagles"
      ]
    ],
    "groups": [
      {
        "t": "Striking",
        "rows": [
          {
            "label": "Sig. strikes landed / min",
            "val": "2.45",
            "cls": "bad",
            "w": 26.8,
            "tickX": 45.2,
            "bar": true
          },
          {
            "label": "Striking accuracy",
            "val": "58%",
            "cls": "good",
            "w": 93.5,
            "tickX": 79,
            "bar": true
          },
          {
            "label": "Sig. strikes absorbed / min",
            "val": "1.45",
            "cls": "good",
            "w": 13.5,
            "tickX": 32.2,
            "bar": true
          },
          {
            "label": "Striking defense",
            "val": "62%",
            "cls": "good",
            "w": 95.4,
            "tickX": 83.1,
            "bar": true
          },
          {
            "label": "Knockdowns / 15 min",
            "val": "0.3",
            "cls": "bad",
            "w": 4.7,
            "tickX": 9.3,
            "bar": true
          }
        ]
      },
      {
        "t": "Grappling",
        "rows": [
          {
            "label": "Takedowns / 15 min",
            "val": "3.1",
            "cls": "good",
            "w": 39.8,
            "tickX": 18.1,
            "bar": true
          },
          {
            "label": "Takedown accuracy",
            "val": "56%",
            "cls": "good",
            "w": 88.9,
            "tickX": 61.9,
            "bar": true
          },
          {
            "label": "Takedown defense",
            "val": "91%",
            "cls": "good",
            "w": 91,
            "tickX": 67.5,
            "bar": true
          },
          {
            "label": "Submissions / 15 min",
            "val": "0.98",
            "cls": "good",
            "w": 61.2,
            "tickX": 40,
            "bar": true
          }
        ]
      },
      {
        "t": "Miscellaneous",
        "rows": [
          {
            "label": "Finish rate",
            "val": "64%",
            "cls": "bad",
            "w": 64,
            "tickX": 74,
            "bar": true
          },
          {
            "label": "Win streak",
            "val": "16",
            "cls": "",
            "w": 0,
            "tickX": null,
            "bar": false
          }
        ]
      }
    ],
    "hasBars": true
  },
  "oddsHistory": {
    "name": "Max Holloway",
    "slug": "max-holloway",
    "initials": "MH",
    "rows": [
      {
        "opponent": "Conor McGregor",
        "odds": -324
      },
      {
        "opponent": "Charles Oliveira",
        "odds": -208
      },
      {
        "opponent": "Dustin Poirier",
        "odds": -116
      },
      {
        "opponent": "Ilia Topuria",
        "odds": 228
      },
      {
        "opponent": "Justin Gaethje",
        "odds": 143
      },
      {
        "opponent": "Jung Chan-sung",
        "odds": -750
      },
      {
        "opponent": "Arnold Allen",
        "odds": -170
      }
    ]
  },
  "matchup": null,
  "parlay": {
    "event": "UFC Fight Night",
    "kind": "moneyline",
    "book": "Consensus · 2 books",
    "legs": [
      {
        "pick": "Anthony Wint",
        "slug": "anthony-wint",
        "opponent": "Matt Adams",
        "label": "to win",
        "odds": "-850"
      },
      {
        "pick": "Fabrizio Escarrega",
        "slug": "fabrizio-escarrega",
        "opponent": "Abe Alsaghir",
        "label": "to win",
        "odds": "-146"
      },
      {
        "pick": "Bilal Hasan",
        "slug": "bilal-hasan",
        "opponent": "Mridul Saikia",
        "label": "to win",
        "odds": "-1895"
      }
    ],
    "combined": "-102",
    "stake": 100,
    "payout": 198
  },
  "styleDemo": null,
  "counts": {
    "fighters": 3123,
    "bouts": 29414,
    "historyRows": 58827,
    "videos": 18043,
    "photos": 2349
  },
  "photos": [
    "islam-makhachev",
    "max-holloway",
    "anthony-wint",
    "fabrizio-escarrega",
    "bilal-hasan",
    "petr-yan",
    "merab-dvalishvili",
    "sean-omalley",
    "umar-nurmagomedov",
    "mario-bautista",
    "cory-sandhagen"
  ],
  "card": {
    "event": "UFC Fight Night",
    "slug": "ufc-fight-night-august-11-2026",
    "date": "2026-08-11",
    "prelimsAt": "2026-08-11T23:00:00.000Z",
    "location": "Meta APEX, Las Vegas, NV",
    "city": "Las Vegas",
    "fights": [
      {
        "f1": "Anthony Wint",
        "f2": "Matt Adams",
        "s1": "",
        "s2": "matt-adams",
        "rec1": "6-0-0",
        "rec2": "",
        "rank1": "NR",
        "rank2": "",
        "weight": "Heavyweight",
        "rounds": 3,
        "o1": "-850",
        "o2": "+492",
        "books": 2,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 1",
        "main": true,
        "tape": {
          "a": {
            "ht": "6'0\"",
            "reach": "",
            "age": 30,
            "stance": "",
            "gym": "Kill Cliff FC",
            "layoff": {
              "txt": "5 mo",
              "mo": 5,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Jamahl Tatum",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "0:37"
              },
              {
                "r": "W",
                "opp": "Miles Banks",
                "method": "KO (Punches)",
                "round": "1",
                "time": "0:21"
              },
              {
                "r": "W",
                "opp": "Emmanuel Verdier",
                "method": "TKO (Punches)",
                "round": "3",
                "time": "4:02"
              },
              {
                "r": "W",
                "opp": "Omar El-Sahlah",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Jawaski Bethly",
                "method": "Submission (Rear-Naked Choke)",
                "round": "1",
                "time": "0:43"
              }
            ]
          },
          "b": {
            "ht": "",
            "reach": "",
            "age": null,
            "stance": "",
            "gym": "",
            "layoff": null,
            "l5": []
          }
        }
      },
      {
        "f1": "Fabrizio Escarrega",
        "f2": "Abe Alsaghir",
        "s1": "",
        "s2": "",
        "rec1": "9-1-0",
        "rec2": "8-0-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Lightweight",
        "rounds": 3,
        "o1": "-146",
        "o2": "+110",
        "books": 2,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 2",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'1\"",
            "reach": "",
            "age": 28,
            "stance": "",
            "gym": "Victory Fight Club",
            "layoff": {
              "txt": "5 mo",
              "mo": 5,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Adriano Nunes",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "0:44"
              },
              {
                "r": "W",
                "opp": "Roman Cordova",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "3:07"
              },
              {
                "r": "W",
                "opp": "Leonel Rojas",
                "method": "Submission (Rear-Naked Choke)",
                "round": "2",
                "time": "3:07"
              },
              {
                "r": "L",
                "opp": "Carlos Arana",
                "method": "TKO (Arm Injury)",
                "round": "1",
                "time": "1:34"
              },
              {
                "r": "W",
                "opp": "Erick Daniel Batista",
                "method": "TKO (Punches and Elbows)",
                "round": "2",
                "time": "2:26"
              }
            ]
          },
          "b": {
            "ht": "5'9\"",
            "reach": "72\"",
            "age": 25,
            "stance": "",
            "gym": "UFC Gym Morocco",
            "layoff": {
              "txt": "11 mo",
              "mo": 11,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Juan Porto",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "2:54"
              },
              {
                "r": "W",
                "opp": "Drew Fickett",
                "method": "Submission (Rear-Naked Choke)",
                "round": "2",
                "time": "2:44"
              },
              {
                "r": "W",
                "opp": "Erik Vo",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "2:03"
              },
              {
                "r": "W",
                "opp": "Jimmy Sandlin",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "4:18"
              },
              {
                "r": "W",
                "opp": "Jerome Featherstone",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Bilal Hasan",
        "f2": "Mridul Saikia",
        "s1": "",
        "s2": "",
        "rec1": "8-0-0",
        "rec2": "9-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Flyweight",
        "rounds": 3,
        "o1": "-1895",
        "o2": "+781",
        "books": 2,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 3",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'7\"",
            "reach": "71\"",
            "age": 25,
            "stance": "",
            "gym": "Charlie's Combat Club",
            "layoff": {
              "txt": "8 mo",
              "mo": 8,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Renaldy Manse",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "2:47"
              },
              {
                "r": "W",
                "opp": "Jason Eastman",
                "method": "TKO (Front Kick to the Body and Punches)",
                "round": "4",
                "time": "1:46"
              },
              {
                "r": "W",
                "opp": "Brian Hauser",
                "method": "KO (Punch to the Body)",
                "round": "2",
                "time": ""
              },
              {
                "r": "W",
                "opp": "Jose Leon",
                "method": "Submission (Rear-Naked Choke)",
                "round": "2",
                "time": ""
              },
              {
                "r": "W",
                "opp": "Shamel Findley",
                "method": "KO (Punches)",
                "round": "1",
                "time": ""
              }
            ]
          },
          "b": {
            "ht": "5'7\"",
            "reach": "68.5\"",
            "age": 29,
            "stance": "",
            "gym": "Bidang MMA & Fitness",
            "layoff": {
              "txt": "7 mo",
              "mo": 7,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Maharram Ahmadov",
                "method": "KO (Head Kick)",
                "round": "1",
                "time": "0:19"
              },
              {
                "r": "L",
                "opp": "Agulali",
                "method": "KO (Punch)",
                "round": "1",
                "time": "0:37"
              },
              {
                "r": "W",
                "opp": "Himanshu Kaushik",
                "method": "Submission (Guillotine Choke)",
                "round": "3",
                "time": "2:17"
              },
              {
                "r": "W",
                "opp": "Vagif Abdullaev",
                "method": "TKO (Leg Kicks)",
                "round": "3",
                "time": ""
              },
              {
                "r": "W",
                "opp": "Karan Nitin Chauhan",
                "method": "Submission (Triangle Choke)",
                "round": "1",
                "time": ""
              }
            ]
          }
        }
      },
      {
        "f1": "Tom Pagliarulo",
        "f2": "Ananias Mulumba",
        "s1": "",
        "s2": "ananias-mulumba",
        "rec1": "10-2-0",
        "rec2": "10-3-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Featherweight",
        "rounds": 3,
        "o1": "+114",
        "o2": "-148",
        "books": 2,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 4",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'0\"",
            "reach": "",
            "age": 29,
            "stance": "",
            "gym": "New England Cartel",
            "layoff": {
              "txt": "1y 0m",
              "mo": 12,
              "long": true
            },
            "l5": [
              {
                "r": "W",
                "opp": "Matt Turnbull",
                "method": "TKO (Knee to the Body and Punches)",
                "round": "1",
                "time": "4:36"
              },
              {
                "r": "W",
                "opp": "Elijah Harris",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "1:35"
              },
              {
                "r": "W",
                "opp": "Don Shainis",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "1:49"
              },
              {
                "r": "W",
                "opp": "Cody Jenkins",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "1:00"
              },
              {
                "r": "L",
                "opp": "Olivier Murad",
                "method": "Submission (Armbar)",
                "round": "3",
                "time": "1:43"
              }
            ]
          },
          "b": {
            "ht": "5'5\"",
            "reach": "70.5\"",
            "age": 27,
            "stance": "Switch",
            "gym": "Elite Training Centre",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Ahmed Faress",
                "method": "TKO (Punch)",
                "round": "1",
                "time": "4:09"
              },
              {
                "r": "L",
                "opp": "Marwan Rahiki",
                "method": "KO/TKO",
                "round": "2",
                "time": "2:13"
              },
              {
                "r": "W",
                "opp": "Amer El Shanshory",
                "method": "Submission (Rear Naked Choke)",
                "round": "2",
                "time": "1:13"
              },
              {
                "r": "W",
                "opp": "Jackiel Ayana",
                "method": "TKO",
                "round": "2",
                "time": "2:50"
              },
              {
                "r": "W",
                "opp": "Jonathan Lamptey",
                "method": "TKO",
                "round": "1",
                "time": "1:52"
              }
            ]
          }
        }
      },
      {
        "f1": "Jon Kunneman",
        "f2": "Joe Kropschot",
        "s1": "",
        "s2": "",
        "rec1": "10-0-0",
        "rec2": "",
        "rank1": "NR",
        "rank2": "",
        "weight": "Middleweight",
        "rounds": 3,
        "o1": "-282",
        "o2": "+204",
        "books": 2,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 5",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'0\"",
            "reach": "77\"",
            "age": 27,
            "stance": "",
            "gym": "Elevation Fight Team",
            "layoff": {
              "txt": "1y 5m",
              "mo": 17,
              "long": true
            },
            "l5": [
              {
                "r": "W",
                "opp": "Matt Friesen",
                "method": "Submission (Arm-Triangle Choke)",
                "round": "1",
                "time": "2:46"
              },
              {
                "r": "W",
                "opp": "Skyler Mauller",
                "method": "Submission (Arm-Triangle Choke)",
                "round": "1",
                "time": "2:16"
              },
              {
                "r": "W",
                "opp": "Charlie Kennedy",
                "method": "Submission (Brabo Choke)",
                "round": "1",
                "time": "1:24"
              },
              {
                "r": "W",
                "opp": "Brandon Fagan",
                "method": "TKO",
                "round": "1",
                "time": "0:09"
              },
              {
                "r": "W",
                "opp": "Tristyn DeHart",
                "method": "TKO (Strikes)",
                "round": "1",
                "time": "0:45"
              }
            ]
          },
          "b": {
            "ht": "",
            "reach": "",
            "age": null,
            "stance": "",
            "gym": "",
            "layoff": null,
            "l5": []
          }
        }
      }
    ],
    "main": {
      "a": {
        "ht": "6'0\"",
        "reach": "",
        "age": 30,
        "stance": "",
        "gym": "Kill Cliff FC",
        "layoff": {
          "txt": "5 mo",
          "mo": 5,
          "long": false
        },
        "l5": [
          {
            "r": "W",
            "opp": "Jamahl Tatum",
            "method": "TKO (Punches)",
            "round": "1",
            "time": "0:37"
          },
          {
            "r": "W",
            "opp": "Miles Banks",
            "method": "KO (Punches)",
            "round": "1",
            "time": "0:21"
          },
          {
            "r": "W",
            "opp": "Emmanuel Verdier",
            "method": "TKO (Punches)",
            "round": "3",
            "time": "4:02"
          },
          {
            "r": "W",
            "opp": "Omar El-Sahlah",
            "method": "Decision (Split)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Jawaski Bethly",
            "method": "Submission (Rear-Naked Choke)",
            "round": "1",
            "time": "0:43"
          }
        ]
      },
      "b": {
        "ht": "",
        "reach": "",
        "age": null,
        "stance": "",
        "gym": "",
        "layoff": null,
        "l5": []
      },
      "stats": {
        "a": {},
        "b": {},
        "sig": {}
      },
      "lean": {},
      "pace": {},
      "path": {},
      "story": {
        "a": [],
        "b": []
      },
      "finishDur": {
        "finRate": {
          "a": "83% (5/6)",
          "b": "—"
        },
        "methods": {
          "a": "4 KO · 1 SUB · 1 DEC",
          "b": "—"
        },
        "timesFinished": {
          "a": "Never",
          "b": "—",
          "aCls": "",
          "bCls": ""
        }
      },
      "common": [],
      "pA": {
        "name": "Anthony Wint",
        "slug": "",
        "record": "6-0-0",
        "rank": "NR",
        "groups": [
          {
            "t": "Striking",
            "rows": [
              {
                "label": "Sig. strikes landed / min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Striking accuracy",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Sig. strikes absorbed / min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Striking defense",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Knockdowns / 15 min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          },
          {
            "t": "Grappling",
            "rows": [
              {
                "label": "Takedowns / 15 min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Takedown accuracy",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Takedown defense",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Submissions / 15 min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          },
          {
            "t": "Miscellaneous",
            "rows": [
              {
                "label": "Finish rate",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Win streak",
                "val": "6",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          }
        ],
        "bars": false
      },
      "pB": {
        "name": "Matt Adams",
        "slug": "matt-adams",
        "record": "",
        "rank": "",
        "groups": [
          {
            "t": "Striking",
            "rows": [
              {
                "label": "Sig. strikes landed / min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Striking accuracy",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Sig. strikes absorbed / min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Striking defense",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Knockdowns / 15 min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          },
          {
            "t": "Grappling",
            "rows": [
              {
                "label": "Takedowns / 15 min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Takedown accuracy",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Takedown defense",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Submissions / 15 min",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          },
          {
            "t": "Miscellaneous",
            "rows": [
              {
                "label": "Finish rate",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              },
              {
                "label": "Win streak",
                "val": "—",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          }
        ],
        "bars": false
      }
    }
  },
  "held": {
    "startsAt": "2026-08-09T00:00:00.000Z",
    "card": {
      "event": "UFC Fight Night",
      "slug": "ufc-fight-night-august-08-2026",
      "date": "2026-08-09",
      "prelimsAt": "2026-08-08T21:00:00.000Z",
      "location": "Meta APEX, Las Vegas, NV",
      "city": "Las Vegas",
      "fights": [
        {
          "f1": "Mateusz Gamrot",
          "f2": "Quillan Salkilld",
          "s1": "mateusz-gamrot",
          "s2": "quillan-salkilld",
          "rec1": "26-5-0",
          "rec2": "13-1-0",
          "rank1": "#8",
          "rank2": "#12",
          "weight": "Lightweight",
          "rounds": 5,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 1",
          "main": true,
          "tape": {
            "a": {
              "ht": "5'10\"",
              "reach": "70.5\"",
              "age": 35,
              "stance": "Southpaw",
              "gym": "American Top Team",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Quillan Salkilld",
                  "method": "Submission (Rear Naked Choke)",
                  "round": "1",
                  "time": "4:25"
                },
                {
                  "r": "W",
                  "opp": "Esteban Ribovics",
                  "method": "Submission (Arm-triangle choke)",
                  "round": "2",
                  "time": "4:19"
                },
                {
                  "r": "L",
                  "opp": "Charles Oliveira",
                  "method": "Submission (Face crank)",
                  "round": "2",
                  "time": "2:48"
                },
                {
                  "r": "W",
                  "opp": "Ľudovít Klein",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Dan Hooker",
                  "method": "Decision (Split)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "6'0\"",
              "reach": "75\"",
              "age": 26,
              "stance": "Orthodox",
              "gym": "Luistro Combat Academy",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Mateusz Gamrot",
                  "method": "Submission (Rear Naked Choke)",
                  "round": "1",
                  "time": "4:25"
                },
                {
                  "r": "W",
                  "opp": "Beneil Dariush",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "3:29"
                },
                {
                  "r": "W",
                  "opp": "Jamie Mullarkey",
                  "method": "Submission (Neck crank)",
                  "round": "1",
                  "time": "3:02"
                },
                {
                  "r": "W",
                  "opp": "Nasrat Haqparast",
                  "method": "KO (Head kick)",
                  "round": "1",
                  "time": "2:30"
                },
                {
                  "r": "W",
                  "opp": "Yanal Ashmouz",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Diego Ferreira",
          "f2": "Billy Quarantillo",
          "s1": "diego-ferreira",
          "s2": "billy-quarantillo",
          "rec1": "20-7-0",
          "rec2": "18-8-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Lightweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 2",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'9\"",
              "reach": "74\"",
              "age": 41,
              "stance": "Orthodox",
              "gym": "Fortis MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Billy Quarantillo",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Alexander Hernandez",
                  "method": "TKO (Punches)",
                  "round": "2",
                  "time": "3:46"
                },
                {
                  "r": "L",
                  "opp": "Grant Dawson",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Mateusz Rębecki",
                  "method": "TKO (Punches)",
                  "round": "3",
                  "time": "4:51"
                },
                {
                  "r": "W",
                  "opp": "Michael Johnson",
                  "method": "KO (Punch)",
                  "round": "2",
                  "time": "1:50"
                }
              ]
            },
            "b": {
              "ht": "5'10\"",
              "reach": "70\"",
              "age": 37,
              "stance": "Orthodox",
              "gym": "Gracie Tampa South",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Diego Ferreira",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Cub Swanson",
                  "method": "KO (Punch)",
                  "round": "3",
                  "time": "1:36"
                },
                {
                  "r": "L",
                  "opp": "Youssef Zalal",
                  "method": "Submission (Rear-naked choke)",
                  "round": "2",
                  "time": "1:50"
                },
                {
                  "r": "W",
                  "opp": "Damon Jackson",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Edson Barboza",
                  "method": "KO (Knee)",
                  "round": "1",
                  "time": "2:37"
                }
              ]
            }
          }
        },
        {
          "f1": "Darren Elkins",
          "f2": "Yadier del Valle",
          "s1": "darren-elkins",
          "s2": "yadier-del-valle",
          "rec1": "29-13-0",
          "rec2": "11-1-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Featherweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 3",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'10\"",
              "reach": "71\"",
              "age": 42,
              "stance": "Orthodox",
              "gym": "Team Alpha Male (Urijah Faber's Ultimate Fitness)",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Yadier del Valle",
                  "method": "KO/TKO (Punch)",
                  "round": "1",
                  "time": "0:35"
                },
                {
                  "r": "L",
                  "opp": "Julian Erosa",
                  "method": "TKO (Elbow and punches)",
                  "round": "1",
                  "time": "4:15"
                },
                {
                  "r": "W",
                  "opp": "Daniel Pineda",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "T.J. Brown",
                  "method": "Submission (Rear-naked choke)",
                  "round": "3",
                  "time": "2:23"
                },
                {
                  "r": "L",
                  "opp": "Jonathan Pearce",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "5'9\"",
              "reach": "69\"",
              "age": 30,
              "stance": "Southpaw",
              "gym": "Main Street Boxing and Muay Thai",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Darren Elkins",
                  "method": "KO/TKO (Punch)",
                  "round": "1",
                  "time": "0:35"
                },
                {
                  "r": "L",
                  "opp": "Jordan Leavitt",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Isaac Dulgarian",
                  "method": "Submission",
                  "round": "1",
                  "time": "3:41"
                },
                {
                  "r": "W",
                  "opp": "Connor Matthews",
                  "method": "Submission",
                  "round": "1",
                  "time": "2:54"
                },
                {
                  "r": "W",
                  "opp": "Antonio Monteiro",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Amanda Lemos",
          "f2": "Alexia Thainara",
          "s1": "amanda-lemos",
          "s2": "alexia-thainara",
          "rec1": "15-7-1",
          "rec2": "15-1-0",
          "rank1": "#8",
          "rank2": "#12",
          "weight": "Women's Strawweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 4",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'4\"",
              "reach": "65\"",
              "age": 39,
              "stance": "Southpaw",
              "gym": "Marajó Brothers Team",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Alexia Thainara",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Gillian Robertson",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Tatiana Suarez",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Iasmin Lucindo",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Virna Jandiroba",
                  "method": "Submission (Armbar)",
                  "round": "2",
                  "time": "4:48"
                }
              ]
            },
            "b": {
              "ht": "5'4\"",
              "reach": "67\"",
              "age": 30,
              "stance": "Orthodox",
              "gym": "Academia Ribas Family / Team LJ Combat",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Amanda Lemos",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Bruna Brasil",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Loma Lookboonmee",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Molly McCann",
                  "method": "Submission (Rear-naked choke)",
                  "round": "1",
                  "time": "4:32"
                },
                {
                  "r": "W",
                  "opp": "Rose Conceição",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Billy Ray Goff",
          "f2": "Ty Miller",
          "s1": "billy-ray-goff",
          "s2": "ty-miller",
          "rec1": "9-5-0",
          "rec2": "8-0-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Welterweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 5",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'10\"",
              "reach": "72\"",
              "age": 28,
              "stance": "Switch",
              "gym": "Team Dexter Vale Tudo",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Ty Miller",
                  "method": "KO/TKO (Punches)",
                  "round": "3",
                  "time": "0:15"
                },
                {
                  "r": "L",
                  "opp": "Ramiz Brahimaj",
                  "method": "Submission (Guillotine choke)",
                  "round": "1",
                  "time": "3:16"
                },
                {
                  "r": "L",
                  "opp": "Trey Waters",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Yusaku Kinoshita",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "3:49"
                },
                {
                  "r": "W",
                  "opp": "Shimon Smotritsky",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "3:37"
                }
              ]
            },
            "b": {
              "ht": "6'2\"",
              "reach": "77\"",
              "age": 26,
              "stance": "Orthodox",
              "gym": "Fit NHB",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Billy Ray Goff",
                  "method": "KO/TKO (Punches)",
                  "round": "3",
                  "time": "0:15"
                },
                {
                  "r": "W",
                  "opp": "Adam Fugitt",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "4:59"
                },
                {
                  "r": "W",
                  "opp": "Jimmy Drago",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "NC",
                  "opp": "Arthur de Barros Vieira Rocha",
                  "method": "No Contest (Accidental Eye Poke)",
                  "round": "1",
                  "time": "3:30"
                },
                {
                  "r": "W",
                  "opp": "Ryan Charlebois",
                  "method": "TKO",
                  "round": "1",
                  "time": "0:45"
                }
              ]
            }
          }
        },
        {
          "f1": "Steven Asplund",
          "f2": "Guilherme Pat",
          "s1": "steven-asplund",
          "s2": "guilherme-pat",
          "rec1": "8-2-0",
          "rec2": "6-2-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Heavyweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 1",
          "main": false,
          "tape": {
            "a": {
              "ht": "6'5\"",
              "reach": "78\"",
              "age": 28,
              "stance": "Orthodox",
              "gym": "Minnesota Top Team",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Guilherme Pat",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Vitor Petrino",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Sean Sharaf",
                  "method": "TKO (Punches)",
                  "round": "2",
                  "time": "3:49"
                },
                {
                  "r": "W",
                  "opp": "Anthony Guarascio",
                  "method": "TKO (Punch and elbows)",
                  "round": "1",
                  "time": "0:16"
                },
                {
                  "r": "W",
                  "opp": "Raiden Kovacs",
                  "method": "TKO (Elbow and punches)",
                  "round": "2",
                  "time": "1:53"
                }
              ]
            },
            "b": {
              "ht": "6'6\"",
              "reach": "81\"",
              "age": 32,
              "stance": "Orthodox",
              "gym": "Lotus MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Steven Asplund",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Thomas Petersen",
                  "method": "Decision (Majority)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Allen Frye Jr.",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Mauricio Queiroz",
                  "method": "TKO (Punches)",
                  "round": "3",
                  "time": "3:13"
                },
                {
                  "r": "W",
                  "opp": "Leandro Moreira de Oliveira",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Diyar Nurgozhay",
          "f2": "Bruno Lopes",
          "s1": "diyar-nurgozhay",
          "s2": "bruno-lopes",
          "rec1": "12-2-0",
          "rec2": "14-4-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Light Heavyweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 2",
          "main": false,
          "tape": {
            "a": {
              "ht": "6'2\"",
              "reach": "74\"",
              "age": 29,
              "stance": "Southpaw",
              "gym": "Tobet Top Team",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Bruno Lopes",
                  "method": "KO/TKO (Punches)",
                  "round": "1",
                  "time": "4:59"
                },
                {
                  "r": "W",
                  "opp": "Rafael Tobias",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Uran Satybaldiev",
                  "method": "Submission (Ezekiel choke)",
                  "round": "1",
                  "time": "2:45"
                },
                {
                  "r": "L",
                  "opp": "Brendson Ribeiro",
                  "method": "Submission (Kimura)",
                  "round": "2",
                  "time": "1:28"
                },
                {
                  "r": "W",
                  "opp": "Bartosz Szewczyk",
                  "method": "KO (Head kick)",
                  "round": "2",
                  "time": "3:32"
                }
              ]
            },
            "b": {
              "ht": "6'2\"",
              "reach": "74.5\"",
              "age": 33,
              "stance": "Orthodox",
              "gym": "China Team",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Diyar Nurgozhay",
                  "method": "KO/TKO (Punches)",
                  "round": "1",
                  "time": "4:59"
                },
                {
                  "r": "L",
                  "opp": "Navajo Stirling",
                  "method": "TKO (Punches)",
                  "round": "2",
                  "time": "4:05"
                },
                {
                  "r": "L",
                  "opp": "Dustin Jacoby",
                  "method": "KO (Punches)",
                  "round": "1",
                  "time": "1:50"
                },
                {
                  "r": "W",
                  "opp": "Magomed Gadzhiyasulov",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Mikheil Sazhiniani",
                  "method": "TKO (Punches)",
                  "round": "2",
                  "time": "4:14"
                }
              ]
            }
          }
        },
        {
          "f1": "Louie Sutherland",
          "f2": "José Montanha",
          "s1": "louie-sutherland",
          "s2": "jose-montanha",
          "rec1": "11-6-0",
          "rec2": "",
          "rank1": "NR",
          "rank2": "",
          "weight": "Heavyweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 3",
          "main": false,
          "tape": {
            "a": {
              "ht": "6'3\"",
              "reach": "76\"",
              "age": 32,
              "stance": "Orthodox",
              "gym": "Fightzone & Durrant's Gym",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "José Montanha",
                  "method": "Submission (Neck Crank)",
                  "round": "1",
                  "time": "1:50"
                },
                {
                  "r": "W",
                  "opp": "Tai Tuivasa",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Brando Peričić",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "1:48"
                },
                {
                  "r": "L",
                  "opp": "Valter Walker",
                  "method": "Submission (Heel Hook)",
                  "round": "1",
                  "time": "1:24"
                },
                {
                  "r": "W",
                  "opp": "Luke Newland",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "2:50"
                }
              ]
            },
            "b": {
              "ht": "",
              "reach": "",
              "age": null,
              "stance": "",
              "gym": "",
              "layoff": {
                "txt": "11 mo",
                "mo": 11,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Bruno de Jesus",
                  "method": "Submission (Rear-naked choke)",
                  "round": "1",
                  "time": "2:29"
                },
                {
                  "r": "W",
                  "opp": "Jhon Ribeiro",
                  "method": "Submission (Rear-naked choke)",
                  "round": "1",
                  "time": "3:30"
                },
                {
                  "r": "W",
                  "opp": "Carlos Amaral Jr.",
                  "method": "Submission (Arm-triangle choke)",
                  "round": "1",
                  "time": "2:30"
                },
                {
                  "r": "L",
                  "opp": "Richard Jacobi",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Sidney Araujo",
                  "method": "Submission (Rear-naked choke)",
                  "round": "2",
                  "time": "1:38"
                }
              ]
            }
          }
        },
        {
          "f1": "Manoel Sousa",
          "f2": "Richie Miranda",
          "s1": "manoel-sousa",
          "s2": "richie-miranda",
          "rec1": "15-1-0",
          "rec2": "13-2-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Lightweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 4",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'9\"",
              "reach": "70\"",
              "age": 29,
              "stance": "Orthodox",
              "gym": "Academia Octógono",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Richie Miranda",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Bolaji Oki",
                  "method": "KO (Punch)",
                  "round": "3",
                  "time": "4:12"
                },
                {
                  "r": "W",
                  "opp": "Cristian Perez",
                  "method": "TKO (Punches)",
                  "round": "3",
                  "time": "3:00"
                },
                {
                  "r": "W",
                  "opp": "Lucas Barros Oliveira",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Archie Colgan",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "5'9\"",
              "reach": "74\"",
              "age": 31,
              "stance": "",
              "gym": "Bloodline Combat Sports",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Manoel Sousa",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Robert Varricchio",
                  "method": "Submission (Bulldog Choke)",
                  "round": "2",
                  "time": "1:02"
                },
                {
                  "r": "W",
                  "opp": "Ilay Barzilay",
                  "method": "Decision (Unanimous)",
                  "round": "5",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Richie Lewis",
                  "method": "TKO (Elbows and Punches)",
                  "round": "5",
                  "time": "2:04"
                },
                {
                  "r": "W",
                  "opp": "Hugo Oyarzun",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Miles Johns",
          "f2": "Gianni Vazquez",
          "s1": "miles-johns",
          "s2": "gianni-vazquez",
          "rec1": "16-5-0",
          "rec2": "13-6-1",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Featherweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 5",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'7\"",
              "reach": "68\"",
              "age": 32,
              "stance": "Orthodox",
              "gym": "Marathon MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Gianni Vazquez",
                  "method": "KO/TKO (Punch)",
                  "round": "1",
                  "time": "3:09"
                },
                {
                  "r": "L",
                  "opp": "Daniel Marcos",
                  "method": "Technical Submission (Rear-naked choke)",
                  "round": "2",
                  "time": "4:23"
                },
                {
                  "r": "L",
                  "opp": "Jean Matsumoto",
                  "method": "Decision (Split)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Felipe Lima",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Douglas Silva de Andrade",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "5'7\"",
              "reach": "71\"",
              "age": 32,
              "stance": "Orthodox",
              "gym": "Calmecac Team",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Miles Johns",
                  "method": "KO/TKO (Punch)",
                  "round": "1",
                  "time": "3:09"
                },
                {
                  "r": "L",
                  "opp": "Javid Basharat",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Narek Avagyan",
                  "method": "KO/TKO",
                  "round": "2",
                  "time": "2:56"
                },
                {
                  "r": "W",
                  "opp": "Austin Russell",
                  "method": "Submission (Anaconda Choke)",
                  "round": "2",
                  "time": "1:33"
                },
                {
                  "r": "W",
                  "opp": "Victor Rosas",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Juliana Miller",
          "f2": "Ravena Oliveira",
          "s1": "juliana-miller",
          "s2": "ravena-oliveira",
          "rec1": "6-4-0",
          "rec2": "7-5-1",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Women's Flyweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 6",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'7\"",
              "reach": "66\"",
              "age": 30,
              "stance": "Orthodox",
              "gym": "10th Planet Jiu-Jitsu",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Ravena Oliveira",
                  "method": "Submission (Rear Naked Choke)",
                  "round": "2",
                  "time": "1:38"
                },
                {
                  "r": "L",
                  "opp": "Carli Judice",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Ivana Petrovic",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Luana Santos",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "3:41"
                },
                {
                  "r": "L",
                  "opp": "Veronica Hardy",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "5'5\"",
              "reach": "65\"",
              "age": 29,
              "stance": "Orthodox",
              "gym": "Life MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Juliana Miller",
                  "method": "Submission (Rear Naked Choke)",
                  "round": "2",
                  "time": "1:38"
                },
                {
                  "r": "L",
                  "opp": "Shanelle Dyer",
                  "method": "TKO (Punches)",
                  "round": "2",
                  "time": "1:17"
                },
                {
                  "r": "L",
                  "opp": "Stephanie Luciano",
                  "method": "Submission (Rear-Naked Choke)",
                  "round": "3",
                  "time": "2:50"
                },
                {
                  "r": "L",
                  "opp": "Tainara Lisboa",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Simone da Silva",
                  "method": "TKO",
                  "round": "3",
                  "time": "4:16"
                }
              ]
            }
          }
        },
        {
          "f1": "Gigi Canuto",
          "f2": "Carol Foro",
          "s1": "gigi-canuto",
          "s2": "carol-foro",
          "rec1": "7-2-0",
          "rec2": "10-1-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Women's Strawweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Prelims",
          "pos": "Prelims 7",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'2\"",
              "reach": "64\"",
              "age": 23,
              "stance": "Orthodox",
              "gym": "Bangtao Muay Thai and MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Carol Foro",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Janaina Silva",
                  "method": "Submission (Face Crank)",
                  "round": "3",
                  "time": "2:38"
                },
                {
                  "r": "W",
                  "opp": "Flor Hernandez",
                  "method": "Submission (Armbar)",
                  "round": "1",
                  "time": "1:49"
                },
                {
                  "r": "W",
                  "opp": "Ershirley Kessy Pereira",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "4:03"
                },
                {
                  "r": "L",
                  "opp": "Natalia Kuziutina",
                  "method": "Decision (Unanimous)",
                  "round": "5",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "5'2\"",
              "reach": "61.5\"",
              "age": 29,
              "stance": "Orthodox",
              "gym": "RPlay Thai",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Gigi Canuto",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Shanelle Dyer",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Sofia Esquer",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "1:30"
                },
                {
                  "r": "W",
                  "opp": "Zulfiya Kurbashova",
                  "method": "TKO (Punches)",
                  "round": "2",
                  "time": "3:30"
                },
                {
                  "r": "W",
                  "opp": "Dayane Mestrinha",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "2:16"
                }
              ]
            }
          }
        }
      ],
      "main": {
        "a": {
          "ht": "5'10\"",
          "reach": "70.5\"",
          "age": 35,
          "stance": "Southpaw",
          "gym": "American Top Team",
          "layoff": {
            "txt": "0 mo",
            "mo": 0,
            "long": false
          },
          "l5": [
            {
              "r": "L",
              "opp": "Quillan Salkilld",
              "method": "Submission (Rear Naked Choke)",
              "round": "1",
              "time": "4:25"
            },
            {
              "r": "W",
              "opp": "Esteban Ribovics",
              "method": "Submission (Arm-triangle choke)",
              "round": "2",
              "time": "4:19"
            },
            {
              "r": "L",
              "opp": "Charles Oliveira",
              "method": "Submission (Face crank)",
              "round": "2",
              "time": "2:48"
            },
            {
              "r": "W",
              "opp": "Ľudovít Klein",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            },
            {
              "r": "L",
              "opp": "Dan Hooker",
              "method": "Decision (Split)",
              "round": "3",
              "time": "5:00"
            }
          ]
        },
        "b": {
          "ht": "6'0\"",
          "reach": "75\"",
          "age": 26,
          "stance": "Orthodox",
          "gym": "Luistro Combat Academy",
          "layoff": {
            "txt": "0 mo",
            "mo": 0,
            "long": false
          },
          "l5": [
            {
              "r": "W",
              "opp": "Mateusz Gamrot",
              "method": "Submission (Rear Naked Choke)",
              "round": "1",
              "time": "4:25"
            },
            {
              "r": "W",
              "opp": "Beneil Dariush",
              "method": "TKO (Punches)",
              "round": "1",
              "time": "3:29"
            },
            {
              "r": "W",
              "opp": "Jamie Mullarkey",
              "method": "Submission (Neck crank)",
              "round": "1",
              "time": "3:02"
            },
            {
              "r": "W",
              "opp": "Nasrat Haqparast",
              "method": "KO (Head kick)",
              "round": "1",
              "time": "2:30"
            },
            {
              "r": "W",
              "opp": "Yanal Ashmouz",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            }
          ]
        },
        "stats": {
          "a": {
            "ht": "5'10\"",
            "dob": "1990-12-11",
            "reach": "70.5\"",
            "stance": "Southpaw",
            "slpm": 3.14,
            "strAcc": "51%",
            "sapm": 2.79,
            "strDef": "60%",
            "kd": 0.09,
            "tdLanded": 5.08,
            "tdAcc": "38%",
            "tdDef": "77%",
            "subAvg": 0.38,
            "finRate": "54%",
            "streak": 1,
            "gym": "American Top Team"
          },
          "b": {
            "ht": "6'0\"",
            "dob": "1999-12-28",
            "reach": "75\"",
            "stance": "Orthodox",
            "slpm": 4.73,
            "strAcc": "57%",
            "sapm": 2.79,
            "strDef": "46%",
            "kd": 1.03,
            "tdLanded": 6.86,
            "tdAcc": "36%",
            "tdDef": "81%",
            "subAvg": 1.03,
            "finRate": "75%",
            "streak": 12,
            "gym": "Luistro Combat Academy"
          },
          "sig": {
            "kd": true,
            "strAcc": true,
            "strDef": true,
            "sapm": false,
            "output": false,
            "tdDef": false,
            "tdLanded": true,
            "subAvg": true,
            "finRate": true,
            "slpm": true,
            "tdAcc": false
          }
        },
        "lean": {
          "a": 22,
          "b": 22
        },
        "pace": {
          "a": 6.2,
          "b": 8.3
        },
        "path": {
          "a": "Takedowns are hard both ways (both stuff 77%+) — no clear grappling edge — he has to win the scrambles and positional exchanges.",
          "b": "Takedowns are hard both ways (both stuff 77%+) — his edge is the busier submission game (1.03 vs 0.38 sub att/15)."
        },
        "story": {
          "a": [
            "Lost by finish in 2 of the last 3 — durability questions."
          ],
          "b": [
            "On a 4-fight finish streak.",
            "Hasn't been finished in his last 13 fights.",
            "3-0 vs southpaws."
          ]
        },
        "finishDur": {
          "finRate": {
            "a": "54% (14/26)",
            "b": "77% (10/13)"
          },
          "methods": {
            "a": "7 KO · 7 SUB · 12 DEC",
            "b": "5 KO · 5 SUB · 3 DEC"
          },
          "timesFinished": {
            "a": "2× (2 SUB)",
            "b": "1× (1 SUB)",
            "aCls": "w",
            "bCls": "l"
          }
        },
        "common": [
          {
            "opp": "Beneil Dariush",
            "a": "L (DEC R3)",
            "b": "W (KO/TKO R1)",
            "aCls": "l",
            "bCls": "w"
          }
        ],
        "pA": {
          "name": "Mateusz Gamrot",
          "slug": "mateusz-gamrot",
          "record": "26-5-0",
          "rank": "#8",
          "groups": [
            {
              "t": "Striking",
              "rows": [
                {
                  "label": "Sig. strikes landed / min",
                  "val": "3.14",
                  "cls": "bad",
                  "w": 45.4,
                  "tickX": 63.7,
                  "bar": true
                },
                {
                  "label": "Striking accuracy",
                  "val": "51%",
                  "cls": "good",
                  "w": 87.9,
                  "tickX": 83.6,
                  "bar": true
                },
                {
                  "label": "Sig. strikes absorbed / min",
                  "val": "2.79",
                  "cls": "good",
                  "w": 42.3,
                  "tickX": 62.4,
                  "bar": true
                },
                {
                  "label": "Striking defense",
                  "val": "60%",
                  "cls": "good",
                  "w": 96.8,
                  "tickX": 87.1,
                  "bar": true
                },
                {
                  "label": "Knockdowns / 15 min",
                  "val": "0.09",
                  "cls": "bad",
                  "w": 5.7,
                  "tickX": 33.1,
                  "bar": true
                }
              ]
            },
            {
              "t": "Grappling",
              "rows": [
                {
                  "label": "Takedowns / 15 min",
                  "val": "5.08",
                  "cls": "good",
                  "w": 100,
                  "tickX": 35.1,
                  "bar": true
                },
                {
                  "label": "Takedown accuracy",
                  "val": "38%",
                  "cls": "good",
                  "w": 56.7,
                  "tickX": 53.7,
                  "bar": true
                },
                {
                  "label": "Takedown defense",
                  "val": "77%",
                  "cls": "good",
                  "w": 77,
                  "tickX": 72,
                  "bar": true
                },
                {
                  "label": "Submissions / 15 min",
                  "val": "0.38",
                  "cls": "bad",
                  "w": 17.6,
                  "tickX": 24.5,
                  "bar": true
                }
              ]
            },
            {
              "t": "Miscellaneous",
              "rows": [
                {
                  "label": "Finish rate",
                  "val": "54%",
                  "cls": "bad",
                  "w": 54,
                  "tickX": 73.5,
                  "bar": true
                },
                {
                  "label": "Win streak",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            }
          ],
          "bars": true
        },
        "pB": {
          "name": "Quillan Salkilld",
          "slug": "quillan-salkilld",
          "record": "13-1-0",
          "rank": "#12",
          "groups": [
            {
              "t": "Striking",
              "rows": [
                {
                  "label": "Sig. strikes landed / min",
                  "val": "4.73",
                  "cls": "good",
                  "w": 68.4,
                  "tickX": 63.7,
                  "bar": true
                },
                {
                  "label": "Striking accuracy",
                  "val": "57%",
                  "cls": "good",
                  "w": 98.3,
                  "tickX": 83.6,
                  "bar": true
                },
                {
                  "label": "Sig. strikes absorbed / min",
                  "val": "2.79",
                  "cls": "good",
                  "w": 42.3,
                  "tickX": 62.4,
                  "bar": true
                },
                {
                  "label": "Striking defense",
                  "val": "46%",
                  "cls": "bad",
                  "w": 74.2,
                  "tickX": 87.1,
                  "bar": true
                },
                {
                  "label": "Knockdowns / 15 min",
                  "val": "1.03",
                  "cls": "good",
                  "w": 65.6,
                  "tickX": 33.1,
                  "bar": true
                }
              ]
            },
            {
              "t": "Grappling",
              "rows": [
                {
                  "label": "Takedowns / 15 min",
                  "val": "6.86",
                  "cls": "good",
                  "w": 100,
                  "tickX": 35.1,
                  "bar": true
                },
                {
                  "label": "Takedown accuracy",
                  "val": "36%",
                  "cls": "bad",
                  "w": 53.7,
                  "tickX": 53.7,
                  "bar": true
                },
                {
                  "label": "Takedown defense",
                  "val": "81%",
                  "cls": "good",
                  "w": 81,
                  "tickX": 72,
                  "bar": true
                },
                {
                  "label": "Submissions / 15 min",
                  "val": "1.03",
                  "cls": "good",
                  "w": 47.7,
                  "tickX": 24.5,
                  "bar": true
                }
              ]
            },
            {
              "t": "Miscellaneous",
              "rows": [
                {
                  "label": "Finish rate",
                  "val": "75%",
                  "cls": "good",
                  "w": 75,
                  "tickX": 73.5,
                  "bar": true
                },
                {
                  "label": "Win streak",
                  "val": "13",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            }
          ],
          "bars": true
        }
      }
    },
    "matchup": {
      "event": "UFC Fight Night",
      "startsAt": "2026-08-09T00:00:00.000Z",
      "weightClass": "Lightweight",
      "titleBout": false,
      "rounds": 5,
      "a": {
        "name": "Mateusz Gamrot",
        "slug": "mateusz-gamrot",
        "initials": "MG",
        "record": "26-5-0",
        "rank": "#8",
        "lean": 22,
        "slpm": 3.14,
        "sapm": 2.79
      },
      "b": {
        "name": "Quillan Salkilld",
        "slug": "quillan-salkilld",
        "initials": "QS",
        "record": "13-1-0",
        "rank": "#12",
        "lean": 22,
        "slpm": 4.73,
        "sapm": 2.79
      },
      "odds": null
    }
  }
};
