// AUTO-GENERATED by scripts/gen-landing-data.cjs — do not edit by hand.
export default {
  "generatedAt": "2026-08-28T21:48:27.918Z",
  "rankings": {
    "division": "Bantamweight",
    "rows": [
      {
        "n": "C",
        "name": "Petr Yan",
        "record": "20-5-0",
        "champ": true,
        "slug": "petr-yan",
        "initials": "PY"
      },
      {
        "n": "1",
        "name": "Merab Dvalishvili",
        "record": "21-5-0",
        "champ": false,
        "slug": "merab-dvalishvili",
        "initials": "MD"
      },
      {
        "n": "2",
        "name": "Sean O'Malley",
        "record": "20-3-0",
        "champ": false,
        "slug": "sean-omalley",
        "initials": "SO"
      },
      {
        "n": "3",
        "name": "Umar Nurmagomedov",
        "record": "20-1-0",
        "champ": false,
        "slug": "umar-nurmagomedov",
        "initials": "UN"
      },
      {
        "n": "4",
        "name": "Mario Bautista",
        "record": "18-3-0",
        "champ": false,
        "slug": "mario-bautista",
        "initials": "MB"
      },
      {
        "n": "5",
        "name": "Cory Sandhagen",
        "record": "18-7-0",
        "champ": false,
        "slug": "cory-sandhagen",
        "initials": "CS"
      }
    ]
  },
  "roster": {
    "week": "August 20 – August 27, 2026",
    "added": [
      "Maheshate"
    ],
    "addedTotal": 14,
    "removed": [],
    "removedTotal": 0,
    "names": [
      "Aaron Pico",
      "Abdul Hussein",
      "Abdul Rakhman Yakhyaev",
      "Abdul-Kareem Al-Selwady",
      "Abubakar Vagaev",
      "Abus Magomedov",
      "Adrian Yanez",
      "Aiemann Zahabi",
      "Ailin Perez",
      "Alatengheili",
      "Alberto Montes",
      "Alden Coria"
    ],
    "total": 660
  },
  "featured": {
    "name": "Islam Makhachev",
    "slug": "islam-makhachev",
    "division": "Welterweight",
    "record": "29-1-0",
    "initials": "IM",
    "bio": [
      [
        "Age",
        34
      ],
      [
        "Height",
        "5'10\""
      ],
      [
        "Reach",
        "70.5\""
      ],
      [
        "Stance",
        "Southpaw"
      ],
      [
        "Gym",
        "AKA/Eagles"
      ]
    ],
    "groups": [
      {
        "t": "Striking",
        "rows": [
          {
            "label": "Sig. strikes landed / min",
            "val": "2.27",
            "cls": "bad",
            "w": 24.9,
            "tickX": 45.3,
            "bar": true
          },
          {
            "label": "Striking accuracy",
            "val": "58%",
            "cls": "good",
            "w": 93.5,
            "tickX": 79,
            "bar": true
          },
          {
            "label": "Sig. strikes absorbed / min",
            "val": "1.42",
            "cls": "good",
            "w": 13.2,
            "tickX": 33.6,
            "bar": true
          },
          {
            "label": "Striking defense",
            "val": "61%",
            "cls": "good",
            "w": 93.8,
            "tickX": 83.1,
            "bar": true
          },
          {
            "label": "Knockdowns / 15 min",
            "val": "0.34",
            "cls": "bad",
            "w": 5.4,
            "tickX": 9.3,
            "bar": true
          }
        ]
      },
      {
        "t": "Grappling",
        "rows": [
          {
            "label": "Takedowns / 15 min",
            "val": "3.22",
            "cls": "good",
            "w": 41.4,
            "tickX": 18.1,
            "bar": true
          },
          {
            "label": "Takedown accuracy",
            "val": "55%",
            "cls": "good",
            "w": 87.3,
            "tickX": 60.3,
            "bar": true
          },
          {
            "label": "Takedown defense",
            "val": "91%",
            "cls": "good",
            "w": 91,
            "tickX": 67,
            "bar": true
          },
          {
            "label": "Submissions / 15 min",
            "val": "0.87",
            "cls": "good",
            "w": 55.1,
            "tickX": 39.6,
            "bar": true
          }
        ]
      },
      {
        "t": "Miscellaneous",
        "rows": [
          {
            "label": "Finish rate",
            "val": "62%",
            "cls": "bad",
            "w": 62,
            "tickX": 74,
            "bar": true
          },
          {
            "label": "Win streak",
            "val": "17",
            "cls": "",
            "w": 0,
            "tickX": null,
            "bar": false
          }
        ]
      }
    ],
    "hasBars": true
  },
  "oddsHistory": {
    "name": "Max Holloway",
    "slug": "max-holloway",
    "initials": "MH",
    "rows": [
      {
        "opponent": "Conor McGregor",
        "odds": -324
      },
      {
        "opponent": "Charles Oliveira",
        "odds": -208
      },
      {
        "opponent": "Dustin Poirier",
        "odds": -116
      },
      {
        "opponent": "Ilia Topuria",
        "odds": 228
      },
      {
        "opponent": "Justin Gaethje",
        "odds": 143
      },
      {
        "opponent": "Jung Chan-sung",
        "odds": -750
      },
      {
        "opponent": "Arnold Allen",
        "odds": -170
      }
    ]
  },
  "matchup": {
    "event": "UFC Fight Night: Nurmagomedov vs. Song",
    "startsAt": "2026-08-29T10:00:00.000Z",
    "weightClass": "Bantamweight",
    "titleBout": false,
    "rounds": 5,
    "a": {
      "name": "Umar Nurmagomedov",
      "slug": "umar-nurmagomedov",
      "initials": "UN",
      "record": "20-1-0",
      "rank": "#3",
      "lean": 31,
      "slpm": 3.86,
      "sapm": 1.86
    },
    "b": {
      "name": "Song Yadong",
      "slug": "song-yadong",
      "initials": "SY",
      "record": "23-9-1",
      "rank": "#6",
      "lean": 66,
      "slpm": 4.34,
      "sapm": 3.81
    },
    "odds": {
      "a": "-636",
      "b": "+453",
      "books": 7,
      "favA": true,
      "favB": false
    }
  },
  "parlay": {
    "event": "UFC Fight Night: Nurmagomedov vs. Song",
    "kind": "moneyline",
    "book": "Consensus · 6 books",
    "legs": [
      {
        "pick": "Umar Nurmagomedov",
        "slug": "umar-nurmagomedov",
        "opponent": "Song Yadong",
        "label": "to win",
        "odds": "-636"
      },
      {
        "pick": "Yan Xiaonan",
        "slug": "yan-xiaonan",
        "opponent": "Denise Gomes",
        "label": "to win",
        "odds": "-152"
      },
      {
        "pick": "Bilal Hasan",
        "slug": "bilal-hasan",
        "opponent": "Nilson Rojas",
        "label": "to win",
        "odds": "-822"
      }
    ],
    "combined": "+115",
    "stake": 100,
    "payout": 215
  },
  "styleDemo": {
    "a": {
      "name": "Umar Nurmagomedov",
      "slug": "umar-nurmagomedov",
      "initials": "UN",
      "record": "20-1-0",
      "rank": "#3",
      "lean": 31,
      "pace": 6.9,
      "path": "Get it to the mat — but Yadong's 74% takedown defense is the problem, so shots must come off the cage or in scrambles."
    },
    "b": {
      "name": "Song Yadong",
      "slug": "song-yadong",
      "initials": "SY",
      "record": "23-9-1",
      "rank": "#6",
      "lean": 66,
      "pace": 9.9,
      "path": "Keep it standing: his 74% takedown defense should stall Nurmagomedov's entries, so the fight is won at range."
    }
  },
  "counts": {
    "fighters": 3146,
    "bouts": 29557,
    "historyRows": 59114,
    "videos": 18391,
    "photos": 2356
  },
  "photos": [
    "islam-makhachev",
    "max-holloway",
    "umar-nurmagomedov",
    "song-yadong",
    "yan-xiaonan",
    "bilal-hasan",
    "petr-yan",
    "merab-dvalishvili",
    "sean-omalley",
    "mario-bautista",
    "cory-sandhagen"
  ],
  "card": {
    "event": "UFC Fight Night: Nurmagomedov vs. Song",
    "slug": "ufc-fight-night-august-29-2026",
    "date": "2026-08-29",
    "prelimsAt": "2026-08-29T07:00:00.000Z",
    "location": "Shanghai Oriental Sports Center, Shanghai, China",
    "city": "Shanghai",
    "fights": [
      {
        "f1": "Umar Nurmagomedov",
        "f2": "Song Yadong",
        "s1": "umar-nurmagomedov",
        "s2": "song-yadong",
        "rec1": "20-1-0",
        "rec2": "23-9-1",
        "rank1": "#3",
        "rank2": "#6",
        "weight": "Bantamweight",
        "rounds": 5,
        "o1": "-636",
        "o2": "+453",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 1",
        "main": true,
        "tape": {
          "a": {
            "ht": "5'8\"",
            "reach": "69\"",
            "age": 30,
            "stance": "Orthodox",
            "gym": "American Kickboxing Academy",
            "layoff": {
              "txt": "7 mo",
              "mo": 7,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Deiveson Figueiredo",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Mario Bautista",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Merab Dvalishvili",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Cory Sandhagen",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Bekzat Almakhan",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'8\"",
            "reach": "67\"",
            "age": 28,
            "stance": "Orthodox",
            "gym": "Team Alpha Male",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Deiveson Figueiredo",
                "method": "Submission (Guillotine choke)",
                "round": "2",
                "time": "4:42"
              },
              {
                "r": "L",
                "opp": "Sean O'Malley",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Henry Cejudo",
                "method": "Technical Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Petr Yan",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Chris Gutiérrez",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Yan Xiaonan",
        "f2": "Denise Gomes",
        "s1": "yan-xiaonan",
        "s2": "denise-gomes",
        "rec1": "19-5-0",
        "rec2": "12-3-0",
        "rank1": "#4",
        "rank2": "#14",
        "weight": "Women's Strawweight",
        "rounds": 3,
        "o1": "-152",
        "o2": "+128",
        "books": 6,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 2",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'5\"",
            "reach": "63\"",
            "age": 37,
            "stance": "Orthodox",
            "gym": "Team Alpha Male (2021–present)",
            "layoff": {
              "txt": "1y 5m",
              "mo": 17,
              "long": true
            },
            "l5": [
              {
                "r": "L",
                "opp": "Virna Jandiroba",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Tabatha Ricci",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Zhang Weili",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Jéssica Andrade",
                "method": "KO (Punches)",
                "round": "1",
                "time": "2:20"
              },
              {
                "r": "W",
                "opp": "Mackenzie Dern",
                "method": "Decision (Majority)",
                "round": "5",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'2\"",
            "reach": "63\"",
            "age": 26,
            "stance": "Orthodox",
            "gym": "Paraná Vale Tudo",
            "layoff": {
              "txt": "10 mo",
              "mo": 10,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Tecia Pennington",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Elise Reed",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "0:30"
              },
              {
                "r": "W",
                "opp": "Karolina Kowalkiewicz",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Eduarda Moura",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Angela Hill",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Aoriqileng",
        "f2": "Kai Asakura",
        "s1": "aoriqileng",
        "s2": "kai-asakura",
        "rec1": "26-13-0",
        "rec2": "22-6-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Bantamweight",
        "rounds": 3,
        "o1": null,
        "o2": null,
        "books": 0,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 3",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'7\"",
            "reach": "69\"",
            "age": 33,
            "stance": "Orthodox",
            "gym": "Fight Ready",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Cody Haddon",
                "method": "KO/TKO",
                "round": "2",
                "time": "2:11"
              },
              {
                "r": "W",
                "opp": "Cody Gibson",
                "method": "KO/TKO",
                "round": "1",
                "time": "0:21"
              },
              {
                "r": "L",
                "opp": "Raul Rosas Jr.",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "NC",
                "opp": "Daniel Marcos",
                "method": "No Contest",
                "round": "2",
                "time": "3:28"
              },
              {
                "r": "W",
                "opp": "Johnny Munoz",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'8\"",
            "reach": "69\"",
            "age": 32,
            "stance": "Orthodox",
            "gym": "Japan Top Team",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Cameron Smotherman",
                "method": "KO (Punch)",
                "round": "1",
                "time": "1:50"
              },
              {
                "r": "L",
                "opp": "Tim Elliott",
                "method": "Submission (Guillotine choke)",
                "round": "2",
                "time": "4:39"
              },
              {
                "r": "L",
                "opp": "Alexandre Pantoja",
                "method": "Technical Submission (Rear-naked choke)",
                "round": "2",
                "time": "2:05"
              },
              {
                "r": "W",
                "opp": "Juan Archuleta",
                "method": "TKO (Knee to the body and punches)",
                "round": "2",
                "time": "3:20"
              },
              {
                "r": "W",
                "opp": "Yuki Motoya",
                "method": "KO (Knee to the body)",
                "round": "3",
                "time": "2:25"
              }
            ]
          }
        }
      },
      {
        "f1": "Alex Perez",
        "f2": "Sumudaerji",
        "s1": "alex-perez",
        "s2": "sumudaerji",
        "rec1": "26-10-0",
        "rec2": "19-7-0",
        "rank1": "#11",
        "rank2": "NR",
        "weight": "Flyweight",
        "rounds": 3,
        "o1": null,
        "o2": null,
        "books": 0,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 4",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'6\"",
            "reach": "65\"",
            "age": 34,
            "stance": "Orthodox",
            "gym": "Team Oyama",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "NC",
                "opp": "Su Mudaerji",
                "method": "NC (Accidental groin kick)",
                "round": "2",
                "time": "1:45"
              },
              {
                "r": "W",
                "opp": "Charles Johnson",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "3:16"
              },
              {
                "r": "L",
                "opp": "Asu Almabayev",
                "method": "Submission (Guillotine choke)",
                "round": "3",
                "time": "0:22"
              },
              {
                "r": "L",
                "opp": "Tatsuro Taira",
                "method": "TKO (Knee injury)",
                "round": "2",
                "time": "2:59"
              },
              {
                "r": "W",
                "opp": "Matheus Nicolau",
                "method": "KO (Punch)",
                "round": "2",
                "time": "2:16"
              }
            ]
          },
          "b": {
            "ht": "5'8\"",
            "reach": "72\"",
            "age": 30,
            "stance": "Southpaw",
            "gym": "Team Alpha Male",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "NC",
                "opp": "Alex Perez",
                "method": "No Contest (Accidental groin kick)",
                "round": "2",
                "time": "1:45"
              },
              {
                "r": "W",
                "opp": "Jesus Aguilar",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Kevin Borjas",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Mitch Raposo",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Charles Johnson",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Ce Liu",
        "f2": "Levi Rodrigues Jr.",
        "s1": "",
        "s2": "levi-rodrigues",
        "rec1": "3-1-0",
        "rec2": "5-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Light Heavyweight",
        "rounds": 3,
        "o1": null,
        "o2": null,
        "books": 0,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 5",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'5\"",
            "reach": "78\"",
            "age": 29,
            "stance": "Orthodox",
            "gym": "Tangshan Buntai Riding Fight Club",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Igor Barabanov",
                "method": "TKO (Leg Kicks and Punches)",
                "round": "1",
                "time": "4:56"
              },
              {
                "r": "L",
                "opp": "Ivan Gnizditskiy",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "1:55"
              },
              {
                "r": "W",
                "opp": "Munkh-Erdene Batjargal",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "1:11"
              },
              {
                "r": "W",
                "opp": "Haiming Yu",
                "method": "KO (Punch and Head Kick)",
                "round": "1",
                "time": "1:11"
              }
            ]
          },
          "b": {
            "ht": "6'0\"",
            "reach": "76.5\"",
            "age": 29,
            "stance": "Orthodox",
            "gym": "Rasteira Fight Team",
            "layoff": {
              "txt": "1 mo",
              "mo": 1,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Felipe Franco",
                "method": "KO/TKO (Punches)",
                "round": "2",
                "time": "1:40"
              },
              {
                "r": "NC",
                "opp": "Freddy Vidal",
                "method": "No Contest (Overturned)",
                "round": "1",
                "time": "3:20"
              },
              {
                "r": "W",
                "opp": "Alan Ribeiro",
                "method": "KO (Punches)",
                "round": "1",
                "time": "2:47"
              },
              {
                "r": "W",
                "opp": "Jhonny Pereira",
                "method": "TKO (Shoulder injury)",
                "round": "3",
                "time": "0:21"
              },
              {
                "r": "W",
                "opp": "Jose Carlos Lima",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "1:28"
              }
            ]
          }
        }
      },
      {
        "f1": "Bilal Hasan",
        "f2": "Nilson Rojas",
        "s1": "bilal-hasan",
        "s2": "",
        "rec1": "9-0-0",
        "rec2": "9-0-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Flyweight",
        "rounds": 3,
        "o1": "-822",
        "o2": "+553",
        "books": 7,
        "title": false,
        "section": "Main Card",
        "pos": "Main Card 6",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'7\"",
            "reach": "71\"",
            "age": 25,
            "stance": "",
            "gym": "Charlie's Combat Club",
            "layoff": {
              "txt": "1 mo",
              "mo": 1,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Mridul Saikia",
                "method": "KO/TKO (Punches)",
                "round": "1",
                "time": "0:45"
              },
              {
                "r": "W",
                "opp": "Renaldy Manse",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "2:47"
              },
              {
                "r": "W",
                "opp": "Jason Eastman",
                "method": "TKO (Front Kick to the Body and Punches)",
                "round": "4",
                "time": "1:46"
              },
              {
                "r": "W",
                "opp": "Brian Hauser",
                "method": "KO (Punch to the Body)",
                "round": "2",
                "time": ""
              },
              {
                "r": "W",
                "opp": "Jose Leon",
                "method": "Submission (Rear-Naked Choke)",
                "round": "2",
                "time": ""
              }
            ]
          },
          "b": {
            "ht": "5'5\"",
            "reach": "",
            "age": 27,
            "stance": "",
            "gym": "Pitbull Martial Arts Center / Team Bad Boy",
            "layoff": {
              "txt": "1 mo",
              "mo": 1,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Gonzalo Hanampa",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Wallafy de Paulo",
                "method": "TKO (Body Kick and Punches)",
                "round": "1",
                "time": "4:30"
              },
              {
                "r": "W",
                "opp": "William Rocha",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "4:25"
              },
              {
                "r": "W",
                "opp": "Adrian Haly",
                "method": "TKO (Punches)",
                "round": "3",
                "time": "4:45"
              },
              {
                "r": "W",
                "opp": "Miguel Angel Fierro",
                "method": "KO (Punch)",
                "round": "1",
                "time": "1:50"
              }
            ]
          }
        }
      },
      {
        "f1": "Namsrai Batbayar",
        "f2": "Andre Lima",
        "s1": "namsrai-batbayar",
        "s2": "andre-lima",
        "rec1": "10-1-0",
        "rec2": "11-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Flyweight",
        "rounds": 3,
        "o1": "+220",
        "o2": "-272",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 1",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'4\"",
            "reach": "68\"",
            "age": 25,
            "stance": "Orthodox",
            "gym": "One Team Fighting Center",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Shuai Yin",
                "method": "TKO (Knee)",
                "round": "1",
                "time": "1:48"
              },
              {
                "r": "W",
                "opp": "Agulali",
                "method": "Submission (Rear-naked choke)",
                "round": "1",
                "time": "4:45"
              },
              {
                "r": "W",
                "opp": "Wataru Yamauchi",
                "method": "TKO",
                "round": "2",
                "time": "0:46"
              },
              {
                "r": "W",
                "opp": "Sarvarbek Kenzhaev",
                "method": "TKO",
                "round": "1",
                "time": "4:07"
              },
              {
                "r": "W",
                "opp": "Jinbo Zou",
                "method": "Submission (Rear-naked choke)",
                "round": "1",
                "time": "2:25"
              }
            ]
          },
          "b": {
            "ht": "5'7\"",
            "reach": "67.5\"",
            "age": 27,
            "stance": "Orthodox",
            "gym": "Mascote Team",
            "layoff": {
              "txt": "2 mo",
              "mo": 2,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Kevin Borjas",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Daniel Barez",
                "method": "Submission (Rear-Naked Choke)",
                "round": "3",
                "time": "3:05"
              },
              {
                "r": "W",
                "opp": "Felipe dos Santos",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Mitch Raposo",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Igor Severino",
                "method": "Disqualification (Biting)",
                "round": "2",
                "time": "2:52"
              }
            ]
          }
        }
      },
      {
        "f1": "Rei Tsuruya",
        "f2": "Kevin Borjas",
        "s1": "rei-tsuruya",
        "s2": "kevin-borjas",
        "rec1": "11-1-0",
        "rec2": "11-5-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Flyweight",
        "rounds": 3,
        "o1": "-833",
        "o2": "+558",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 2",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'6\"",
            "reach": "68\"",
            "age": 24,
            "stance": "Orthodox",
            "gym": "Paraestra Matsudo",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Luis Gurule",
                "method": "Submission",
                "round": "1",
                "time": "3:19"
              },
              {
                "r": "L",
                "opp": "Joshua Van",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Carlos Hernandez",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Jiniushiyue",
                "method": "KO/TKO",
                "round": "1",
                "time": "4:59"
              },
              {
                "r": "W",
                "opp": "Mark Climaco",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'5\"",
            "reach": "68\"",
            "age": 28,
            "stance": "Orthodox",
            "gym": "Pitbull Martial Arts Center",
            "layoff": {
              "txt": "2 mo",
              "mo": 2,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Andre Lima",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Imanol Rodriguez",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "4:21"
              },
              {
                "r": "L",
                "opp": "Su Mudaerji",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Ronaldo Rodriguez",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Alessandro Costa",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "1:35"
              }
            ]
          }
        }
      },
      {
        "f1": "Jack Jenkins",
        "f2": "Sean Woodson",
        "s1": "jack-jenkins",
        "s2": "sean-woodson",
        "rec1": "14-4-0",
        "rec2": "13-2-1",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Featherweight",
        "rounds": 3,
        "o1": "+119",
        "o2": "-141",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 3",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'7\"",
            "reach": "68\"",
            "age": 32,
            "stance": "Switch",
            "gym": "Absolute Mixed Martial Arts",
            "layoff": {
              "txt": "11 mo",
              "mo": 11,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Ramon Taveras",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Gabriel Santos",
                "method": "Submission (Rear-naked choke)",
                "round": "3",
                "time": "2:06"
              },
              {
                "r": "W",
                "opp": "Herbert Burns",
                "method": "TKO (Retirement)",
                "round": "3",
                "time": "0:48"
              },
              {
                "r": "L",
                "opp": "Chepe Mariscal",
                "method": "TKO (Injury)",
                "round": "2",
                "time": "3:19"
              },
              {
                "r": "W",
                "opp": "Jamall Emmers",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "6'2\"",
            "reach": "78\"",
            "age": 34,
            "stance": "Orthodox",
            "gym": "Wolves' Den Training Center",
            "layoff": {
              "txt": "1y 5m",
              "mo": 17,
              "long": true
            },
            "l5": [
              {
                "r": "L",
                "opp": "Dan Ige",
                "method": "TKO (Punches)",
                "round": "3",
                "time": "1:12"
              },
              {
                "r": "W",
                "opp": "Fernando Padilla",
                "method": "TKO (Punches)",
                "round": "1",
                "time": "4:58"
              },
              {
                "r": "W",
                "opp": "Alex Caceres",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Charles Jourdain",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Dennis Buzukja",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Xiao Long",
        "f2": "Francesco Nuzzi",
        "s1": "xiao-long",
        "s2": "francesco-nuzzi",
        "rec1": "27-11-0",
        "rec2": "11-2-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Bantamweight",
        "rounds": 3,
        "o1": null,
        "o2": null,
        "books": 0,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 4",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'8\"",
            "reach": "70\"",
            "age": 28,
            "stance": "Orthodox",
            "gym": "UFC Performance Institute Shanghai",
            "layoff": {
              "txt": "6 mo",
              "mo": 6,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Cody Garbrandt",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "SuYoung You",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Quang Le",
                "method": "KO (Punches)",
                "round": "3",
                "time": "1:28"
              },
              {
                "r": "L",
                "opp": "ChangHo Lee",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Shuya Kamikubo",
                "method": "Decision (Majority)",
                "round": "3",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'6\"",
            "reach": "69\"",
            "age": 30,
            "stance": "",
            "gym": "Aurora MMA",
            "layoff": {
              "txt": "5 mo",
              "mo": 5,
              "long": false
            },
            "l5": [
              {
                "r": "NC",
                "opp": "Manoel Costa",
                "method": "No Contest (Accidental Knee to Groin)",
                "round": "1",
                "time": "3:35"
              },
              {
                "r": "W",
                "opp": "Lucas Rodrigues",
                "method": "TKO (Punches and Knee)",
                "round": "1",
                "time": "3:52"
              },
              {
                "r": "L",
                "opp": "Mando Gutierrez",
                "method": "Submission (Rear-Naked Choke)",
                "round": "1",
                "time": "4:13"
              },
              {
                "r": "W",
                "opp": "Farbod Iran Nezhad",
                "method": "KO (Head Kick and Punches)",
                "round": "1",
                "time": "1:52"
              },
              {
                "r": "NC",
                "opp": "Moktar Benkaci",
                "method": "No Contest (Accidental Eye Poke)",
                "round": "2",
                "time": "4:10"
              }
            ]
          }
        }
      },
      {
        "f1": "Lawrence Lui",
        "f2": "Hector Santiago",
        "s1": "lawrence-lui",
        "s2": "",
        "rec1": "8-1-0",
        "rec2": "6-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Bantamweight",
        "rounds": 3,
        "o1": "-340",
        "o2": "+270",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 5",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'7\"",
            "reach": "72\"",
            "age": 30,
            "stance": "Orthodox",
            "gym": "City Kickboxing",
            "layoff": {
              "txt": "7 mo",
              "mo": 7,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Sulangrangbo",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Van Y Nghiem",
                "method": "KO/TKO",
                "round": "2",
                "time": "1:48"
              },
              {
                "r": "W",
                "opp": "Qinghe Zhang",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Daniel Mitchell",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Toby Meech",
                "method": "KO/TKO",
                "round": "1",
                "time": "3:53"
              }
            ]
          },
          "b": {
            "ht": "5'4\"",
            "reach": "69\"",
            "age": 33,
            "stance": "",
            "gym": "Team Lucas Mineiro",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Paulo Nogueira",
                "method": "KO (Punch)",
                "round": "1",
                "time": "3:42"
              },
              {
                "r": "W",
                "opp": "Fernando Henrique",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Maycon Alcino",
                "method": "Submission (Rear-Naked Choke)",
                "round": "2",
                "time": "4:01"
              },
              {
                "r": "W",
                "opp": "Mateus Sales",
                "method": "TKO (Punch to the Body)",
                "round": "2",
                "time": "2:50"
              },
              {
                "r": "W",
                "opp": "Thiago Santos",
                "method": "KO (Punch)",
                "round": "1",
                "time": "0:29"
              }
            ]
          }
        }
      },
      {
        "f1": "Jingnan Xiong",
        "f2": "Julia Polastri",
        "s1": "jingnan-xiong",
        "s2": "julia-polastri",
        "rec1": "19-3-0",
        "rec2": "14-6-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Women's Strawweight",
        "rounds": 3,
        "o1": "+188",
        "o2": "-229",
        "books": 7,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 6",
        "main": false,
        "tape": {
          "a": {
            "ht": "5'5\"",
            "reach": "64\"",
            "age": 38,
            "stance": "Switch",
            "gym": "Phuket Top Team",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Angela Hill",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Meng Bo",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Angela Lee",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Ayaka Miura",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Michelle Nicolini",
                "method": "Decision (Unanimous)",
                "round": "5",
                "time": "5:00"
              }
            ]
          },
          "b": {
            "ht": "5'2\"",
            "reach": "64\"",
            "age": 28,
            "stance": "Orthodox",
            "gym": "CWB Fighter",
            "layoff": {
              "txt": "4 mo",
              "mo": 4,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Talita Alencar",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Karolina Kowalkiewicz",
                "method": "KO/TKO (Head kick & punches)",
                "round": "3",
                "time": "2:56"
              },
              {
                "r": "L",
                "opp": "Loopy Godinez",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Cory McKenna",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "L",
                "opp": "Josefine Knutsson",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      },
      {
        "f1": "Ding Meng",
        "f2": "Cameron Nelson",
        "s1": "ding-meng",
        "s2": "",
        "rec1": "35-10-0",
        "rec2": "7-1-0",
        "rank1": "NR",
        "rank2": "NR",
        "weight": "Welterweight",
        "rounds": 3,
        "o1": null,
        "o2": null,
        "books": 0,
        "title": false,
        "section": "Prelims",
        "pos": "Prelims 7",
        "main": false,
        "tape": {
          "a": {
            "ht": "6'2\"",
            "reach": "73\"",
            "age": 31,
            "stance": "Orthodox",
            "gym": "Black Tiger Fight Club",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "L",
                "opp": "Jose Souza",
                "method": "Decision (Split)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Mirali Huseynov",
                "method": "KO/TKO",
                "round": "2",
                "time": "2:45"
              },
              {
                "r": "L",
                "opp": "Rami Hamed",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Kuerbanjiang Tuluosibake",
                "method": "KO/TKO",
                "round": "3",
                "time": "0:24"
              },
              {
                "r": "W",
                "opp": "Qi Wang",
                "method": "KO/TKO",
                "round": "2",
                "time": "1:31"
              }
            ]
          },
          "b": {
            "ht": "",
            "reach": "",
            "age": 28,
            "stance": "",
            "gym": "Renzo Gracie PEI / Niagara Top Team",
            "layoff": {
              "txt": "3 mo",
              "mo": 3,
              "long": false
            },
            "l5": [
              {
                "r": "W",
                "opp": "Luis Guerrero",
                "method": "TKO (Punches)",
                "round": "2",
                "time": "1:47"
              },
              {
                "r": "W",
                "opp": "Joao Machado",
                "method": "Submission (Rear-Naked Choke)",
                "round": "2",
                "time": "2:13"
              },
              {
                "r": "W",
                "opp": "Kenyon Moore",
                "method": "KO (Punch)",
                "round": "1",
                "time": "2:43"
              },
              {
                "r": "W",
                "opp": "Manuel Garcia",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              },
              {
                "r": "W",
                "opp": "Ryan Rohovich",
                "method": "Decision (Unanimous)",
                "round": "3",
                "time": "5:00"
              }
            ]
          }
        }
      }
    ],
    "main": {
      "a": {
        "ht": "5'8\"",
        "reach": "69\"",
        "age": 30,
        "stance": "Orthodox",
        "gym": "American Kickboxing Academy",
        "layoff": {
          "txt": "7 mo",
          "mo": 7,
          "long": false
        },
        "l5": [
          {
            "r": "W",
            "opp": "Deiveson Figueiredo",
            "method": "Decision (Unanimous)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Mario Bautista",
            "method": "Decision (Unanimous)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "L",
            "opp": "Merab Dvalishvili",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Cory Sandhagen",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Bekzat Almakhan",
            "method": "Decision (Unanimous)",
            "round": "3",
            "time": "5:00"
          }
        ]
      },
      "b": {
        "ht": "5'8\"",
        "reach": "67\"",
        "age": 28,
        "stance": "Orthodox",
        "gym": "Team Alpha Male",
        "layoff": {
          "txt": "3 mo",
          "mo": 3,
          "long": false
        },
        "l5": [
          {
            "r": "W",
            "opp": "Deiveson Figueiredo",
            "method": "Submission (Guillotine choke)",
            "round": "2",
            "time": "4:42"
          },
          {
            "r": "L",
            "opp": "Sean O'Malley",
            "method": "Decision (Unanimous)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Henry Cejudo",
            "method": "Technical Decision (Unanimous)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "L",
            "opp": "Petr Yan",
            "method": "Decision (Unanimous)",
            "round": "3",
            "time": "5:00"
          },
          {
            "r": "W",
            "opp": "Chris Gutiérrez",
            "method": "Decision (Unanimous)",
            "round": "5",
            "time": "5:00"
          }
        ]
      },
      "stats": {
        "a": {
          "ht": "5'8\"",
          "dob": "1996-01-03",
          "reach": "69\"",
          "stance": "Orthodox",
          "slpm": 3.86,
          "strAcc": "56%",
          "sapm": 1.86,
          "strDef": "61%",
          "kd": 0.12,
          "tdLanded": 4.03,
          "tdAcc": "47%",
          "tdDef": "79%",
          "subAvg": 0.24,
          "finRate": "45%",
          "streak": 2,
          "gym": "American Kickboxing Academy"
        },
        "b": {
          "ht": "5'8\"",
          "dob": "1997-12-02",
          "reach": "67\"",
          "stance": "Orthodox",
          "slpm": 4.34,
          "strAcc": "44%",
          "sapm": 3.81,
          "strDef": "55%",
          "kd": 0.48,
          "tdLanded": 0.81,
          "tdAcc": "41%",
          "tdDef": "74%",
          "subAvg": 0.2,
          "finRate": "57%",
          "streak": 1,
          "gym": "Team Alpha Male"
        },
        "sig": {
          "kd": true,
          "strAcc": true,
          "strDef": true,
          "sapm": true,
          "output": false,
          "tdDef": false,
          "tdLanded": true,
          "subAvg": false,
          "finRate": true,
          "slpm": false,
          "tdAcc": false
        }
      },
      "lean": {
        "a": 31,
        "b": 66
      },
      "pace": {
        "a": 6.9,
        "b": 9.9
      },
      "path": {
        "a": "Get it to the mat — but Yadong's 74% takedown defense is the problem, so shots must come off the cage or in scrambles.",
        "b": "Keep it standing: his 74% takedown defense should stall Nurmagomedov's entries, so the fight is won at range."
      },
      "story": {
        "a": [],
        "b": [
          "Hasn't been finished in his last 6 fights."
        ]
      },
      "finishDur": {
        "finRate": {
          "a": "45% (9/20)",
          "b": "57% (13/23)"
        },
        "methods": {
          "a": "2 KO · 7 SUB · 11 DEC",
          "b": "9 KO · 4 SUB · 10 DEC"
        },
        "timesFinished": {
          "a": "Never",
          "b": "3× (2 KO/TKO, 1 DQ)",
          "aCls": "w",
          "bCls": "l"
        }
      },
      "common": [
        {
          "opp": "Deiveson Figueiredo",
          "a": "W (DEC R3)",
          "b": "W (SUB R2)",
          "aCls": "w",
          "bCls": "w"
        },
        {
          "opp": "Cory Sandhagen",
          "a": "W (DEC R5)",
          "b": "L (KO/TKO R4)",
          "aCls": "w",
          "bCls": "l"
        }
      ],
      "pA": {
        "name": "Umar Nurmagomedov",
        "slug": "umar-nurmagomedov",
        "record": "20-1-0",
        "rank": "#3",
        "groups": [
          {
            "t": "Striking",
            "rows": [
              {
                "label": "Sig. strikes landed / min",
                "val": "3.86",
                "cls": "bad",
                "w": 52.7,
                "tickX": 59.2,
                "bar": true
              },
              {
                "label": "Striking accuracy",
                "val": "56%",
                "cls": "good",
                "w": 93.3,
                "tickX": 80,
                "bar": true
              },
              {
                "label": "Sig. strikes absorbed / min",
                "val": "1.86",
                "cls": "good",
                "w": 32.5,
                "tickX": 63.5,
                "bar": true
              },
              {
                "label": "Striking defense",
                "val": "61%",
                "cls": "good",
                "w": 88.4,
                "tickX": 79.7,
                "bar": true
              },
              {
                "label": "Knockdowns / 15 min",
                "val": "0.12",
                "cls": "bad",
                "w": 7.6,
                "tickX": 32.5,
                "bar": true
              }
            ]
          },
          {
            "t": "Grappling",
            "rows": [
              {
                "label": "Takedowns / 15 min",
                "val": "4.03",
                "cls": "good",
                "w": 73.3,
                "tickX": 27.3,
                "bar": true
              },
              {
                "label": "Takedown accuracy",
                "val": "47%",
                "cls": "good",
                "w": 66.2,
                "tickX": 50.7,
                "bar": true
              },
              {
                "label": "Takedown defense",
                "val": "79%",
                "cls": "good",
                "w": 79,
                "tickX": 67,
                "bar": true
              },
              {
                "label": "Submissions / 15 min",
                "val": "0.24",
                "cls": "bad",
                "w": 12,
                "tickX": 31,
                "bar": true
              }
            ]
          },
          {
            "t": "Miscellaneous",
            "rows": [
              {
                "label": "Finish rate",
                "val": "45%",
                "cls": "bad",
                "w": 50.6,
                "tickX": 75.3,
                "bar": true
              },
              {
                "label": "Win streak",
                "val": "2",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          }
        ],
        "bars": true
      },
      "pB": {
        "name": "Song Yadong",
        "slug": "song-yadong",
        "record": "23-9-1",
        "rank": "#6",
        "groups": [
          {
            "t": "Striking",
            "rows": [
              {
                "label": "Sig. strikes landed / min",
                "val": "4.34",
                "cls": "good",
                "w": 59.3,
                "tickX": 59.2,
                "bar": true
              },
              {
                "label": "Striking accuracy",
                "val": "44%",
                "cls": "bad",
                "w": 73.3,
                "tickX": 80,
                "bar": true
              },
              {
                "label": "Sig. strikes absorbed / min",
                "val": "3.81",
                "cls": "bad",
                "w": 66.5,
                "tickX": 63.5,
                "bar": true
              },
              {
                "label": "Striking defense",
                "val": "55%",
                "cls": "bad",
                "w": 79.7,
                "tickX": 79.7,
                "bar": true
              },
              {
                "label": "Knockdowns / 15 min",
                "val": "0.48",
                "cls": "bad",
                "w": 30.6,
                "tickX": 32.5,
                "bar": true
              }
            ]
          },
          {
            "t": "Grappling",
            "rows": [
              {
                "label": "Takedowns / 15 min",
                "val": "0.81",
                "cls": "bad",
                "w": 14.7,
                "tickX": 27.3,
                "bar": true
              },
              {
                "label": "Takedown accuracy",
                "val": "41%",
                "cls": "good",
                "w": 57.7,
                "tickX": 50.7,
                "bar": true
              },
              {
                "label": "Takedown defense",
                "val": "74%",
                "cls": "good",
                "w": 74,
                "tickX": 67,
                "bar": true
              },
              {
                "label": "Submissions / 15 min",
                "val": "0.2",
                "cls": "bad",
                "w": 10,
                "tickX": 31,
                "bar": true
              }
            ]
          },
          {
            "t": "Miscellaneous",
            "rows": [
              {
                "label": "Finish rate",
                "val": "57%",
                "cls": "bad",
                "w": 64,
                "tickX": 75.3,
                "bar": true
              },
              {
                "label": "Win streak",
                "val": "1",
                "cls": "",
                "w": 0,
                "tickX": null,
                "bar": false
              }
            ]
          }
        ],
        "bars": true
      }
    }
  },
  "held": {
    "startsAt": "2026-08-25T23:00:00.000Z",
    "card": {
      "event": "Dana White's Contender Series: Season 10, Week 3",
      "slug": "ufc-fight-night-august-25-2026",
      "date": "2026-08-25",
      "prelimsAt": "2026-08-25T23:00:00.000Z",
      "location": "Meta APEX, Las Vegas, NV",
      "city": "Las Vegas",
      "fights": [
        {
          "f1": "Bella Mir",
          "f2": "Alex Apodaca",
          "s1": "",
          "s2": "",
          "rec1": "4-1-0",
          "rec2": "4-1-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Women's Bantamweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 1",
          "main": true,
          "tape": {
            "a": {
              "ht": "5'7\"",
              "reach": "67\"",
              "age": 23,
              "stance": "",
              "gym": "Syndicate MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Alex Apodaca",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Stephanie Calderon",
                  "method": "Submission (Hammerlock)",
                  "round": "1",
                  "time": "3:58"
                },
                {
                  "r": "W",
                  "opp": "Jessica Link-Davis",
                  "method": "Submission (Armbar)",
                  "round": "1",
                  "time": "2:38"
                },
                {
                  "r": "W",
                  "opp": "Alma Cespedes",
                  "method": "Submission (Rear-Naked Choke)",
                  "round": "1",
                  "time": "1:53"
                },
                {
                  "r": "W",
                  "opp": "Danielle Wynn",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            },
            "b": {
              "ht": "5'7\"",
              "reach": "71.5\"",
              "age": null,
              "stance": "",
              "gym": "FactoryX Muay Thai",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Bella Mir",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Devon McDonald",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Shanna Gomez",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Karine Cristine",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "L",
                  "opp": "Nikola Kacperska",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Mario Piazzon",
          "f2": "Guilherme Uriel",
          "s1": "mario-piazzon",
          "s2": "guilherme-uriel",
          "rec1": "12-2-0",
          "rec2": "8-2-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Heavyweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 2",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'9\"",
              "reach": "73\"",
              "age": 28,
              "stance": "Orthodox",
              "gym": "Galpao Da Luta",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Guilherme Uriel",
                  "method": "Submission (Guillotine Choke)",
                  "round": "1",
                  "time": "0:50"
                },
                {
                  "r": "W",
                  "opp": "Andre Vieira",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Fernando Batista",
                  "method": "KO/TKO",
                  "round": "2",
                  "time": "3:50"
                },
                {
                  "r": "L",
                  "opp": "Alex Junius",
                  "method": "KO/TKO",
                  "round": "1",
                  "time": "2:25"
                },
                {
                  "r": "W",
                  "opp": "Andre Vieira",
                  "method": "KO/TKO",
                  "round": "2",
                  "time": "4:33"
                }
              ]
            },
            "b": {
              "ht": "6'1\"",
              "reach": "74\"",
              "age": 29,
              "stance": "Orthodox",
              "gym": "Evolution Combat MMA",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Mario Piazzon",
                  "method": "Submission (Guillotine Choke)",
                  "round": "1",
                  "time": "0:50"
                },
                {
                  "r": "W",
                  "opp": "Leonardo Fraga",
                  "method": "KO/TKO",
                  "round": "1",
                  "time": "1:36"
                },
                {
                  "r": "L",
                  "opp": "Josh Hokit",
                  "method": "KO/TKO",
                  "round": "2",
                  "time": "1:06"
                },
                {
                  "r": "W",
                  "opp": "Hyago Silva",
                  "method": "KO/TKO",
                  "round": "1",
                  "time": "1:27"
                },
                {
                  "r": "W",
                  "opp": "Weslley Alec",
                  "method": "Submission (Guillotine)",
                  "round": "1",
                  "time": "0:29"
                }
              ]
            }
          }
        },
        {
          "f1": "Gary Balletto",
          "f2": "Sean Clancy Jr.",
          "s1": "",
          "s2": "",
          "rec1": "",
          "rec2": "9-0-0",
          "rank1": "",
          "rank2": "NR",
          "weight": "Welterweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 3",
          "main": false,
          "tape": {
            "a": {
              "ht": "",
              "reach": "",
              "age": null,
              "stance": "",
              "gym": "",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Sean Clancy Jr.",
                  "method": "KO/TKO (Elbows)",
                  "round": "2",
                  "time": "3:54"
                },
                {
                  "r": "W",
                  "opp": "William Dunkle",
                  "method": "KO/TKO",
                  "round": "2",
                  "time": "4:43"
                },
                {
                  "r": "W",
                  "opp": "Bruno Quintanilha",
                  "method": "KO/TKO",
                  "round": "2",
                  "time": "2:36"
                },
                {
                  "r": "W",
                  "opp": "Pat Casey",
                  "method": "Submission (Rear-Naked Choke)",
                  "round": "1",
                  "time": "3:08"
                },
                {
                  "r": "W",
                  "opp": "James Cannon",
                  "method": "Submission (Rear-Naked Choke)",
                  "round": "2",
                  "time": "0:37"
                }
              ]
            },
            "b": {
              "ht": "6'2\"",
              "reach": "",
              "age": 23,
              "stance": "",
              "gym": "Higher Level Martial Arts",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Gary Balletto",
                  "method": "KO/TKO (Elbows)",
                  "round": "2",
                  "time": "3:54"
                },
                {
                  "r": "W",
                  "opp": "Melvin van Suijdam",
                  "method": "KO/TKO (Punches)",
                  "round": "2",
                  "time": ""
                },
                {
                  "r": "W",
                  "opp": "Italo Gomes",
                  "method": "Submission (Neck Crank)",
                  "round": "2",
                  "time": ""
                },
                {
                  "r": "W",
                  "opp": "Andrey Augusto",
                  "method": "TKO (Punch to the Body)",
                  "round": "3",
                  "time": ""
                },
                {
                  "r": "W",
                  "opp": "Rafael Aronov",
                  "method": "Submission (Rear-Naked Choke)",
                  "round": "1",
                  "time": ""
                }
              ]
            }
          }
        },
        {
          "f1": "Ronald Humphrey",
          "f2": "Alexis Miranda",
          "s1": "",
          "s2": "",
          "rec1": "5-0-0",
          "rec2": "9-3-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Welterweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 4",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'11\"",
              "reach": "77\"",
              "age": 25,
              "stance": "Orthodox",
              "gym": "American Top Team Sandy Springs",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Alexis Miranda",
                  "method": "Submission (Rear Naked Choke)",
                  "round": "1",
                  "time": "4:03"
                },
                {
                  "r": "W",
                  "opp": "Liam Hamill",
                  "method": "TKO (Punches)",
                  "round": "1",
                  "time": "0:28"
                },
                {
                  "r": "W",
                  "opp": "Dupree Stewart",
                  "method": "KO/TKO (Punches from Top)",
                  "round": "1",
                  "time": "3:11"
                },
                {
                  "r": "W",
                  "opp": "Paul Kimble",
                  "method": "KO/TKO (Punches)",
                  "round": "2",
                  "time": "2:28"
                },
                {
                  "r": "W",
                  "opp": "Ralston Thomas",
                  "method": "TKO (Strikes)",
                  "round": "1",
                  "time": "1:31"
                }
              ]
            },
            "b": {
              "ht": "6'2\"",
              "reach": "76.5\"",
              "age": 27,
              "stance": "",
              "gym": "Entram Gym",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Ronald Humphrey",
                  "method": "Submission (Rear Naked Choke)",
                  "round": "1",
                  "time": "4:03"
                },
                {
                  "r": "W",
                  "opp": "Ricardo Chavez",
                  "method": "Decision (Split)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Eduardo Figueroa",
                  "method": "KO/TKO",
                  "round": "1",
                  "time": ""
                },
                {
                  "r": "L",
                  "opp": "Anuar Aburto",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Roman Cordova",
                  "method": "Decision (Unanimous)",
                  "round": "3",
                  "time": "5:00"
                }
              ]
            }
          }
        },
        {
          "f1": "Carlos Petruzzella",
          "f2": "Nick Galanti",
          "s1": "",
          "s2": "",
          "rec1": "15-2-0",
          "rec2": "8-1-0",
          "rank1": "NR",
          "rank2": "NR",
          "weight": "Middleweight",
          "rounds": 3,
          "o1": null,
          "o2": null,
          "books": 0,
          "title": false,
          "section": "Main Card",
          "pos": "Main Card 5",
          "main": false,
          "tape": {
            "a": {
              "ht": "5'11\"",
              "reach": "",
              "age": 29,
              "stance": "",
              "gym": "Thai Brasil",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "L",
                  "opp": "Nick Galanti",
                  "method": "KO/TKO (Punch)",
                  "round": "1",
                  "time": "0:35"
                },
                {
                  "r": "W",
                  "opp": "Lautaro Ayala",
                  "method": "TKO (Head Kick, Knee & Ground Elbows)",
                  "round": "1",
                  "time": "3:06"
                },
                {
                  "r": "W",
                  "opp": "Diego Robledo",
                  "method": "TKO (Doctor Stoppage)",
                  "round": "1",
                  "time": "0:45"
                },
                {
                  "r": "L",
                  "opp": "Joseilton Santos",
                  "method": "KO/TKO (Right Overhand)",
                  "round": "1",
                  "time": "4:24"
                },
                {
                  "r": "W",
                  "opp": "Gaston Palomino",
                  "method": "TKO (Ground and Pound)",
                  "round": "1",
                  "time": "0:50"
                }
              ]
            },
            "b": {
              "ht": "6'1\"",
              "reach": "",
              "age": 28,
              "stance": "",
              "gym": "Dante Rivera BJJ",
              "layoff": {
                "txt": "0 mo",
                "mo": 0,
                "long": false
              },
              "l5": [
                {
                  "r": "W",
                  "opp": "Carlos Petruzzella",
                  "method": "KO/TKO (Punch)",
                  "round": "1",
                  "time": "0:35"
                },
                {
                  "r": "W",
                  "opp": "Austin Clayton",
                  "method": "Decision (Unanimous)",
                  "round": "5",
                  "time": "5:00"
                },
                {
                  "r": "W",
                  "opp": "Derek Benoit",
                  "method": "Submission (Rear-Naked Choke)",
                  "round": "1",
                  "time": ""
                },
                {
                  "r": "W",
                  "opp": "Ty Gwerder",
                  "method": "KO/TKO",
                  "round": "3",
                  "time": ""
                },
                {
                  "r": "W",
                  "opp": "Shane Sobnosky",
                  "method": "Submission (Guillotine)",
                  "round": "1",
                  "time": ""
                }
              ]
            }
          }
        }
      ],
      "main": {
        "a": {
          "ht": "5'7\"",
          "reach": "67\"",
          "age": 23,
          "stance": "",
          "gym": "Syndicate MMA",
          "layoff": {
            "txt": "0 mo",
            "mo": 0,
            "long": false
          },
          "l5": [
            {
              "r": "L",
              "opp": "Alex Apodaca",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            },
            {
              "r": "W",
              "opp": "Stephanie Calderon",
              "method": "Submission (Hammerlock)",
              "round": "1",
              "time": "3:58"
            },
            {
              "r": "W",
              "opp": "Jessica Link-Davis",
              "method": "Submission (Armbar)",
              "round": "1",
              "time": "2:38"
            },
            {
              "r": "W",
              "opp": "Alma Cespedes",
              "method": "Submission (Rear-Naked Choke)",
              "round": "1",
              "time": "1:53"
            },
            {
              "r": "W",
              "opp": "Danielle Wynn",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            }
          ]
        },
        "b": {
          "ht": "5'7\"",
          "reach": "71.5\"",
          "age": null,
          "stance": "",
          "gym": "FactoryX Muay Thai",
          "layoff": {
            "txt": "0 mo",
            "mo": 0,
            "long": false
          },
          "l5": [
            {
              "r": "W",
              "opp": "Bella Mir",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            },
            {
              "r": "W",
              "opp": "Devon McDonald",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            },
            {
              "r": "W",
              "opp": "Shanna Gomez",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            },
            {
              "r": "W",
              "opp": "Karine Cristine",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            },
            {
              "r": "L",
              "opp": "Nikola Kacperska",
              "method": "Decision (Unanimous)",
              "round": "3",
              "time": "5:00"
            }
          ]
        },
        "stats": {
          "a": {
            "ht": "5'7\"",
            "dob": "2003-01-01",
            "reach": "67\"",
            "stance": null,
            "slpm": 2,
            "strAcc": "39%",
            "sapm": 3.2,
            "strDef": "61%",
            "kd": 0,
            "tdLanded": 1,
            "tdAcc": "17%",
            "tdDef": null,
            "subAvg": 0,
            "finRate": "75%",
            "streak": 4,
            "gym": "Syndicate MMA"
          },
          "b": {
            "ht": "5'7\"",
            "dob": null,
            "reach": "71.5\"",
            "stance": null,
            "slpm": 3.2,
            "strAcc": "39%",
            "sapm": 2,
            "strDef": "61%",
            "kd": 0,
            "tdLanded": 0,
            "tdAcc": null,
            "tdDef": "83%",
            "subAvg": 0,
            "finRate": "0%",
            "streak": 3,
            "gym": "FactoryX Muay Thai"
          },
          "sig": {
            "kd": false,
            "strAcc": false,
            "strDef": false,
            "sapm": true,
            "output": false,
            "tdDef": false,
            "tdLanded": true,
            "subAvg": false,
            "finRate": true,
            "slpm": true,
            "tdAcc": false
          }
        },
        "lean": {
          "a": 50,
          "b": 84
        },
        "pace": {
          "a": 5.1,
          "b": 8.2
        },
        "path": {
          "a": "Comfortable everywhere — her edge is the bigger finishing threat; drag Apodaca into her stronger area.",
          "b": "A striking battle — she has the edge in output (8.2 vs 5.1 thrown/min), so her path is volume and pace over the rounds, while staying disciplined against Mir's power."
        },
        "story": {
          "a": [
            "Won by finish in 3 of the last 5."
          ],
          "b": []
        },
        "finishDur": {
          "finRate": {
            "a": "75% (3/4)",
            "b": "0% (0/4)"
          },
          "methods": {
            "a": "3 SUB · 1 DEC",
            "b": "4 DEC"
          },
          "timesFinished": {
            "a": "Never",
            "b": "Never",
            "aCls": "",
            "bCls": ""
          }
        },
        "common": [],
        "pA": {
          "name": "Bella Mir",
          "slug": "",
          "record": "4-1-0",
          "rank": "NR",
          "groups": [
            {
              "t": "Striking",
              "rows": [
                {
                  "label": "Sig. strikes landed / min",
                  "val": "2",
                  "cls": "bad",
                  "w": 35.4,
                  "tickX": 73.1,
                  "bar": true
                },
                {
                  "label": "Striking accuracy",
                  "val": "39%",
                  "cls": "bad",
                  "w": 67.2,
                  "tickX": 84.5,
                  "bar": true
                },
                {
                  "label": "Sig. strikes absorbed / min",
                  "val": "3.2",
                  "cls": "bad",
                  "w": 55.6,
                  "tickX": 54.2,
                  "bar": true
                },
                {
                  "label": "Striking defense",
                  "val": "61%",
                  "cls": "good",
                  "w": 88.4,
                  "tickX": 81.2,
                  "bar": true
                },
                {
                  "label": "Knockdowns / 15 min",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            },
            {
              "t": "Grappling",
              "rows": [
                {
                  "label": "Takedowns / 15 min",
                  "val": "1",
                  "cls": "bad",
                  "w": 28,
                  "tickX": 41.9,
                  "bar": true
                },
                {
                  "label": "Takedown accuracy",
                  "val": "17%",
                  "cls": "bad",
                  "w": 17,
                  "tickX": 47,
                  "bar": true
                },
                {
                  "label": "Takedown defense",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                },
                {
                  "label": "Submissions / 15 min",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            },
            {
              "t": "Miscellaneous",
              "rows": [
                {
                  "label": "Finish rate",
                  "val": "75%",
                  "cls": "good",
                  "w": 85.2,
                  "tickX": 70.5,
                  "bar": true
                },
                {
                  "label": "Win streak",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            }
          ],
          "bars": true
        },
        "pB": {
          "name": "Alex Apodaca",
          "slug": "",
          "record": "4-1-0",
          "rank": "NR",
          "groups": [
            {
              "t": "Striking",
              "rows": [
                {
                  "label": "Sig. strikes landed / min",
                  "val": "3.2",
                  "cls": "bad",
                  "w": 56.6,
                  "tickX": 73.1,
                  "bar": true
                },
                {
                  "label": "Striking accuracy",
                  "val": "39%",
                  "cls": "bad",
                  "w": 67.2,
                  "tickX": 84.5,
                  "bar": true
                },
                {
                  "label": "Sig. strikes absorbed / min",
                  "val": "2",
                  "cls": "good",
                  "w": 34.7,
                  "tickX": 54.2,
                  "bar": true
                },
                {
                  "label": "Striking defense",
                  "val": "61%",
                  "cls": "good",
                  "w": 88.4,
                  "tickX": 81.2,
                  "bar": true
                },
                {
                  "label": "Knockdowns / 15 min",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            },
            {
              "t": "Grappling",
              "rows": [
                {
                  "label": "Takedowns / 15 min",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                },
                {
                  "label": "Takedown accuracy",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                },
                {
                  "label": "Takedown defense",
                  "val": "83%",
                  "cls": "good",
                  "w": 83,
                  "tickX": 65,
                  "bar": true
                },
                {
                  "label": "Submissions / 15 min",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            },
            {
              "t": "Miscellaneous",
              "rows": [
                {
                  "label": "Finish rate",
                  "val": "—",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                },
                {
                  "label": "Win streak",
                  "val": "4",
                  "cls": "",
                  "w": 0,
                  "tickX": null,
                  "bar": false
                }
              ]
            }
          ],
          "bars": true
        }
      }
    },
    "matchup": {
      "event": "Dana White's Contender Series: Season 10, Week 3",
      "startsAt": "2026-08-25T23:00:00.000Z",
      "weightClass": "Women's Bantamweight",
      "titleBout": false,
      "rounds": 3,
      "a": {
        "name": "Bella Mir",
        "slug": "",
        "initials": "BM",
        "record": "4-1-0",
        "rank": "NR",
        "lean": 50,
        "slpm": 2,
        "sapm": 3.2
      },
      "b": {
        "name": "Alex Apodaca",
        "slug": "",
        "initials": "AA",
        "record": "4-1-0",
        "rank": "NR",
        "lean": 84,
        "slpm": 3.2,
        "sapm": 2
      },
      "odds": null
    }
  }
};
