// AUTO-GENERATED by scripts/gen-scorecard-data.cjs — do not edit by hand.
export default {
  "generatedAt": "2026-07-09T14:42:46.989Z",
  "scorecard": {
    "generatedAt": "2026-07-09T14:42:46.953Z",
    "nGraded": 0,
    "note": "Internal proof-of-concept. Pre-upgrade CLV uses self-snapshotted close (approximate).",
    "calibration": [],
    "accuracy": {
      "model": null,
      "marketClose": null
    },
    "brier": {
      "modelOpen": null,
      "marketClose": null
    },
    "logloss": {
      "modelOpen": null,
      "marketClose": null
    },
    "clv": {
      "nWithMovement": 0,
      "hitRate": null,
      "avgMovePts": null,
      "leanedOnly": {
        "n": 0,
        "hitRate": null,
        "avgMovePts": null
      }
    }
  },
  "graded": []
};
