// AUTO-GENERATED by scripts/gen-scorecard-data.cjs — do not edit by hand.
export default {
  "generatedAt": "2026-08-14T00:55:06.809Z",
  "scorecard": {
    "generatedAt": "2026-08-14T00:55:06.712Z",
    "nGraded": 58,
    "note": "Internal proof-of-concept. Pre-upgrade CLV uses self-snapshotted close (approximate).",
    "calibration": [
      {
        "band": "30-40%",
        "n": 7,
        "predicted": 0.3684,
        "actual": 0.4286
      },
      {
        "band": "40-50%",
        "n": 17,
        "predicted": 0.4526,
        "actual": 0.3529
      },
      {
        "band": "50-60%",
        "n": 24,
        "predicted": 0.5486,
        "actual": 0.7083
      },
      {
        "band": "60-70%",
        "n": 8,
        "predicted": 0.6301,
        "actual": 0.875
      },
      {
        "band": "70-80%",
        "n": 2,
        "predicted": 0.728,
        "actual": 1
      }
    ],
    "accuracy": {
      "model": 0.7069,
      "marketClose": 0.7931
    },
    "brier": {
      "modelOpen": 0.2172,
      "marketClose": 0.1474
    },
    "logloss": {
      "modelOpen": 0.6262,
      "marketClose": 0.4651
    },
    "clv": {
      "nWithMovement": 58,
      "hitRate": 0.3793,
      "avgMovePts": -0.0068,
      "leanedOnly": {
        "n": 50,
        "hitRate": 0.38,
        "avgMovePts": -0.006
      }
    }
  },
  "graded": [
    {
      "event": "UFC 329",
      "a": {
        "feed": "Cody Durden",
        "db": "Cody Durden"
      },
      "b": {
        "feed": "Alessandro Costa",
        "db": "Alessandro Costa"
      },
      "winner": "B",
      "method": "Submission",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.3972,
      "modelClose": 0.3973,
      "marketOpen": 0.3111,
      "marketClose": 0.3322,
      "leanA": 0.0861,
      "clv": {
        "toward": true,
        "pts": 0.0211,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Damian Pinas",
        "db": "Damian Pinas"
      },
      "b": {
        "feed": "Cesar Almeida",
        "db": "Cesar Almeida"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.7125,
      "modelClose": 0.7125,
      "marketOpen": 0.6531,
      "marketClose": 0.6895,
      "leanA": 0.0594,
      "clv": {
        "toward": true,
        "pts": 0.0364,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Tracy Cortez",
        "db": "Tracy Cortez"
      },
      "b": {
        "feed": "Wang Cong",
        "db": "Wang Cong"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4407,
      "modelClose": 0.4407,
      "marketOpen": 0.4892,
      "marketClose": 0.4837,
      "leanA": -0.0485,
      "clv": {
        "toward": true,
        "pts": 0.0055,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Luke Riley",
        "db": "Luke Riley"
      },
      "b": {
        "feed": "Kai Kamaka",
        "db": "Kai Kamaka III"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5531,
      "modelClose": 0.5531,
      "marketOpen": 0.7163,
      "marketClose": 0.6656,
      "leanA": -0.1632,
      "clv": {
        "toward": true,
        "pts": 0.0507,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Cody Garbrandt",
        "db": "Cody Garbrandt"
      },
      "b": {
        "feed": "Adrian Yanez",
        "db": "Adrian Yanez"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5165,
      "modelClose": 0.5165,
      "marketOpen": 0.2185,
      "marketClose": 0.2198,
      "leanA": 0.298,
      "clv": {
        "toward": true,
        "pts": 0.0013,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Gable Steveson",
        "db": "Gable Steveson"
      },
      "b": {
        "feed": "Elisha Ellison",
        "db": "Elisha Ellison"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5266,
      "modelClose": 0.5266,
      "marketOpen": 0.9213,
      "marketClose": 0.9042,
      "leanA": -0.3947,
      "clv": {
        "toward": true,
        "pts": 0.0171,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Robert Whittaker",
        "db": "Robert Whittaker"
      },
      "b": {
        "feed": "Nikita Krylov",
        "db": "Nikita Krylov"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4402,
      "modelClose": 0.4402,
      "marketOpen": 0.5635,
      "marketClose": 0.5293,
      "leanA": -0.1233,
      "clv": {
        "toward": true,
        "pts": 0.0342,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "John Garza",
        "db": "John Garza"
      },
      "b": {
        "feed": "Farid Basharat",
        "db": "Farid Basharat"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4733,
      "modelClose": 0.4733,
      "marketOpen": 0.1729,
      "marketClose": 0.1677,
      "leanA": 0.3004,
      "clv": {
        "toward": false,
        "pts": -0.0052,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Paddy Pimblett",
        "db": "Paddy Pimblett"
      },
      "b": {
        "feed": "Benoit Saint-Denis",
        "db": "Benoît Saint Denis"
      },
      "winner": "A",
      "method": "Submission",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.3148,
      "modelClose": 0.3148,
      "marketOpen": 0.4428,
      "marketClose": 0.4417,
      "leanA": -0.128,
      "clv": {
        "toward": true,
        "pts": 0.0011,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Max Holloway",
        "db": "Max Holloway"
      },
      "b": {
        "feed": "Conor McGregor",
        "db": "Conor McGregor"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 5,
      "modelOpen": 0.6228,
      "modelClose": 0.6227,
      "marketOpen": 0.6636,
      "marketClose": 0.7356,
      "leanA": -0.0408,
      "clv": {
        "toward": false,
        "pts": -0.072,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "King Green",
        "db": "King Green"
      },
      "b": {
        "feed": "Terrance Mckinney",
        "db": "Terrance McKinney"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.3884,
      "modelClose": 0.3883,
      "marketOpen": 0.4254,
      "marketClose": 0.4474,
      "leanA": -0.037,
      "clv": {
        "toward": false,
        "pts": -0.022,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Brandon Royval",
        "db": "Brandon Royval"
      },
      "b": {
        "feed": "Lone'er Kavanagh",
        "db": "Lone'er Kavanagh"
      },
      "winner": "A",
      "method": "Submission",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.577,
      "modelClose": 0.5771,
      "marketOpen": 0.3379,
      "marketClose": 0.3273,
      "leanA": 0.2391,
      "clv": {
        "toward": false,
        "pts": -0.0106,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Cory Sandhagen",
        "db": "Cory Sandhagen"
      },
      "b": {
        "feed": "Mario Bautista",
        "db": "Mario Bautista"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5175,
      "modelClose": 0.5174,
      "marketOpen": 0.5721,
      "marketClose": 0.5644,
      "leanA": -0.0546,
      "clv": {
        "toward": true,
        "pts": 0.0077,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Levi Rodrigues",
        "db": "Levi Rodrigues Jr."
      },
      "b": {
        "feed": "Felipe Franco",
        "db": "Felipe Franco"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.6324,
      "modelClose": 0.6324,
      "marketOpen": 0.6279,
      "marketClose": 0.5711,
      "leanA": 0.0045,
      "clv": {
        "toward": false,
        "pts": -0.0568,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Tommy McMillen",
        "db": "Tommy McMillen"
      },
      "b": {
        "feed": "Alberto Montes",
        "db": "Alberto Montes"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4351,
      "modelClose": 0.4351,
      "marketOpen": 0.438,
      "marketClose": 0.6038,
      "leanA": -0.0029,
      "clv": {
        "toward": false,
        "pts": -0.1658,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Alden Coria",
        "db": "Alden Coria"
      },
      "b": {
        "feed": "Stewart Nicoll",
        "db": "Stewart Nicoll"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.6469,
      "modelClose": 0.6469,
      "marketOpen": 0.8757,
      "marketClose": 0.88,
      "leanA": -0.2288,
      "clv": {
        "toward": false,
        "pts": -0.0043,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Anna Melisano",
        "db": "Anna Melisano"
      },
      "b": {
        "feed": "Dione Barbosa",
        "db": "Dione Barbosa"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4295,
      "modelClose": 0.4295,
      "marketOpen": 0.2133,
      "marketClose": 0.1729,
      "leanA": 0.2162,
      "clv": {
        "toward": false,
        "pts": -0.0404,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "RJ Harris",
        "db": "RJ Harris"
      },
      "b": {
        "feed": "Alvin Hines",
        "db": "Alvin Hines"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5922,
      "modelClose": 0.5922,
      "marketOpen": 0.4392,
      "marketClose": 0.4783,
      "leanA": 0.153,
      "clv": {
        "toward": true,
        "pts": 0.0391,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Dricus Du Plessis",
        "db": "Dricus du Plessis"
      },
      "b": {
        "feed": "Kamaru Usman",
        "db": "Kamaru Usman"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 5,
      "aWon": 1,
      "rounds": 5,
      "modelOpen": 0.5151,
      "modelClose": 0.5151,
      "marketOpen": 0.696,
      "marketClose": 0.6548,
      "leanA": -0.1809,
      "clv": {
        "toward": true,
        "pts": 0.0412,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Tabatha Ricci",
        "db": "Tabatha Ricci"
      },
      "b": {
        "feed": "Fatima Kline",
        "db": "Fatima Kline"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5164,
      "modelClose": 0.5164,
      "marketOpen": 0.2381,
      "marketClose": 0.2042,
      "leanA": 0.2783,
      "clv": {
        "toward": false,
        "pts": -0.0339,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Chase Hooper",
        "db": "Chase Hooper"
      },
      "b": {
        "feed": "Mitch Ramirez",
        "db": "Mitch Ramirez"
      },
      "winner": "A",
      "method": "Submission",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.7434,
      "modelClose": 0.7434,
      "marketOpen": 0.7241,
      "marketClose": 0.7524,
      "leanA": 0.0193,
      "clv": {
        "toward": true,
        "pts": 0.0283,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Jared Cannonier",
        "db": "Jared Cannonier"
      },
      "b": {
        "feed": "Christian Leroy Duncan",
        "db": "Christian Leroy Duncan"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4464,
      "modelClose": 0.4465,
      "marketOpen": 0.2759,
      "marketClose": 0.2694,
      "leanA": 0.1705,
      "clv": {
        "toward": false,
        "pts": -0.0065,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Ismael Bonfim",
        "db": "Ismael Bonfim"
      },
      "b": {
        "feed": "Axel Sola",
        "db": "Axel Sola"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4714,
      "modelClose": 0.4715,
      "marketOpen": 0.3571,
      "marketClose": 0.3655,
      "leanA": 0.1143,
      "clv": {
        "toward": true,
        "pts": 0.0084,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Magomed Ankalaev",
        "db": "Magomed Ankalaev"
      },
      "b": {
        "feed": "Bogdan Guskov",
        "db": "Bogdan Guskov"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 5,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5961,
      "modelClose": 0.6375,
      "marketOpen": 0.7907,
      "marketClose": 0.8088,
      "leanA": -0.1946,
      "clv": {
        "toward": false,
        "pts": -0.0181,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Nurullo Aliev",
        "db": "Nurullo Aliev"
      },
      "b": {
        "feed": "Mike Davis",
        "db": "Mike Davis"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4173,
      "modelClose": 0.4183,
      "marketOpen": 0.5781,
      "marketClose": 0.666,
      "leanA": -0.1608,
      "clv": {
        "toward": false,
        "pts": -0.0879,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Rizvan Kuniev",
        "db": "Rizvan Kuniev"
      },
      "b": {
        "feed": "Tyrell Fortune",
        "db": "Tyrell Fortune"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5786,
      "modelClose": 0.5786,
      "marketOpen": 0.7107,
      "marketClose": 0.7434,
      "leanA": -0.1321,
      "clv": {
        "toward": false,
        "pts": -0.0327,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Santiago Ponzinibbio",
        "db": "Santiago Ponzinibbio"
      },
      "b": {
        "feed": "Sam Patterson",
        "db": "Sam Patterson"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.3954,
      "modelClose": 0.3948,
      "marketOpen": 0.2252,
      "marketClose": 0.1915,
      "leanA": 0.1702,
      "clv": {
        "toward": false,
        "pts": -0.0337,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Valter Walker",
        "db": "Valter Walker"
      },
      "b": {
        "feed": "Thomas Petersen",
        "db": "Thomas Petersen"
      },
      "winner": "A",
      "method": "Submission",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5918,
      "modelClose": 0.5918,
      "marketOpen": 0.6828,
      "marketClose": 0.6178,
      "leanA": -0.091,
      "clv": {
        "toward": true,
        "pts": 0.065,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Magomed Zaynukov",
        "db": "Magomed Zaynukov"
      },
      "b": {
        "feed": "Damian Rzepecki",
        "db": "Damian Rzepecki"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5078,
      "modelClose": 0.5078,
      "marketOpen": 0.7418,
      "marketClose": 0.7002,
      "leanA": -0.234,
      "clv": {
        "toward": true,
        "pts": 0.0416,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Magomed Tuchalov",
        "db": "Magomed Tuchalov"
      },
      "b": {
        "feed": "Brendson Ribeiro",
        "db": "Brendson Ribeiro"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5943,
      "modelClose": 0.5943,
      "marketOpen": 0.8182,
      "marketClose": 0.863,
      "leanA": -0.2239,
      "clv": {
        "toward": false,
        "pts": -0.0448,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Cody Gibson",
        "db": "Cody Gibson"
      },
      "b": {
        "feed": "Abdul Hussein",
        "db": "Abdul Hussein"
      },
      "winner": "B",
      "method": "Submission",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4194,
      "modelClose": 0.4194,
      "marketOpen": 0.2381,
      "marketClose": 0.1881,
      "leanA": 0.1813,
      "clv": {
        "toward": false,
        "pts": -0.05,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Dustin Jacoby",
        "db": "Dustin Jacoby"
      },
      "b": {
        "feed": "Muhammad Said",
        "db": "Muhammad Said"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5273,
      "modelClose": 0.5273,
      "marketOpen": 0.5996,
      "marketClose": 0.6164,
      "leanA": -0.0723,
      "clv": {
        "toward": false,
        "pts": -0.0168,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Abubakar Vagaev",
        "db": "Abubakar Vagaev"
      },
      "b": {
        "feed": "Saygid Izagakhmaev",
        "db": "Saygid Izagakhmaev"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4652,
      "modelClose": 0.465,
      "marketOpen": 0.6947,
      "marketClose": 0.6742,
      "leanA": -0.2295,
      "clv": {
        "toward": true,
        "pts": 0.0205,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Aleksandar Rakic",
        "db": "Aleksandar Rakić"
      },
      "b": {
        "feed": "Marcin Tybura",
        "db": "Marcin Tybura"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5327,
      "modelClose": 0.5011,
      "marketOpen": 0.7241,
      "marketClose": 0.7664,
      "leanA": -0.1914,
      "clv": {
        "toward": false,
        "pts": -0.0423,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Dennis Buzukja",
        "db": "Dennis Buzukja"
      },
      "b": {
        "feed": "Bogdan Grad",
        "db": "Bogdan Grad"
      },
      "winner": "B",
      "method": "Submission",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4542,
      "modelClose": 0.4542,
      "marketOpen": 0.3379,
      "marketClose": 0.3613,
      "leanA": 0.1163,
      "clv": {
        "toward": true,
        "pts": 0.0234,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Uros Medic",
        "db": "Uroš Medić"
      },
      "b": {
        "feed": "Daniel Rodriguez",
        "db": "Daniel Rodriguez"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 5,
      "modelOpen": 0.569,
      "modelClose": 0.5695,
      "marketOpen": 0.7497,
      "marketClose": 0.7642,
      "leanA": -0.1807,
      "clv": {
        "toward": false,
        "pts": -0.0145,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Dusko Todorovic",
        "db": "Dusko Todorovic"
      },
      "b": {
        "feed": "Robert Valentin",
        "db": "Robert Valentin"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5818,
      "modelClose": 0.5494,
      "marketOpen": 0.4236,
      "marketClose": 0.4037,
      "leanA": 0.1582,
      "clv": {
        "toward": false,
        "pts": -0.0199,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Vlasto Cepo",
        "db": "Vlasto Cepo"
      },
      "b": {
        "feed": "Gilbert Urbina",
        "db": "Gilbert Urbina"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4839,
      "modelClose": 0.4852,
      "marketOpen": 0.7241,
      "marketClose": 0.7447,
      "leanA": -0.2402,
      "clv": {
        "toward": false,
        "pts": -0.0206,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Mateusz Rebecki",
        "db": "Mateusz Rębecki"
      },
      "b": {
        "feed": "Kyle Prepolec",
        "db": "Kyle Prepolec"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.6397,
      "modelClose": 0.6392,
      "marketOpen": 0.7428,
      "marketClose": 0.8411,
      "leanA": -0.1031,
      "clv": {
        "toward": false,
        "pts": -0.0983,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Oban Elliott",
        "db": "Oban Elliott"
      },
      "b": {
        "feed": "Michael Oliveira",
        "db": "Michael Oliveira"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.3308,
      "modelClose": 0.3309,
      "marketOpen": 0.2136,
      "marketClose": 0.2428,
      "leanA": 0.1172,
      "clv": {
        "toward": true,
        "pts": 0.0292,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Jovan Leka",
        "db": "Jovan Leka"
      },
      "b": {
        "feed": "Alexander Poppeck",
        "db": "Alexander Poppeck"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.6879,
      "modelClose": 0.635,
      "marketOpen": 0.6728,
      "marketClose": 0.718,
      "leanA": 0.0151,
      "clv": {
        "toward": true,
        "pts": 0.0452,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Nina Milošević",
        "db": "Nina Milosevic"
      },
      "b": {
        "feed": "Hailey Cowan",
        "db": "Hailey Cowan"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.6,
      "modelClose": 0.6,
      "marketOpen": 0.7619,
      "marketClose": 0.8071,
      "leanA": -0.1619,
      "clv": {
        "toward": false,
        "pts": -0.0452,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Marina Spasić",
        "db": "Marina Spasic"
      },
      "b": {
        "feed": "Stephanie Luciano",
        "db": "Stephanie Luciano"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5064,
      "modelClose": 0.5224,
      "marketOpen": 0.2905,
      "marketClose": 0.262,
      "leanA": 0.2159,
      "clv": {
        "toward": false,
        "pts": -0.0285,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Miloš Janičić",
        "db": "Milos Janicic"
      },
      "b": {
        "feed": "Noah Gugnon",
        "db": "Noah Gugnon"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5093,
      "modelClose": 0.5143,
      "marketOpen": 0.5635,
      "marketClose": 0.4977,
      "leanA": -0.0542,
      "clv": {
        "toward": true,
        "pts": 0.0658,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Mark Vologdin",
        "db": "Mark Vologdin"
      },
      "b": {
        "feed": "Borislav Nikolić",
        "db": "Borislav Nikolic"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4117,
      "modelClose": 0.5883,
      "marketOpen": 0.3574,
      "marketClose": 0.6447,
      "leanA": 0.0543,
      "clv": {
        "toward": true,
        "pts": 0.2873,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Ty Miller",
        "db": "Ty Miller"
      },
      "b": {
        "feed": "Billy Goff",
        "db": "Billy Ray Goff"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5272,
      "modelClose": 0.5277,
      "marketOpen": 0.712,
      "marketClose": 0.7685,
      "leanA": -0.1848,
      "clv": {
        "toward": false,
        "pts": -0.0565,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Diyar Nurgozhay",
        "db": "Diyar Nurgozhay"
      },
      "b": {
        "feed": "Bruno Lopes",
        "db": "Bruno Lopes"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.57,
      "modelClose": 0.5653,
      "marketOpen": 0.5798,
      "marketClose": 0.5934,
      "leanA": -0.0098,
      "clv": {
        "toward": false,
        "pts": -0.0136,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Steven Asplund",
        "db": "Steven Asplund"
      },
      "b": {
        "feed": "Guilherme Pat",
        "db": "Guilherme Pat"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5673,
      "modelClose": 0.5673,
      "marketOpen": 0.6705,
      "marketClose": 0.7258,
      "leanA": -0.1032,
      "clv": {
        "toward": false,
        "pts": -0.0553,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Juliana Miller",
        "db": "Juliana Miller"
      },
      "b": {
        "feed": "Ravena Oliveira",
        "db": "Ravena Oliveira"
      },
      "winner": "A",
      "method": "Submission",
      "round": 2,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.6097,
      "modelClose": 0.6112,
      "marketOpen": 0.6742,
      "marketClose": 0.7258,
      "leanA": -0.0645,
      "clv": {
        "toward": false,
        "pts": -0.0516,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Louie Sutherland",
        "db": "Louie Sutherland"
      },
      "b": {
        "feed": "Jose Montanha",
        "db": "Jose Montanha"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.482,
      "modelClose": 0.482,
      "marketOpen": 0.6288,
      "marketClose": 0.6515,
      "leanA": -0.1468,
      "clv": {
        "toward": false,
        "pts": -0.0227,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Manoel Sousa",
        "db": "Manoel Sousa"
      },
      "b": {
        "feed": "Richie Miranda",
        "db": "Richie Miranda"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.601,
      "modelClose": 0.601,
      "marketOpen": 0.7094,
      "marketClose": 0.7258,
      "leanA": -0.1084,
      "clv": {
        "toward": false,
        "pts": -0.0164,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Miles Johns",
        "db": "Miles Johns"
      },
      "b": {
        "feed": "Gianni Vazquez",
        "db": "Gianni Vazquez"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4729,
      "modelClose": 0.4729,
      "marketOpen": 0.6027,
      "marketClose": 0.6181,
      "leanA": -0.1298,
      "clv": {
        "toward": false,
        "pts": -0.0154,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Amanda Lemos",
        "db": "Amanda Lemos"
      },
      "b": {
        "feed": "Alexia Thainara",
        "db": "Alexia Thainara"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.3633,
      "modelClose": 0.3603,
      "marketOpen": 0.3332,
      "marketClose": 0.272,
      "leanA": 0.0301,
      "clv": {
        "toward": false,
        "pts": -0.0612,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Carlos Diego Ferreira",
        "db": "Diego Ferreira"
      },
      "b": {
        "feed": "Billy Quarantillo",
        "db": "Billy Quarantillo"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4918,
      "modelClose": 0.4923,
      "marketOpen": 0.5994,
      "marketClose": 0.6123,
      "leanA": -0.1076,
      "clv": {
        "toward": false,
        "pts": -0.0129,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Mateusz Gamrot",
        "db": "Mateusz Gamrot"
      },
      "b": {
        "feed": "Quillan Salkilld",
        "db": "Quillan Salkilld"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 5,
      "modelOpen": 0.4593,
      "modelClose": 0.4591,
      "marketOpen": 0.4513,
      "marketClose": 0.4343,
      "leanA": 0.008,
      "clv": {
        "toward": false,
        "pts": -0.017,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Tom Pagliarulo",
        "db": "Tom Pagliarulo"
      },
      "b": {
        "feed": "Ananias Mulumba",
        "db": "Ananias Mulumba"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.3892,
      "modelClose": 0.3892,
      "marketOpen": 0.4085,
      "marketClose": 0.4114,
      "leanA": -0.0193,
      "clv": {
        "toward": false,
        "pts": -0.0029,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Bilal Hasan",
        "db": "Bilal Hasan"
      },
      "b": {
        "feed": "Mridul Saikia",
        "db": "Mridul Saikia"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.572,
      "modelClose": 0.572,
      "marketOpen": 0.884,
      "marketClose": 0.9424,
      "leanA": -0.312,
      "clv": {
        "toward": false,
        "pts": -0.0584,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Abe Alsaghir",
        "db": "Abe Alsaghir"
      },
      "b": {
        "feed": "Fabrizio Escarrega",
        "db": "Fabrizio Escarrega"
      },
      "winner": "A",
      "method": "Decision - Split",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5202,
      "modelClose": 0.5202,
      "marketOpen": 0.5385,
      "marketClose": 0.4464,
      "leanA": -0.0183,
      "clv": {
        "toward": true,
        "pts": 0.0921,
        "leaned": false
      }
    }
  ]
};
