// AUTO-GENERATED by scripts/gen-scorecard-data.cjs — do not edit by hand.
export default {
  "generatedAt": "2026-07-22T01:18:31.278Z",
  "scorecard": {
    "generatedAt": "2026-07-22T01:18:31.174Z",
    "nGraded": 22,
    "note": "Internal proof-of-concept. Pre-upgrade CLV uses self-snapshotted close (approximate).",
    "calibration": [
      {
        "band": "30-40%",
        "n": 3,
        "predicted": 0.3668,
        "actual": 0.6667
      },
      {
        "band": "40-50%",
        "n": 6,
        "predicted": 0.4442,
        "actual": 0.3333
      },
      {
        "band": "50-60%",
        "n": 8,
        "predicted": 0.5393,
        "actual": 0.625
      },
      {
        "band": "60-70%",
        "n": 3,
        "predicted": 0.634,
        "actual": 0.6667
      },
      {
        "band": "70-80%",
        "n": 2,
        "predicted": 0.728,
        "actual": 1
      }
    ],
    "accuracy": {
      "model": 0.6364,
      "marketClose": 0.7273
    },
    "brier": {
      "modelOpen": 0.2298,
      "marketClose": 0.1551
    },
    "logloss": {
      "modelOpen": 0.6515,
      "marketClose": 0.4793
    },
    "clv": {
      "nWithMovement": 22,
      "hitRate": 0.5455,
      "avgMovePts": -0.0061,
      "leanedOnly": {
        "n": 19,
        "hitRate": 0.5789,
        "avgMovePts": 0.0032
      }
    }
  },
  "graded": [
    {
      "event": "UFC 329",
      "a": {
        "feed": "Cody Durden",
        "db": "Cody Durden"
      },
      "b": {
        "feed": "Alessandro Costa",
        "db": "Alessandro Costa"
      },
      "winner": "B",
      "method": "Submission",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.3972,
      "modelClose": 0.3973,
      "marketOpen": 0.3111,
      "marketClose": 0.3322,
      "leanA": 0.0861,
      "clv": {
        "toward": true,
        "pts": 0.0211,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Damian Pinas",
        "db": "Damian Pinas"
      },
      "b": {
        "feed": "Cesar Almeida",
        "db": "Cesar Almeida"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.7125,
      "modelClose": 0.7125,
      "marketOpen": 0.6531,
      "marketClose": 0.6895,
      "leanA": 0.0594,
      "clv": {
        "toward": true,
        "pts": 0.0364,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Tracy Cortez",
        "db": "Tracy Cortez"
      },
      "b": {
        "feed": "Wang Cong",
        "db": "Wang Cong"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4407,
      "modelClose": 0.4407,
      "marketOpen": 0.4892,
      "marketClose": 0.4837,
      "leanA": -0.0485,
      "clv": {
        "toward": true,
        "pts": 0.0055,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Luke Riley",
        "db": "Luke Riley"
      },
      "b": {
        "feed": "Kai Kamaka",
        "db": "Kai Kamaka III"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5531,
      "modelClose": 0.5531,
      "marketOpen": 0.7163,
      "marketClose": 0.6656,
      "leanA": -0.1632,
      "clv": {
        "toward": true,
        "pts": 0.0507,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Cody Garbrandt",
        "db": "Cody Garbrandt"
      },
      "b": {
        "feed": "Adrian Yanez",
        "db": "Adrian Yanez"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5165,
      "modelClose": 0.5165,
      "marketOpen": 0.2185,
      "marketClose": 0.2198,
      "leanA": 0.298,
      "clv": {
        "toward": true,
        "pts": 0.0013,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Gable Steveson",
        "db": "Gable Steveson"
      },
      "b": {
        "feed": "Elisha Ellison",
        "db": "Elisha Ellison"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5266,
      "modelClose": 0.5266,
      "marketOpen": 0.9213,
      "marketClose": 0.9042,
      "leanA": -0.3947,
      "clv": {
        "toward": true,
        "pts": 0.0171,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Robert Whittaker",
        "db": "Robert Whittaker"
      },
      "b": {
        "feed": "Nikita Krylov",
        "db": "Nikita Krylov"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4402,
      "modelClose": 0.4402,
      "marketOpen": 0.5635,
      "marketClose": 0.5293,
      "leanA": -0.1233,
      "clv": {
        "toward": true,
        "pts": 0.0342,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "John Garza",
        "db": "John Garza"
      },
      "b": {
        "feed": "Farid Basharat",
        "db": "Farid Basharat"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4733,
      "modelClose": 0.4733,
      "marketOpen": 0.1729,
      "marketClose": 0.1677,
      "leanA": 0.3004,
      "clv": {
        "toward": false,
        "pts": -0.0052,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Paddy Pimblett",
        "db": "Paddy Pimblett"
      },
      "b": {
        "feed": "Benoit Saint-Denis",
        "db": "Benoît Saint Denis"
      },
      "winner": "A",
      "method": "Submission",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.3148,
      "modelClose": 0.3148,
      "marketOpen": 0.4428,
      "marketClose": 0.4417,
      "leanA": -0.128,
      "clv": {
        "toward": true,
        "pts": 0.0011,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Max Holloway",
        "db": "Max Holloway"
      },
      "b": {
        "feed": "Conor McGregor",
        "db": "Conor McGregor"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 5,
      "modelOpen": 0.6228,
      "modelClose": 0.6227,
      "marketOpen": 0.6636,
      "marketClose": 0.7356,
      "leanA": -0.0408,
      "clv": {
        "toward": false,
        "pts": -0.072,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "King Green",
        "db": "King Green"
      },
      "b": {
        "feed": "Terrance Mckinney",
        "db": "Terrance McKinney"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.3884,
      "modelClose": 0.3883,
      "marketOpen": 0.4254,
      "marketClose": 0.4474,
      "leanA": -0.037,
      "clv": {
        "toward": false,
        "pts": -0.022,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Brandon Royval",
        "db": "Brandon Royval"
      },
      "b": {
        "feed": "Lone'er Kavanagh",
        "db": "Lone'er Kavanagh"
      },
      "winner": "A",
      "method": "Submission",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.577,
      "modelClose": 0.5771,
      "marketOpen": 0.3379,
      "marketClose": 0.3273,
      "leanA": 0.2391,
      "clv": {
        "toward": false,
        "pts": -0.0106,
        "leaned": true
      }
    },
    {
      "event": "UFC 329",
      "a": {
        "feed": "Cory Sandhagen",
        "db": "Cory Sandhagen"
      },
      "b": {
        "feed": "Mario Bautista",
        "db": "Mario Bautista"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5175,
      "modelClose": 0.5174,
      "marketOpen": 0.5721,
      "marketClose": 0.5644,
      "leanA": -0.0546,
      "clv": {
        "toward": true,
        "pts": 0.0077,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Levi Rodrigues",
        "db": "Levi Rodrigues Jr."
      },
      "b": {
        "feed": "Felipe Franco",
        "db": "Felipe Franco"
      },
      "winner": "B",
      "method": "KO/TKO",
      "round": 2,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.6324,
      "modelClose": 0.6324,
      "marketOpen": 0.6279,
      "marketClose": 0.5711,
      "leanA": 0.0045,
      "clv": {
        "toward": false,
        "pts": -0.0568,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Tommy McMillen",
        "db": "Tommy McMillen"
      },
      "b": {
        "feed": "Alberto Montes",
        "db": "Alberto Montes"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.4351,
      "modelClose": 0.4351,
      "marketOpen": 0.438,
      "marketClose": 0.6038,
      "leanA": -0.0029,
      "clv": {
        "toward": false,
        "pts": -0.1658,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Alden Coria",
        "db": "Alden Coria"
      },
      "b": {
        "feed": "Stewart Nicoll",
        "db": "Stewart Nicoll"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.6469,
      "modelClose": 0.6469,
      "marketOpen": 0.8757,
      "marketClose": 0.88,
      "leanA": -0.2288,
      "clv": {
        "toward": false,
        "pts": -0.0043,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Anna Melisano",
        "db": "Anna Melisano"
      },
      "b": {
        "feed": "Dione Barbosa",
        "db": "Dione Barbosa"
      },
      "winner": "B",
      "method": "Submission",
      "round": 1,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4295,
      "modelClose": 0.4295,
      "marketOpen": 0.2133,
      "marketClose": 0.1729,
      "leanA": 0.2162,
      "clv": {
        "toward": false,
        "pts": -0.0404,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "RJ Harris",
        "db": "RJ Harris"
      },
      "b": {
        "feed": "Alvin Hines",
        "db": "Alvin Hines"
      },
      "winner": "A",
      "method": "KO/TKO",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.5922,
      "modelClose": 0.5922,
      "marketOpen": 0.4392,
      "marketClose": 0.4783,
      "leanA": 0.153,
      "clv": {
        "toward": true,
        "pts": 0.0391,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Dricus Du Plessis",
        "db": "Dricus du Plessis"
      },
      "b": {
        "feed": "Kamaru Usman",
        "db": "Kamaru Usman"
      },
      "winner": "A",
      "method": "Decision - Unanimous",
      "round": 5,
      "aWon": 1,
      "rounds": 5,
      "modelOpen": 0.5151,
      "modelClose": 0.5151,
      "marketOpen": 0.696,
      "marketClose": 0.6548,
      "leanA": -0.1809,
      "clv": {
        "toward": true,
        "pts": 0.0412,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Tabatha Ricci",
        "db": "Tabatha Ricci"
      },
      "b": {
        "feed": "Fatima Kline",
        "db": "Fatima Kline"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.5164,
      "modelClose": 0.5164,
      "marketOpen": 0.2381,
      "marketClose": 0.2042,
      "leanA": 0.2783,
      "clv": {
        "toward": false,
        "pts": -0.0339,
        "leaned": true
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Chase Hooper",
        "db": "Chase Hooper"
      },
      "b": {
        "feed": "Mitch Ramirez",
        "db": "Mitch Ramirez"
      },
      "winner": "A",
      "method": "Submission",
      "round": 1,
      "aWon": 1,
      "rounds": 3,
      "modelOpen": 0.7434,
      "modelClose": 0.7434,
      "marketOpen": 0.7241,
      "marketClose": 0.7524,
      "leanA": 0.0193,
      "clv": {
        "toward": true,
        "pts": 0.0283,
        "leaned": false
      }
    },
    {
      "event": "UFC Fight Night",
      "a": {
        "feed": "Jared Cannonier",
        "db": "Jared Cannonier"
      },
      "b": {
        "feed": "Christian Leroy Duncan",
        "db": "Christian Leroy Duncan"
      },
      "winner": "B",
      "method": "Decision - Unanimous",
      "round": 3,
      "aWon": 0,
      "rounds": 3,
      "modelOpen": 0.4464,
      "modelClose": 0.4465,
      "marketOpen": 0.2759,
      "marketClose": 0.2694,
      "leanA": 0.1705,
      "clv": {
        "toward": false,
        "pts": -0.0065,
        "leaned": true
      }
    }
  ]
};
